google/go-github

README.md

Fixes references to depreciated goauth2 libaray and replaces example
with the recomended oauth2 implimentation.

Update authentication section of README

---

github/orgs_teams.go
github/orgs_teams_test.go

Both have been deprecated.
Fixes #190.
- AddTeamMember: https://developer.github.com/v3/orgs/teams/#add-team-member
- RemoveTeamMember: https://developer.github.com/v3/orgs/teams/#remove-team-member
/cc @willnorris

orgs_teams: remove AddTeamMember and RemoveTeamMember

---

github/github.go
github/licenses.go
github/licenses_test.go
github/repos.go
github/repos_test.go

licenses: add support for the OSS licenses API provided by GitHub.

---

github/repos_deployments.go

There's no way of serializing/requesting an empty required_contexts that
is needed for bypassing the commit status checks for the ref.
It's a breaking change but will allow to serialize an empty array and
omit empty value as expected.
Example: http://play.golang.org/p/6Jsh8L7AfO

use *[]string for DeploymentRequest.RequiredContexts

---

github/activity_star.go
github/activity_star_test.go
github/github.go

Supports the updated starring API as mentioned in issue #188.
There is now a new struct called StarredRepository which holds a pointer to a Repository and the new `starred_at` timestamp. This was the cleanest way I found to go about this
For now there is a special media type to request the new API. I've added a TODO for it to be deleted when the new API fully launches.

Support for updated starring API

---

github/repos_releases.go
github/repos_releases_test.go

Fixes #186 
Adds `GetLatestRelease` and `GetReleaseByTag` to RepositoriesService.

New release endpoints

---

github/misc.go
github/misc_test.go

GitHub occasionally changes the IP addresses from which GitHub Pages
websites are served. For users of the service, they must upgrade any A
records to these IP addresses to continue using the service. This patch
provides this data in the `APIMeta` struct as the property `Pages` and
populates from the /meta endpoint.
Release Announcement:
https://developer.github.com/changes/2015-06-11-pages-a-records/
Fixes #212.
/cc @willnorris

misc: add GitHub Pages IP addresses

---

github/issues.go

It was inadvertently introduced in 65fa4d43e9f1e4ba1a67b120d4cd17285c8fe013.

Fix typos in docs.

---

github/issues_events.go

Documented at https://developer.github.com/v3/issues/events/#events-1 and https://developer.github.com/v3/issues/events/#attributes.
> Event "renamed":
> 	- The issue title was changed.
> Attribute "rename":
> 	- An object containing rename details including ‘from’ and ‘to’
> 	attributes. Only provided for ‘renamed’ events.
A live example of such event can be seen here:
https://api.github.com/repos/emersion/go-js-canvas/issues/events/451244229
Relevant fields snippet:
```JSON
...
"event": "renamed",
"commit_id": null,
"commit_url": null,
"created_at": "2015-11-01T02:14:26Z",
"rename": {
"from": "Are you aware of dom package containing this already?",
"to": "Are you aware of DOM package containing this already?"
},
...
```

Add support for 'renamed' issue events.

---

github/issues_events.go

I processed every IssueEvent from the entire history of the golang/go repository and these are all the ones I found. So I have some belief that they might be a complete set. :-)

github: document and add support for all IssueEvent types

---

github/issues.go

The value `all` is also possible for State. See https://developer.github.com/v3/issues/#list-issues and https://developer.github.com/v3/issues/#list-issues-for-a-repository.

github: Document all possible values for IssueList{,ByRepo}Options.State.

---

github/github.go
github/github_test.go

Previously, concurrent calls to `Client.Do` would have data races writing `Client.Rate`. Protect it with a mutex.
Resolves #253.
I've been using/testing it for the last week or two, and I haven't spotted any other issues with concurrency.
Technically, this is a ever-so-slightly breaking API change, since `Rate` was previously an exported struct field, but now it's a method, so callers will need to change `client.Rate` to `client.Rate()`. I don't see any other way around this. Aside from exporting the mutex and keeping `Rate` as is, but that would require the user to know about the mutex and lock it when reading `Rate`. That seems very unfriendly API.

Fix data race surrounding Client.Rate.

---

github/github.go
github/repos.go
github/repos_test.go

For more information about the preview see here:
https://developer.github.com/changes/2015-11-11-protected-branches-api/
This adds only retrieving the information and not setting it. Setting
will come in a later commit (if that one here is okay).
I tried to follow the naming guidelines as much as possible and
hopefully I made it right the first time. :-)

Add initial support for protected branches

---

github/doc.go
github/github.go

- Rate is now a method, not a field.
- Mention RateLimits rather than RateLimit since the latter is deprecated.
- Use Go convention for marking deprecated identifiers. See https://github.com/golang/blog/commit/257114af91a0defb1fc2c16c7f4ae2429b8a4e0f.

Minor Rate, RateLimits documentation fixes.

---

github/pulls_comments.go

In V3 of the GitHub API, pull request comments are created in two ways. The first way is to create a comment on a specific line of a file in a commit with the following parameters:
| Name      | Type    | Description                                            |
|-----------|---------|--------------------------------------------------------|
| body      | string  | Required. The text of the comment                      |
| commit_id | string  | Required. The SHA of the commit to comment on.         |
| path      | string  | Required. The relative path of the file to comment on. |
| position  | integer | Required. The line index in the diff to comment on.    |
And the second way is through a reply to an existing comment with the following parameters:
| Name        | Type    | Description …

Add InReplyTo to PullRequestComment struct

---

github/github.go
github/repos_releases.go
github/repos_releases_test.go

If a redirect to AWS occurs, then the redirect will be canceled and
the redirect Location will be returned in the string and the
io.ReadCloser will be nil. At this point, the user would need to
perform the http.Get on the returned URL in a different http.Client
(without the GitHub authentication transport).
Fixes #246.
Change-Id: I4fe2dfc9cd0ce81934a07f11a6296e71c7dd51a0

change DownloadReleaseAsset API to additionally return a URL

---

github/github.go
github/migrations.go
github/migrations_test.go

The Migrations API is the GitHub equivalent of Google TakeOut.
It allows you to create an archive of one or more repositories
that you can download and later use for import purposes.
See: https://help.github.com/enterprise/2.4/admin/guides/migrations/exporting-the-github-com-organization-s-repositories/
for more information.
Fixes #292.
Change-Id: Id20624acb4f16a2aade9143e723c8eb85ec75402

go-github: add support for Migrations API

---

github/github.go

On successful queries (on errors ReadAll runs in CheckResponse), the
Response.Body is not read all the way to the EOF as json.Decoder is used,
which stops at the end of the object, which is probably followed by a \n.
Then, Response.Body.Close() is called.  When that happens with a non-drained
Body, the TCP/TLS connection is closed (which makes sense, in case there was
still a lot to read from the network), stopping the Transport from reusing
it.  Also, a library user can't drain the Body themselves because Close() is
called before passing the Response to the user.
Since we know GitHub API responses only carry a single JSON object, draining
before closing is free, and saving all those handshakes causes huge savings
in latency, bandwidth and CPU for both the client and the poor GitHub …

Drain Response.Body to enable TCP/TLS connection reuse (4x speedup)

---

github/repos.go
github/repos_test.go

Note: GetByID uses the undocumented GitHub API endpoint `/repositories/:id`.
Include license preview Accept header.
Helps #329.
This commit is based on https://github.com/sourcegraph/go-github/commit/da394ef1f53de34e9c3e5782ca27589df32b426c which has been tested in production. It has been amended by me to include [Licences API](https://developer.github.com/changes/2015-03-09-licenses-api/) header, improved documentation and commit message, with appropriate updates to the test.
I've tested it locally with the Licences API header to make sure it works, and I've confirmed that it did.

Add RepositoriesService.GetByID method.

---

github/pulls.go

On webhooks, when the PR is assigned you get
```
{
"action": "assigned",
"number": 73,
"pull_request": {
"url":
...
"body": "",
"created_at": "2016-04-13T13:51:23Z",
"updated_at": "2016-04-13T13:51:37Z",
"closed_at": null,
"merged_at": null,
"merge_commit_sha": "333a18e2215ec59bfd09fefd730f71492a52f983",
"assignee": {
"login": "someuser",
"id": ...
```

Add "assignee" field in pull request

---

github/github.go
github/repos_commits.go
github/repos_commits_test.go

See: https://developer.github.com/changes/2016-04-12-commit-reference-sha-api-is-now-official/
Fixes #297.
Change-Id: I9cc3c4a2e143c6b3ca4677d8d27ea7af96341dd9

change custom accept header for support of commit reference SHA-1 API

---

github/repos_releases.go
github/repos_releases_test.go

If `RepositoriesService.DownloadReleaseAsset` encounters an error from the GitHub API (e.g., 404 Not Found), The error would not be returned by the method and instead the error payload would be delivered as the `io.ReadCloser`. This patch resolves this with `CheckResponse`.
Fixes #343
/cc @willnorris (thanks for the help!)

Correctly handle API errors when downloading Release Assets

---

github/github_test.go

Print the actual value that doesn't match.
Minor followup fix for c3f5683ad1dfe8c2c5aad4a7bbe536cbdc4a1009 (#277).

Improve test error message.

---

.travis.yml
github/repos_releases_test.go
tests/integration/authorizations_test.go
tests/integration/doc.go
tests/integration/github_test.go

Also make tip a fast-finish allowed failure. That way, if CI fails on tip due to a temporary issue with tip, it will not break build status. However, it's still possible to see tip build status by looking at CI details page.
Expect CI to fail on this PR because there are known go vet issues, those will be fixed in next commit.

Travis: Run gofmt -s, go vet, go test -race, add Go 1.6.

---

github/github.go
github/github_test.go

This (minor) optimization is possible because the client keeps track of the rate limits from previous API calls, and GitHub's rate limiting model is known in advance, and is predictable.
In situations where it's possible to predict that the network API call will result in a `*RateLimitError`, simply return it immediately instead of making the network API call to GitHub's servers. This is both faster for the client (by around 9700 times in my benchmarks) because it avoids the network round-trip latency, and better for GitHub's servers that won't need to needlessly reject network requests.
Note that this optimization only kicks in when the client is already exceeding the rate limit and it hasn't been reset yet. It has no effect during most normal usage when rate limit is not exceeded.
I …

Predict *RateLimitError, return immediately without network call (9700x speedup when rate limit exceeded).

---

github/github_test.go

An upcoming change to Go 1.7 allows the json package to be able to encode maps
with the integer keys. Thus, this is no longer a good way to generate intentional
JSON failures.
Reference: https://github.com/golang/go/commit/f05c3aa24d815cd3869153750c9875e35fc48a6e

fix unit tests for go1.7 release

---

github/messages.go
github/messages_test.go

Change-Id: I1c80b8eb7816efc9b83e6b8be956430c68809d5e

go-github: add utilities for processing payload messages

---

github/users.go

Fixes #278.
Change-Id: Ia1d0c1f6b395d493714d91e0f6e79dc2506f8fde

document 'since' pagination for Users.ListAll

---

github/reactions.go

It's harmless, but inconsistent. All other such URLs in this package do not use a leading slash.
See https://github.com/google/go-github/commit/09a37d57ac99a8938444e44375db8660c2184696#commitcomment-17927607.

Remove leading slash from ReactionsService.DeleteReaction URL.

---

github/github.go
github/repos_collaborators.go
github/repos_collaborators_test.go
github/repos_invitations.go
github/repos_invitations_test.go
github/users.go
github/users_gpg_keys.go
github/users_test.go

Fixes #371.
Change-Id: I97f2fc28ce048442ee8af3bd11c48b5b2084e09b

add support for new repository invitations

---

tests/integration/activity_test.go
tests/integration/users_test.go

Note that `TestUsers_Keys` still fails for general users
but will need to be addressed later.
Fixes #366.
Change-Id: I35d8a73c2daed08df7d60085b1585f48caee9a95

make integration tests pass even if already watching this repo

---

github/repos.go
github/repos_test.go

Also updates comments in RepositoryListOptions to match the Github API docs
(https://developer.github.com/v3/repos/#list-your-repositories).
Fixes #231.

Add support for affiliation and visibility in RepositoryListOptions.

---

github/issues.go
github/pulls.go

In [events](https://developer.github.com/v3/activity/events/types/#pullrequestevent), the `id` field is present both in the Issue and PullRequest objects.
This PR adds them.

Add missing ID fields to PullRequest and Issue structs

---

README.md
github/doc.go

Fixes #397.
Change-Id: I30ce336e3a36cf5758b9bf52b9dd77f7c1df5f27

Sync doc.go and README.md

---

github/github.go

This is largely a style change. In the case of `NewRequest` and `NewUploadRequest`, it is completely a noop given current code (since a new request is created, and each header is added only one time). For `BasicAuthTransport`, it's a noop as long as incoming request doesn't already have "X-GitHub-OTP" header set (and if it did, then this is a better behavior to change its value rather than add a new one).
Even though these changes are largely noops, `Header.Set` is a simpler primitive to reason about, and it's more representative of the intended action. For "Content-Type", "Accept", and "User-Agent" headers, multiple such headers do not make sense, so it's better to use `Header.Set` than `Header.Add`.

Don't use Header.Add where Header.Set is sufficient.

---

github/github.go

GitHub search API ratelimits are changed recently.
Reference: https://developer.github.com/v3/search/#rate-limit
Rate limit for unauthenticated requests change from 5 to 10 per minute.
And, rate limit for authenticated requests change from 20 to 30 per minute.

Update RateLimits comment

---

github/pulls.go

Looks like support for milestones is missing in the PullRequests struct...
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Adding Milestone support for PullRequests

---

github/github.go
github/github_test.go

It's similar to `RateLimitError`, but it's a different type of rate limit error. It is documented at:
https://developer.github.com/v3/#abuse-rate-limits
Parse and include the `Retry-After` header value, if present. It is documented at:
https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits
According to GitHub support, its type is an integer value representing seconds.
Helps #431.

Add and detect AbuseRateLimitError.

---

github/repos_traffic.go
github/repos_traffic_test.go

I just removed the old `timestampMS` type, and used the common `timestamp`.
I also made the test clearer by defining the `timestamp` using `time.Date`.
Should fix #458 .

Switches to the new traffic API format

---

github/projects.go

I removed leading slash on Projects API
reasons
- unify with others
- constructing url does not work when in GitHub Enterprise environment

Remove leading slash on Projects API

---

github/repos_commits.go

This field is unused. There is no "commit message" inside of `RepositoryCommit` (higher level GitHub object), it's only inside of `Commit` (lower level git object).
It was added accidentally in #49 and not caught via test due to #491.
Followup to #49. See https://github.com/google/go-github/pull/49/files#r92034462.

Remove RepositoryCommit.Message field.

---

github/repos_pages.go

This was originally fixed in #469, but it regressed in 905f04725b7bcad81e475ce48474b87561ecc723 (although it was not a part of the PR #467 that commit was based on).
I spotted it [once again](https://github.com/google/go-github/pull/469#issuecomment-258648061) via Travis CI running with the improved `go vet` that comes in 1.8. See https://travis-ci.org/google/go-github/jobs/183406963.

Fix PagesBuild.UpdatedAt field tag.

---

github/event_types.go

See Hook type struct: 
type Hook struct {
CreatedAt *time.Time             `json:"created_at,omitempty"`
UpdatedAt *time.Time             `json:"updated_at,omitempty"`
Name      *string                `json:"name,omitempty"`
URL       *string                `json:"url,omitempty"`
Events    []string               `json:"events,omitempty"`
Active    *bool                  `json:"active,omitempty"`
Config    map[string]interface{} `json:"config,omitempty"`
_**ID        *int                   `json:"id,omitempty"`**_
}

change PingEvent.HookID to be int, not string

---

tests/integration/doc.go

Point to the README, section on integration tests, instead of an empty directory.

tests/integration: Point to a better place for more information.

---

github/activity_events_test.go
github/event_types.go

https://developer.github.com/webhooks/#payloads has been recently updated
to include installation object to support GitHub's new Integrations.
This is a WIP, I wanted to discuss this as well as still testing to ensure this works myself (but I should be more confident in a day or so).
Looking for feedback to see if this is the correct place to add the installation object which should be common across all events (when sent to an installation). Also looking for guidance on correct testing.

Add optional Installation object to Event

---

github/github.go
github/repos_traffic.go
github/repos_traffic_test.go

The traffic API is now formally released and a preview header is no longer required.
https://developer.github.com/changes/2016-12-28-end-traffic-api-preview/

Remove preview header for traffic API

---

github/repos.go

All of those fields are documented as required at https://developer.github.com/v3/repos/branches/#update-branch-protection.
In #512, we changed the API to better reflect that. However, it should still be documented that the fields are required. This is consistent with the other required fields that are also documented as required.
Additionally, note that empty slices must be non-`nil`. From running integration tests, I've seen that passing `nil` slices (which get encoded as `null` via `encoding/json`) resulted in invalid request errors such as:
No subschema in "anyOf" matched.
For 'properties/users', nil is not an array.
For 'properties/teams', nil is not an array.
Not all subschemas of "allOf" matched.
For 'anyOf/1', {"users"=>nil, "teams"=>nil} is not a null. []
Follows #512.
/cc …

Document required branch protection fields.

---

tests/integration/repos_test.go

Integration tests update branches were broken since old structures were used. This has been modified. Integration folder requires ProtectionRequest structure to be available by RepositoryService. Protection also has been changed.
Resolves #507.
Updates #310.

Update integration tests for new branch protection API.

---

github/github.go
github/github_test.go

Fixes #522. See that issue and commit messages for explanation.
I see that CI succeeds on Go 1.7 and newer, but fails on 1.6 and older. I'm going to think about how to best address that, and update this PR.

Redact secret in error from HTTP client Do.

---

github/pulls.go
github/pulls_test.go

This adds support for changing the base branch of a PR.
As per the discussion in #421, the `PullRequest` is converted into an
unexported type `pullRequestUpdate` which matches the shape expected by the
pulls PATCH endpoint.
Resolves issue #421.

pulls: Support updating base branch

---

github/event_types.go

As defined in https://developer.github.com/v3/activity/events/types/#pushevent
Sorry, these should've been merged in with #533 at the time, and have the same conditions applied, that they're only defined in the webhook payload which contains `PushEventRepository` which is commented to only exist during a webhook. So I think it should be a simple addition.
Let me know if you'd like changes.

Additional Clone related URLs to PushEventRepository

---

github/github.go
github/issues_events.go
github/repos_comments.go

Resolves #536. Explicitly return nil when there is no error. Hopefully, this should address outstanding instances of the following pattern: 
```go
if err != nil {
return ..., err
}
return ..., err
```

Return nil explicitly when there is no error.

---

.travis.yml
README.md
github/github.go

This is part 1 of 3 PRs to resolve #526 (as was suggested to split PR #529 in https://github.com/google/go-github/pull/529#discussion_r101895336).
Please see commit message for change details:
> We need to do this in order to be able to resolve #526 without unreasonable compromises.
> 
> That's the minimum version that has context package in standard library, and built-in support for it inside net/http package. Now that Go 1.8 is out, this "current version, plus one back".
> 
> Bump up the library version in anticipation of breaking API changes in following commits. It makes sense to bump it now because this commit drops support for Go versions 1.4, 1.5 and 1.6, so we can say that version 2 is the latest supported by older Go versions.
> 
> Helps #526.

Require Go 1.7 and newer.

---

github/activity_events.go
github/event_types.go
github/github.go
github/github_test.go
github/misc_test.go
github/orgs_teams_test.go
github/repos_contents.go
github/repos_contents_test.go
github/repos_deployments.go
github/repos_hooks.go

**DO NOT MERGE:** Please note the base of this PR is currently the `require-go17-plus` branch rather than `master`. This PR is for review purposes only. Once #554 is merged, I will change base of this PR to `master` and it can be mergeable then.
This is part 2 of 3 PRs to resolve #526 (as was suggested to split PR #529 in https://github.com/google/go-github/pull/529#discussion_r101895336).
Please see commit message for change details:
> This is a breaking API change. However, it removes things that were deprecated and shouldn't be used anymore (including something that's available in standard library).
>
> Next commit will be a large breaking API change anyway, so it makes more sense to get rid of the deprecated things instead of updating their API.
>
> `http.StatusUnprocessableEntity` …

Remove deprecated identifiers.

---

github/github.go

This is a followup to #555. /cc @gmlewis
`mostRecent` was created specifically to support `Rate` method in #347. That method is now gone (removed in #555), so `mostRecent` is unused and can be safely removed.

Remove unused Client.mostRecent.

---

examples/basicauth/main.go

According to https://golang.org/ref/spec#Type_assertions:
> For an expression `x` of interface type and a type `T`, the primary expression
>
>     x.(T)
>
> asserts that `x` is not nil and that the value stored in `x` is of type `T`. [...] The value of `ok` is `true` if the assertion holds.
Therefore, this if statement can be simplified without changing behavior.
I also made a proposal for this check in https://github.com/dominikh/go-tools/issues/34.

examples/basicauth: Simplify comma-ok type assertion in if statement.

---

github/activity_notifications.go
github/activity_star.go
github/activity_watching.go
github/authorizations.go
github/event_types.go
github/gists.go
github/gitignore.go
github/issues_milestones.go
github/messages.go
github/orgs_members.go
github/repos.go
github/repos_collaborators.go
github/repos_contents.go
github/repos_releases.go
github/repos_stats.go
github/search.go

While reviewing #551, I noticed that there were various slight variations in the phrasing of comments with the form:
// GitHub API docs: https://developer.github.com/v3/...
This change makes them all consistent.
Also fix "GitHub" misspelled as "Github" in a few places.
Followup to #551. /cc @kevinburke

Improve consistency of "GitHub API docs" strings in comments.

---

.travis.yml
github/issues.go

~~Testing this out and iterating on it.~~ Ready to review and merge now.
This should help us catch situations where we forget to run `go generate` after a change.
This idea comes from https://github.com/google/go-github/pull/573#issuecomment-284206455. /cc @gmlewis

Travis: Check that go generate produces zero diff in Travis CI.

---

github/github_test.go
github/repos.go
github/search.go

The common theme of this cleanup PR is to prefer setting things, instead of adding, in places where setting is sufficient (i.e., the current adding behavior is provably never done more than once for the same key), and it's a better fit for the intended behavior.
The motivation to do so is because set communicates the underlying intended action better, and it's simpler to reason about, more readable. Readers can see that there will not be multiple entries of the same key without having to verify that by reading additional code. It also fixes inconsistencies in the code in some places.
The PR consists of 4 commits, see commit message of each commit for details and rationale of each distinct change.

Prefer setting over adding, where setting is sufficient and better fits intention.

---

github/github_test.go

This is a minor refactor that is a noop. Do it because the new order seems more readable and logical. It's also more consistent with the comment.
This tiny refactor is extracted from #568.

Refactor test to first Add(time.Minute), then Round(time.Second).

---

github/gists.go
github/gists_test.go
github/github-accessors.go

Found on [Go Report Card](https://goreportcard.com/report/github.com/google/go-github)

fix misspelling in GistCommit struct

---

github/activity_events.go
github/activity_events_test.go
github/messages.go

The `Event.Payload` function can fail in instances when it receives invalid
json. (example: when parsing a webhook that is set to application/x-www-form-urlencoded)
If this happens, we shouldn't panic but instead return an error to let the
caller know about the failure.
Added in a new function, `Event.ParsePayload` to take its place a depreciated
the old function.
Also, it looks like this is the only place where we are panicing in this library. https://github.com/google/go-github/search?q=panic&type=Code&utf8=%E2%9C%93

Don't panic when processing event payload

---

github/git_commits.go
github/git_commits_test.go
github/pulls.go
github/pulls_test.go

This also changes the logic of `Git.CreateCommit` to ensure that the `commit` argument is non-nil.
I am against changing this argument to a value because it is a non-trivial struct and makes sense (to me) to be passed by reference.
Fixes #531.
Change-Id: Ifc6640db138e4ea936f3c3077c1563fe3eedd450

Document Git.CreateCommit and PullRequests.Edit arguments

---

github/github.go
github/repos_invitations.go
github/repos_invitations_test.go

All repository routes on the GitHub API can accessed via /repositories/:id _and_ /repos/:owner/:repo. For whatever reason, the documentation for the invitation routes only references the former, but both work correctly.
Repository invitations are the only functions in google/go-github to use the :id style routes, so I'd propose we change them to use :owner/:repo as that will likely be much more convenient for users of this library.

Invitation methods take :owner/:repo

---

github/github-accessors.go
github/pulls.go

Add the maintainer_can_modify option to the PullRequest structs

---

github/issues_milestones.go

The state field was missing "all".
The sort field listed "due_date" instead of "due_on" (but had due_on
correctly elsewhere).
See https://developer.github.com/v3/issues/milestones/#list-milestones-for-a-repository

Fix MilestoneListOptions docs.

---

github/repos_contents.go

This is simpler and more readable.
Helps #536.

Return nil error explicitly in RepositoriesService.GetContents.

---

github/github-accessors.go
github/orgs_teams.go
github/orgs_teams_test.go

In GitHub Enterprise, the teams API routes include `ldap_dn` if the team is being synchronized with LDAP.

Adds LDAPDN field to Team

---

github/issues_events.go

I've not updated the comment:
>        //     assigned, unassigned                                                                         
>        //       The Actor assigned the issue to or removed the assignment from the Assignee.               
to keep it consistent with [Github documentation](https://developer.github.com/v3/issues/events/) even though it is clearly incorrect.

Add Assigner field to issues_events

---

github/issues_events.go

The current phrase reads as if the "Actor" field contains the
information about the user who changed the assignment, but this
information is actually in the "Assigner" field.
Fix the description of `assigned, unassigned` event to reflect
that.
Is that clearer?

Update `IssueEvent.Event` assign/unassign doc

---

github/git_refs.go
github/git_refs_test.go
github/repos_contents.go

This (breaking) change alters the api of GetRef() to return a slice of
References instead of a single Reference, in order to account for the
fact that GH will return an array of references in the event that
there is not a precise match to the queried reference.
This is accomplished by passing a buffer to client.Do(), and making a
second attempt at unmarshalling in the event that the single-object
case fails.
Addresses issue #588

#588 Handle multiple References returned by the GH refs/ endpoint.

---

README.md
github/doc.go
github/github.go

Fixes #571.
Change-Id: Iefcc687d9fc56c40964d5e6f1cdbc54d020dae3c

Return rate limit information immediately after `checkRateLimitBeforeDo`

---

github/github-accessors.go
github/repos.go
github/repos_test.go

Add admin enforcement to protected branches API (#606)

---

README.md
github/doc.go

In [`RepositoryListByOrgOptions`](https://godoc.org/github.com/google/go-github/github#RepositoryListByOrgOptions) struct, [`ListOptions`](https://godoc.org/github.com/google/go-github/github#ListOptions) struct is an [embedded field](https://golang.org/ref/spec#Struct_types), so it's possible to dereference `Page` without explicitly going through `ListOptions`.
This is shorter, simpler and readable.

Simplify pagination example code.

---

github/authorizations.go
github/authorizations_test.go
github/gists.go
github/gists_test.go
github/github.go
github/pulls_reviewers.go
github/pulls_reviewers_test.go
github/pulls_reviews.go
github/pulls_reviews_test.go
github/repos_pages.go
github/repos_pages_test.go
github/users.go
github/users_test.go

This adds a ListOptions argument to ListReviews, so that pagination is
able to be supported. Without this it’s not possible to fetch the
2nd page of reviews, from what I can see.
Note that this does break the API, but I’ve added support for a nil
value in the argument, to minimise upgrade pain.

Add pagination option to PullRequests.ListReviews.

---

github/issues_labels.go
github/strings_test.go

The previous behavior was inconsistent, and not documented, so no one could actually rely on it. If custom printing behavior is needed, it should be done in a helper func or a wrapper type that implements desired printing behavior, and documents it.
There was agreement in #595 that this is the best thing to do.
Fixes #595.
/cc @yml FYI, since you might be relying on this behavior.

Change Label.String behavior to use Stringify like all others.

---

github/github.go
github/pulls_reviewers.go
github/pulls_reviewers_test.go
github/pulls_reviews.go
github/pulls_reviews_test.go

@shurcooL I have made changes for the media type for the entire pulls reviews. Can you please review this?

#638: Remove custom media type for Pull Request Reviews API

---

github/github-accessors.go
github/github.go
github/repos_community_health.go
github/repos_community_health_test.go

This is a new API released by GitHub and is currently available as a
preview only.
Link - https://developer.github.com/v3/repos/community/#retrieve-community-health-metrics
Fixes: #553

Add Community Health metrics endpoint

---

github/github-accessors.go
github/repos_commits.go
github/repos_commits_test.go

They are documented in the sample response at https://developer.github.com/v3/repos/commits/#compare-two-commits. I also confirmed the fields are present in a real GitHub API response:
<details>
```
GET https://api.github.com/repos/robpike/ivy/compare/dev...master
{
"url": "https://api.github.com/repos/robpike/ivy/compare/dev...master",
"html_url": "https://github.com/robpike/ivy/compare/dev...master",
"permalink_url": "https://github.com/robpike/ivy/compare/robpike:5bded9c...robpike:37dab08",
"diff_url": "https://github.com/robpike/ivy/compare/dev...master.diff",
"patch_url": "https://github.com/robpike/ivy/compare/dev...master.patch",
"base_commit": {
"sha": "5bded9c912dced5a0e13acaea6169c77608ac22e",
"commit": {
"author": {
"name": "Rob Pike",
"email": "r@golang.org",
"date": …
```

Add missing URL fields to CommitsComparison struct.

---

github/github-accessors.go
github/pulls.go

https://developer.github.com/v3/activity/events/types/#pullrequestevent documents a `merge_commit_sha` on the pull request webhook event.
Related to https://github.com/google/go-github/issues/521 and https://github.com/google/go-github/pull/338

Add Pull Request MergeCommitSHA

---

github/activity_events.go
github/event_types.go
github/github-accessors.go
github/messages.go
github/messages_test.go

The team event was announced in this post:
https://developer.github.com/changes/2016-11-29-user-management-webhooks/
The API documentation is at:
https://developer.github.com/v3/activity/events/types/#teamevent
The "Changes" object in the response is not illustrated in
the example payload, but it is documented in the table of fields.
Closes #652.

Add support for 'team' events

---

github/event_types.go

I made these strings by accident in #653. The documentation in
https://developer.github.com/v3/activity/events/types/#teamevent
clearly states that they're boolean.
My apologies for missing that the first time around 🌷

Fix type in team event fields

---

README.md
github/doc.go

As discussed in #627 I have a package which provides the GitHub Apps Authentication as an Installation `http.RoundTripper` that I use with this GitHub library successfully. I'm happy to keep maintaining it in an external repository, but a link from this library may assist others in finding the package.
Relates to #455.

Add link to GitHub Apps authentication package in docs.

---

github/github-accessors.go
github/repos.go
github/repos_test.go

Adds pull request reviews enforcement structures and API methods, adds admin enforcement API methods and removes old IncludeAdmins field from the request.

[Issue#617] Update Protected Branches API preview

---

github/users_gpg_keys.go

`golint` does not detect the proper comment form due to an empty line.

Fix minor linting issue

---

github/orgs.go
github/orgs_test.go
github/repos_test.go
github/users_test.go

This pull request adds the `GetByID` method to `OrganizationsService` in the same fashion as is done for `UsersService`  in #333 and `RepositoriesService` in #332.
I've not created a separate issue as this method was added in the same spirit as described in #329.

Add OrganizationService.GetByID method.

---

github/github.go

The current behavior of `newResponse` is that it expects non-nil `r`, and always returns non-nil `*github.Response`. This behavior is relied on by all callers of `newResponse`.
This change improves the documentation of `newResponse` to reflect that.
Closes #660.

Document that newResponse expects non-nil input.

---

github/repos_collaborators.go

This is a cherry-pick of a minor documentation improvement for `AddCollaborator` method from https://github.com/google/go-github/pull/580#issuecomment-299608384.
It's more explicit about what the method does. It is based on wording in GitHub API docs at https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator:
> To send an invitation to a collaborator rather than directly adding them,

Improve documentation of AddCollaborator method.

---

github/github-accessors.go
github/projects.go

Add fields that were missing in the ProjectCard struct.
Fixes #667.

Add missing fields to ProjectCard struct.

---

github/orgs_teams.go
github/orgs_teams_test.go
github/repos.go
github/repos_forks.go
github/repos_forks_test.go
github/repos_test.go

Add topics preview header to more RepositoriesService methods. 
Fixes https://github.com/google/go-github/issues/675

Add preview Topics support to more methods

---

github/github.go
github/pulls.go
github/pulls_test.go
github/repos.go
github/repos_test.go

delete custom media type 'application/vnd.github.polaris-preview' 

---

github/github.go
github/pulls_reviewers.go
github/pulls_reviewers_test.go

Adding preview support for team review requests. 
Fixes #678

Add Preview Support for Team Review Requests

---

README.md
github/doc.go

These were annoying me, and it's Friday, so no one can tell me these improvements are too small to bother with. =.=
This small PR features these changes:
- Use tabs to indent Go code, just like gofmt does.
- Remove unneeded backticks in code block in README.md.
Overall, the formatting consistency is improved.

doc: Fix formatting inconsistencies.

---

github/github.go
github/github_test.go

This pull request provides logic to return an error if there is no slash at the end of `BaseURL` or `UploadURL`.
Related comment:
https://github.com/google/go-github/pull/690#issuecomment-321879628

Add error for no trailing slash

---

example/appengine/app.go
example/appengine/app.yaml
github/github.go
github/repos_contents.go
github/repos_releases.go
github/with_appengine.go
github/without_appengine.go

Fix Google App Engine support and provide working example

---

github/projects.go

Fixes #696
Inconsistent documentation was found in file github/projects.go
Edited the doc line to match corresponding [Github docs](https://developer.github.com/v3/projects/cards/).

Removed Inconsistency in documentation for ProjectCardOptions(#696)

---

.gitignore
.travis.yml
README.md

based on instructions at
https://coveralls.zendesk.com/hc/en-us/articles/201342809-Go
Fixes #694
@shurcooL could you make sure this doesn't look like it'll interfere with the recent changes you made to the travis config?

add coveralls support to travis config

---

README.md
github/doc.go

The Search API has a separate rate limit. This is not mentioned in the README and could be misleading.
Link to the Github API docs: https://developer.github.com/v3/search/#rate-limit.

README: add rate limit info for search API

---

github/github.go
github/repos_collaborators.go
github/repos_collaborators_test.go

Fixes #647.
Let me know if there is anything that needs to be changed or can be improved. 
Thank you!

[#647] Add 'affiliation' to ListCollaborators.

---

github/authorizations.go
github/github-accessors.go
github/github.go
github/repos_deployments.go

This PR renames two fields as per discussion in #605:
`Authorizations.UpdateAt` => `UpdatedAt`
`DeploymentStatus.UpdatedAt` => `PushedAt`
As this is a breaking API change, would it be appropriate to merge these changes as a single version bump with #706, also a breaking change?

[#605] Use more appropriate field names

---

github/search.go
github/search_test.go

This PR addresses #707 by adding some example documentation on search queries and a unit test for what GitHub terms "search qualifiers", e.g., `"is:issue"`.

Document search api

---

github/timestamp_test.go

This PR adds test logic verifying that timestamp strings in the `"2006-01-02T15:04:05.000Z"`  format are converted properly into `Timestamps` by JSON unmarshalling.
Fixes #715.

(#715) Add test for anomalous timestamp format from Projects API.

---

github/timestamp_test.go

It's already declared and used elsewhere; no reason not to use it here.
This is a minor code simplification opportunity I spotted while reviewing #716. /cc @e-beach

Use referenceUnixTimeStr const in tests.

---

github/github.go
github/orgs_teams.go
github/orgs_teams_test.go

Re-submit of #718.
This PR address part of #714 by
1. Adding a parent field to the Team struct.
2. Requesting this field to be populated from each endpoint that returns a team, by adding the API preview header to the request.

Request parent team when endpoints return a team

---

.travis.yml

Go 1.9 is out by now, and it's different from `master`.

Travis: Add Go 1.9.x.

---

github/github-accessors.go
github/orgs_teams.go
github/orgs_teams_test.go

This replaces `Team` with `NewTeam` in function that accept a team for creating or editing a team.
The `NewTeam` struct is similar to the existing `NewPullRequest` for creating pull requests.
We need a new struct because the set of parameters for creating or editing a team contains some parameters that are not in the parameter for teams, and most properties of teams cannot be used for editing.
The specific change is that Teams are returned with a `parent` field, but are created/edited with a `parent_id` field.

Add parent team id param

---

github/github.go
github/orgs_members.go
github/orgs_members_test.go

The `/orgs/:org` GitHub API endpoint expects the string name of the organization, not its integer ID (that would be `/organizations/:id` endpoint, which we're generally not using).
Change the org parameter type from int to string to make it possible to specify the organization via its name.
This method wasn't functional before.
Fixes #730.

Change ListPendingOrgInvitations method to take string org name.

---

github/github-accessors.go
github/issues.go

Retrieve following data fields returned for Issues from GitHub API  (Fix #739) :
- repository_url;
- comments_url;
- events_url;
- labels_url.

Add missing URL`s data to Issue type

---

github/orgs_teams.go
github/orgs_teams_test.go
github/repos.go
github/repos_collaborators.go
github/repos_collaborators_test.go
github/repos_test.go

This adds the preview header to the rest of the endpoints mentioned in https://developer.github.com/changes/2017-08-30-preview-nested-teams/.
In summary, supporting the preview API required adding a parameter for `CreateTeam` and `EditTeam`, creating the `NewPullRequest` struct, and adding the preview header to every header involving a team (this PR).
This should finish up support for the API.

Add NestedTeamsPreview header to remaining endpoints

---

github/messages.go
github/messages_test.go

- Enable `ValidatePayload` to work for webhooks with Content-Type `application/x-www-form-urlencoded` in addition to `application/json`.
- Reject any Content-Type that is not `application/x-www-form-urlencoded` or `application/json`.

Accept application/x-www-form-urlencoded webhooks

---

github/projects.go
github/projects_test.go

State was missing, useful for updating projects per:
https://developer.github.com/v3/projects/#update-a-project
Adds the ability to `open`/`close` projects based on `ProjectOptions` with `ProjectUpdate`

Adds state to project options per github's docs

---

github/github-accessors.go
github/orgs_teams.go

Using the code as written in the `NestedTeamsPreview` branch produces an error when talking to the GitHub API:
```
panic: PATCH https://api.github.com/teams/2514825: 422 Invalid request.
For 'properties/parent_team_id', "2514824" is not a number or null. []
```
The [documentation](https://developer.github.com/v3/orgs/teams/#create-team) states that this parameter is an `id` type which--for the GitHub API--appears to mean an integer, not a string.

parent_team_id is an integer identifier, not a string

---

github/github.go
github/repos.go
github/repos_test.go

The standard pagination options have no effect in the `/repositories` endpoint, both empirically and according to the documentation: https://developer.github.com/v3/repos/#list-all-public-repositories
> Note: Pagination is powered exclusively by the since parameter. Use the Link header to get the URL for the next page of repositories.

remove ListOptions from RepositoryListAllOptions (they have no effect)

---

github/repos.go
github/repos_test.go

While working on terraform-providers/terraform-provider-github#50 I realized that this was missing.
GitHub.com support page about feature https://developer.github.com/v3/repos/branches/#update-branch-protection

Adds RequireCodeOwnerReviews to PullRequestReviewsEnforcement

---

github/github.go

The JSON encoder escapes[ > < and &](https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML).
This is problematic because Markdown uses > for quoting. This causes > to appear as a literal character when doing, say, CreateComment, as the JSON encoder escaped it to \u003e and the Markdown processor ignores it.
This PR stops the escaping, so the Markdown processor will correctly recognize the > and quote text rather than literal printing. This is almost always what is desired. In the case it's not, the callee can use json.HTMLEscape when passing the text to the go-github service.

Change JSON encoder to not escape HTML

---

github/orgs_teams.go

Documentation update of deprecated OrganizationsService.IsTeamMember method, as discussed in #717.

Updates docs to mark method as deprecated

---

github/apps.go
github/apps_installation.go
github/apps_installation_test.go
github/apps_test.go
github/github-accessors.go

This pull request provides the missing [apps](https://developer.github.com/v3/apps/) methods and tests.
Fixes #734.

Add missing apps methods

---

github/github.go
github/github_test.go

With this PR I have completed the following, addressing the issues discussed in #756:
- Introduced new func to create a new enterprise client
- Ensured base and upload urls are formatted with a trailing slash
- Added appropriate comment documentation
- Extended test cases to cover this new creation method
Did I cover everything? :)

NewEnterpriseClient method with custom urls

---

github/orgs_teams.go
github/orgs_teams_test.go

As per discussion in https://github.com/google/go-github/pull/747#issuecomment-336780818, this endpoint is missing.

NestedTeamsPreview: Add the ListChildTeams endpoint

---

github/pulls.go
github/pulls_test.go
github/repos_commits.go
github/repos_commits_test.go

Follows the same high-level pattern as set out in PR #481 with `PullRequestsService.GetRaw` method. (/cc @huydx FYI.)
Improve documentation wording.
Improve style of `PullRequestsService.GetRaw` and its tests to be more consistent.
Fix minor typo in GitHub documentation URL.

Add RepositoriesService.GetCommitRaw method.

---

github/pulls_reviewers.go

Use a pointer when execute the request.
```
error: json: Unmarshal(non-pointer github.ReviewersRequest)
```
I think the best way is to change method signature to use a pointer but it's breaking.
```go
func (s *PullRequestsService) RequestReviewers(ctx context.Context, owner, repo string, number int, reviewers *ReviewersRequest) (*PullRequest, *Response, error) {
```

fix: RemoveReviewers json unmarshall error

---

github/gen-accessors.go
github/github-accessors.go
github/github_test.go

Add support for automatically adding accessor methods for named structs
in github-accessors.go. Add a new flag to struct type Getter - NamedStruct
which is a flag to decide if this getter is for a named struct or not.
If it's a named struct, we make some changes in the way its
accessor method looks like finally in github-accessors.go.
Another thing to note here is that named structs are always going to end
up of type *ast.Ident from AST point of view so we don't need to check
for named structs for any other cases (like array/map/selector expression).
Fixes #587 
/cc @gmlewis

gen-accessors: add support for named structs

---

github/repos.go
github/repos_test.go

Based on GitHub documentation:
> Required. An array of topics to add to the repository. Pass one or more topics to replace the set of existing topics. Send an empty array ([]) to clear all topics from the repository.
https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository 
right now if passing an empty array, the Names attribute is omitted resulting in API validation error on GitHub side.

Removing omitifempty on topics.Names to be able to remove all topics

---

github/apps_marketplace.go
github/apps_marketplace_test.go
github/github-accessors.go
github/github.go

* Includes basic testing for Listing Plans and the Accounts linked to a Plan (including stubs)
**NOTE** This is currently awaiting scrutiny as it's my first contribution to the project. I would appreciate any feedback (good or bad) and the 👍  if it's ok to carry on with the rest of the implementation for #720

#720 Initial commit for listing Plans and Plan Accounts

---

github/activity_events.go
github/repos.go

Adds missing ",omitempty" to the field json schema of the pointer
fields.
Fixes: #786

Add missing omitempty to the field json schema

---

github/activity_events.go
github/event_types.go
github/github-accessors.go
github/messages.go
github/messages_test.go

Support MarketeplacePurchaseEvent

---

github/github.go
github/repos.go
github/repos_test.go

As announced here:
https://developer.github.com/changes/2017-11-09-repository-transfer-api-preview/
And detailed here:
https://developer.github.com/v3/repos/#transfer-a-repository
Fixes #777

Add support for the repository transfer API

---

github/repos_stats.go

fix a typo in file repos_repos
I think `thew eek` should be `the week`.

Update repos_stats.go: fix a typo in file repos_repos

---

github/github-accessors.go
github/pulls.go

I see that when a user contributes to a repo at his first time, the github will show this contributor is the-first-time-contributor. And I contact with developers in github about how to get this field in API.
And they said they design a new Field `AuthorAssociation` in pullrequest struct. Although this is not documented in github API docs.
I think it is important, so I try to add this field.

Add AuthorAssociation field in struct PullRequest

---

github/gen-accessors.go
github/github-accessors.go

Make gen-accessors.go skip certain struct and fields while creating
accessor methods for structs and fields. Basically, now we have two more
blacklists (blacklistStruct and blacklistField) respectively for
blacklisted structs and fields.
So, for every struct, it should first check and skip if the struct
is in blacklist.
Then, for every field, it should first check and skip if the struct
is in blacklist.
Fixes #778

 gen-accessors: skip Client struct and unexported fields

---

github/github.go

Avoid modifying the original request as per http.RoundTripper contract.
In UnauthenticatedRateLimitedTransport.RoundTrip, we need to modify the
URL of the request only, while in BasicAuthTransport.RoundTrip, we need
to modify only the headers.
Hence, we get rid of cloneRequest method which wasn't working good for
the needs of UnauthenticatedRateLimitedTransport.RoundTrip. Instead, now
we have the implementation of cloneRequest inline in both the RoundTrip
interfaces.
We decided to make the cloneRequest implementation inline because of its
use at only these two places and we think we won't gain much by making a
generic implementation of cloneRequest as a function. To follow the
discussion on this, check the GitHub issue - https://github.com/google/go-github/issues/556.
Fixes #556

RoundTrip: avoid modifying the original request

---

github/github-accessors.go
github/pulls.go

This isn't a well documented field but it's present in API responses and mentioned here 
https://github.com/octokit/octokit.rb/issues/626

Add PullRequest.MergeableState field

---

github/orgs_outside_collaborators.go
github/orgs_outside_collaborators_test.go

I have implemented the two methods on `OrganizationsService` corresponding to missing
endpoints of the Outside Collaborators API, namely:
1. [`RemoveOutsideCollaborator`](https://developer.github.com/v3/orgs/outside_collaborators/#remove-outside-collaborator)
2. [`ConvertMemberToOutsideCollaborator`](https://developer.github.com/v3/orgs/outside_collaborators/#convert-member-to-outside-collaborator)
This was my first attempt at wrapping endpoints so it is likely that the code can be improved upon.
Meanwhile, I will work on adding unit tests for these endpoints.
Refer #524

Add Outside Collaborators API for OrganizationsService

---

github/gists.go
github/gists_test.go
github/git_blobs.go
github/git_blobs_test.go
github/git_commits.go
github/git_commits_test.go
github/git_refs.go
github/git_refs_test.go
github/git_tags.go
github/git_tags_test.go
github/github-accessors.go
github/github.go
github/issues.go
github/issues_labels.go
github/issues_labels_test.go
github/issues_milestones.go
github/issues_milestones_test.go
github/issues_test.go
github/orgs.go
github/orgs_test.go
github/repos_deployments.go
github/repos_deployments_test.go

Helps #814 .
The current pull request includes the GraphQL node ID in the response for the following REST API v3 resources:
- Deployments
- Gists
- Git Blobs
- Git Commits
- Git References
- Git Tags
- Issues
- Labels
- Milestones
- Organizations

Support preview GraphQL API v4 Node IDs

---

github/gen-accessors.go

Hardcode 2017 as copyright year in github-accessors.go.

---

github/github.go
github/github_test.go

Seems like the URL changed, docs were not updated though:
https://developer.github.com/v3/#abuse-rate-limits
Will also send an email to github support to check wether this is intended or not.

fix: abuse rate limits handling

---

github/git_trees_test.go
github/github_test.go

Use testMethod to test the request method instead of manually comparing
it and testing. This change is to make things consistent through out the
code base.
Fixes #829

Make use of testMethod consistent

---

README.md
github/github.go

This does not yet address some of the additional workflows and policies we'll need to adopt as a result.  For example, when do we cut new releases, do we attempt to maintain a formal changelog, or at least release notes when we cut a new release, etc.  This also requires that we update go docs to call out which methods are exposing preview functionality from the GitHub API.
Fixes #376

readme: add section on versioning

---

github/pulls.go

to fix #854 
In pulls API, each pull-requests have a "labels" property
https://developer.github.com/v3/pulls/#response

Add "Labels" property for PullRequest

---

README.md
example/simple/main.go
github/doc.go

The modifications performed in this commit:
1.    A working code snippet has been added to the README
2.    The "examples" folder has been explicitly hyperlinked
Resolves #809

Added examples to the README

---

github/github-accessors.go
github/projects.go
github/projects_test.go
github/reactions.go
github/reactions_test.go
github/repos_projects.go
github/repos_projects_test.go
github/repos_releases.go
github/repos_releases_test.go

Helps #814 .
The current pull request includes the GraphQL node ID in the response for the following REST API v3 resources:
* Projects
* Reactions
* Releases

Added node id to other API's

---

github/github.go
github/pulls_reviewers.go
github/pulls_reviewers_test.go

As the Team Review Requests API is fully supported by GitHub API v3, we
have removed the preview(custom) media type: `thor-preview`.
Fixes #835 
-------------
1. How should we proceed here given that some GitHub enterprise versions may not yet support the Team Review Requests API?
2. According to the new versioning guideline, under which category should be removing preview functionality in favor of GitHub API support fall?
Ping @willnorris @gmlewis @sahildua2305

Remove preview media type for Team Review Requests

---

github/github-accessors.go
github/github.go
github/orgs_members.go
github/orgs_members_test.go
github/orgs_teams.go

New endpoints:
- [Create organization invitation](https://developer.github.com/v3/orgs/members/#create-organization-invitation)
- [List organization invitation teams](https://developer.github.com/v3/orgs/members/#list-organization-invitation-teams)
Changes to existing endpoints:
- [List pending organization invitations](https://developer.github.com/v3/orgs/members/#list-pending-organization-invitations) has two new fields. `team_count` and `invitation_teams_url`.
Detailed here:
- https://developer.github.com/changes/2018-01-25-organization-invitation-api-preview/
Fixes #838

Support preview Organization Invitation API

---

github/apps_installation.go
github/apps_test.go
github/github-accessors.go

Implements https://github.com/google/go-github/issues/851
An InstallationID is different from an AppID. This PR adds an additional field
so that we can query the GitHub application ID given its installation ID.
The `app_id` field is returned during installation and creation events.
It is also returned in the https://developer.github.com/v3/apps/#get-a-single-installation endpoint.

Add app_id to the Installation struct

---

github/github.go

The behavior on connection reuse is introduced in golang/go@18072ad.
Fixes #843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/go-github/847)

Remove unnecessary draining the `resp.Body`

---

github/apps.go
github/apps_installation.go
github/apps_test.go
github/github-accessors.go

This is the companion PR for adding the remaining fields of the `app` response. 
context: https://github.com/google/go-github/issues/851
This PR adds the remaining fields for the `app` endpoints, specifically adding support for 
`target`
`target_type`
`repository_selection`
`single_file_name`
`permissions`
`events`
* I've added unit tests for `target`(s) field for all the tests
* Added a more detailed response test for `ListInstallations` only (would like feedback if I can follow the same pattern for the remaining tests).
/cc @kshitij10496 @gmlewis

Add remaining `app` fields

---

github/event_types.go

This PR adds the ability to read labels from 'labeled' pull request events. This isn't present in any other event, hence the comment.

Add the ability to read a label from labeled events

---

github/event_types.go
github/github-accessors.go

PR #867 added a Label field to the PullRequestEvent, but I forgot to add the corresponding accessor. This fixes this oversight.

Add a GetLabel() accessor for the PullRequestLabel

---

.travis.yml
github/github-accessors.go

Add Go 1.10.x to .travis.yml. Add quotes to be consistent with the recommended style at https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use.
Regenerate the package with:
go generate github.com/google/go-github/...
That fixes the build.
Updates #868.

Travis: Add Go 1.10.x and fix build.

---

README.md
github/doc.go
github/with_appengine.go

Google App Engine now supports Go 1.8 (up from 1.6). (They even support 1.9 beta as of today! 🎉) The `context` package in Go standard library was added in 1.7. That means we no longer have to suggest rewriting the import path. 🔥
Reference: https://cloud.google.com/appengine/docs/standard/go/release-notes#october_25_2018.
Fixes #859.
---
Note: I am not an App Engine user or expert, so it's best if this can be reviewed by someone who is. I made this PR using the information shared in #859.

Remove App Engine note about rewriting context import path.

---

github/repos_releases.go
github/repos_releases_test.go

As I commented at https://github.com/google/go-github/issues/870#issuecomment-375071816, a downloaded binary file with `DownloadReleaseAsset()` is broken due to the additional accept header. I'm facing this problem on [go-github-selfupdate](https://github.com/rhysd/go-github-selfupdate) library.
https://travis-ci.org/rhysd/go-github-selfupdate/jobs/356272200#L218
I confirmed that this fix solved the problem on my local machine (macOS 10.12, Go 1.10).
Fixes #870.

Remove mediaTypeGraphQLNodeIDPreview accept header from DownloadReleaseAsset.

---

github/github-accessors.go
github/repos.go
github/repos_test.go
test/integration/repos_test.go

The 'dismissal_restrictions' key in the 'required_pull_request_reviews' object must either be omitted (for the case of personal repositories), an empty JSON object, or a JSON object with exactly two keys 'users' and 'teams'. See https://developer.github.com/v3/repos/branches/#update-branch-protection. Closes #664

Bug fix PUT /repos/:owner/:repo/branches/:branch/protection

---

github/issues_comments.go
github/orgs_hooks.go
github/repos_keys.go

I think the OrganizationsService didn't get converted in the int -> int64 id migration.
Updates #597.

Replace `int` id with `int64` in OrganizationsService

---

github/issues_comments.go

Also document which `IssueComment` fields need to be set in `EditComment` method.
This should help improve clarity of the API, and reduce the chance to mix up the issue vs comment IDs.
Resolves #885.

Rename id parameter to commentID in IssuesService comment methods.

---

github/pulls_comments.go

**This is a breaking API change that is a part of issue #597.** It should've been applied earlier, but we missed it because the parameter was misleadingly named `number` rather than `id` or `commentID`.
Rename the parameter to `commentID` to make it more clear that it's the comment ID and not the PR ID nor PR number. This should help improve clarity of the API, and reduce the chance to mix up the IDs.
Also document which `PullRequestComment` fields need to be set in `EditComment` method.
Similar to #886.
Updates #885.
Updates #597.

Change number int to commentID int64 in PRsService comment methods.

---

github/github.go
github/repos_forks.go
github/repos_forks_test.go

Per the docs
(https://developer.github.com/v3/repos/forks/#create-a-fork), there is
still a useful body, and it is helpful for automatic fork creation to
get that response.
I'm not sure if this approach is okay. An alternate is to do the decoding inside Do, so this works for the ~dozen other places that might get an AcceptedError, but I didn't want to go check the docs for every single case to see whether the response body is meant to have useful data.

In CreateFork, return the repo info when 202 Accepted occurs.

---

github/git_blobs.go
github/git_blobs_test.go

This addresses #658.
The name isn't great (I would have preferred `GetRawBlob`), but it matches the previously added `RepositoriesService.GetCommitRaw`. Happy to switch if you'd prefer the better name and don't mind the mild inconsistency.

Add GitService.GetBlobRaw.

---

github/github-accessors.go
github/issues_comments.go
github/pulls_comments.go

It's undocumented in the v3 API, but is present in the v4 API, and is
indeed returned in v3 API requests.

Add the AuthorAssociation field to IssueComment and PullRequestComment.

---

github/examples_test.go

This PR provides an example on how to use `client.Repositories.CreateFile` to push a new file to a repository.

Add an example of using the contents API to push a file

---

github/orgs.go
github/orgs_test.go

Change org ID in OrganizationsListOptions to be consistent with the [org id type](https://github.com/google/go-github/blob/master/github/orgs.go#L23)

change org id to int64 in OrganizationsListOptions

---

github/github-accessors.go
github/pulls_comments.go
github/pulls_comments_test.go

Closes: #897
This PR adds the  'pull_request_review_id' field to PullRequestComment as requested in #897

Add pull_request_review_id field to PullRequestComment (Fixes #897)

---

github/github-accessors.go
github/github.go
github/teams.go
github/teams_discussion_comments.go
github/teams_discussion_comments_test.go
github/teams_discussions.go
github/teams_discussions_test.go

- Add a new service TeamsService to support API related to Organization Teams https://developer.github.com/v3/teams/
- Add methods to support new preview API for team discussions https://developer.github.com/v3/teams/discussions/
- Add methods to support new preview API for team discussion comments https://developer.github.com/v3/teams/discussion_comments/
Fixes #849 
https://developer.github.com/changes/2018-02-07-team-discussions-api/#new-rest-api-endpoints
Second part of the change https://developer.github.com/changes/2018-02-07-team-discussions-api/#updates-to-the-teams-api-documentation will be done in a separate PR, once this PR is merged.

Support preview Team Discussions API

---

github/orgs.go
github/users.go

This PR adds the following note:
- Pagination is powered exclusively by the Since parameter,
- ListOptions.Page has no effect.
- ListOptions.PerPage controls an undocumented GitHub API parameter.
Fix bug #900

Documentation update for 'OrganizationsListOptions' and 'UserListOptions' (#900)

---

README.md

Follows https://github.com/shurcooL/githubv4/commit/19298c78142b5fe80c2cdaa2091bc51cbc3a94fc.
Updates shurcooL/githubv4#35.

README: Update for githubql package rename.

---

github/pulls_reviews.go

In a few instances the pull request number was accidentally promoted from an int to an int64.

Revert pull request number from int64 to int

---

github/admin_stats.go

It's just for consistency with the other comments in the code.

typo missing space

---

github/repos.go

...for team IDs.
I didn't change the variable name to keep consistent with the [create org invitation options](https://github.com/google/go-github/blob/74e913d8de3209e490c76b099d574e033bdcf717/github/orgs_members.go#L318).
Fixes #946

Update the transfer repository request to use the correct json name

---

github/github.go
github/licenses.go
github/licenses_test.go
github/repos.go
github/repos_test.go

Fixes [#813](https://github.com/google/go-github/issues/813) by removing custom media type for licenses.

Remove custom media type for license api (#813)

---

github/github-accessors.go
github/pulls_comments.go

Fixes #948.
The JSON tag mismatches the one returned from the API, so the value is always encoded as nil.
Relevant docs: https://developer.github.com/v3/pulls/comments/#get-a-single-comment
Also have to use an alias since the JSON tag is different between getting a comment and creating a comment.
I'd be keen to see if there's a more elegant way to do this.

Fix InReplyToID JSON tag for PullRequestComment

---

github/repos_commits.go

I always try finding the right go-github method by searching the url of a compatible GitHub API Document URL. When I searched `https://developer.github.com/v3/repos/commits/#compare-two-commits`, I found the same URL is specified as `https://developer.github.com/v3/repos/commits/index.html#compare-two-commits` in go-github GoDoc.
I personally think the former one would be better than later one since the url people normally encounter on GitHub API Document is the former one. So I changed it! Thanks! 👍

Remove unnecessary index.html from a #compare-two-commits url

---

github/misc_test.go
github/repos_contents_test.go

currently builds of the package with go1.11 fail due to using `%q` qualifier with `*string` type in github/repos_contents_test.go:
```
$ go1.11beta2 tool vet .
github/repos_contents_test.go:59: T.Errorf format %q has arg tt.encoding of wrong type *string
github/repos_contents_test.go:62: T.Errorf format %q has arg tt.encoding of wrong type *string
```
In Travis, a number of PR builds fail with `Go:master` ("Allowed failures"), ex. https://travis-ci.org/google/go-github/builds/406237120
PR fixes the issue by treating the cases where tt.enconding and tt.content are nil or not nil separately and adding extra varaibles (`encoding` and `content`) for printing in error messages.  It also adds a workaround for gofmt difference between go1.10 and go1.11  (as in …

fix go vet error with go1.11

---

github/timestamp.go

Found by go-critic linter.
Log:
```
check-package: $GOPATH/src/github.com/google/go-github/github/timestamp.go:31:3: underef: could simplify (*t).Time to t.Time
check-package: $GOPATH/src/github.com/google/go-github/github/timestamp.go:33:3: underef: could simplify (*t).Time to t.Time
```
If next suggestions are important too, I can make another PR(or extend current).
```
check-package: $GOPATH/src/github.com/google/go-github/github/activity_notifications_test.go:37:34: namedConst: use time.January instead of 1
check-package: $GOPATH/src/github.com/google/go-github/github/activity_notifications_test.go:38:34: namedConst: use time.March instead of 3
check-package: $GOPATH/src/github.com/google/go-github/github/activity_notifications_test.go:83:88: namedConst: use time.January instead of 1 …
```

Remove redundant dereference of time.Time

---

github/git_trees.go
github/git_trees_test.go
github/github-accessors.go

Makes it so that the "Truncated" field provided by the response
to the GetTree call is properly populated.
Fixes #922

Add Truncated field to Tree

---

github/github-accessors.go
github/github.go
github/repos_prereceive_hooks.go
github/repos_prereceive_hooks_test.go

Add APIs for pre-receive hooks

---

github/apps.go
github/apps_test.go
github/github-accessors.go

According to https://developer.github.com/v3/activity/events/types/#installationevent the `created_at` and `updated_at` timestamps in the event payloads are unix-formatted, while the CRUD APIs use RFC3339. Using `*Timestamp` handles the unfortunate fact that the API is inconsistent. Without this change, my application emits the following error
```
failed to unmarshal PullRequestEvent: parsing time "1533435666" as ""2006-01-02T15:04:05Z07:00"": cannot parse "1533435666" as """
```
I understand this might be a breaking change to the public API, so I'm open to feedback if there are alternative ways to proceed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/go-github/965)

Installation: Use *Timestamp instead of *time.Time for the benefit of InstallationEvent

---

github/github-accessors.go
github/orgs_projects_test.go
github/projects.go
github/projects_test.go
github/repos_projects_test.go

The original motivation was to add Project's `HtmlURL` field as we need it in https://github.com/terraform-providers/terraform-provider-github/pull/111
but I took some time to look at all missing fields in both Project & ProjectColumn, just for completeness.
The PR covers only one, small part of https://github.com/google/go-github/issues/884 - there is still more work to do before #884 can actually be closed - specifically around Project Collaborators and Team Projects.

projects: Add missing fields to struct

---

github/apps.go
github/apps_test.go

With a GitHub App that I'm building, I am only ever persisting IDs rather than `owner` and `name` for repositories. For the most part I am using the GraphQL API, but I need to create an installation access token, which I'm using `go-github` for.
This change adds a `FindRepositoryInstallationByID` endpoint which mirrors how `RepositoryService#GetByID` works.

Add FindRepositoryInstallationByID to AppsService

---

.travis.yml
README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/simple/main.go
github/examples_test.go
github/projects_test.go
go.mod
go.sum
test/fields/fields.go

This PR is generated by a [tool I wrote](https://github.com/marwan-at-work/mod) that helps migrate Go packages that are tagged +2 to Semantic Import Versioning. 
Note that this change should be backwards compatible and can still be imported without the `/vX` suffix when Go Modules is off.

Introduce go modules

---

github/checks.go
github/checks_test.go

Previously, `RequestCheckSuite` appended the contents of the `ops RequestCheckSuiteOptions` parameter as query string parameters, resulting in requests like `https://api.github.com/repos/$owner/$repo/check-suite-requests?HeadSHA=$sha`. These sorts of requests result in `422 Invalid request` errors from the GitHub API.
This PR passes the contents of the `ops RequestCheckSuiteOptions` parameter through to `(c *Client) NewRequest` as the body instead, resulting in requests that GitHub's API accepts.

Fix RequestCheckSuite

---

github/issues.go
github/issues_test.go

https://developer.github.com/v3/issues/#list-issues-for-a-repository
lists
- application/vnd.github.symmetra-preview+json
- application/vnd.github.squirrel-girl-preview
- application/vnd.github.machine-man-preview
which map to
- mediaTypeLabelDescriptionSearchPreview
- mediaTypeReactionsPreview
- mediaTypeIntegrationPreview

Fixes wrong Accept media type that was causing a 500

---

github/checks.go
github/checks_test.go
github/github-accessors.go

This PR updates `CheckService` and `CheckSuiteAnnotation` to account for the [recent changes to the GitHub API](https://developer.github.com/changes/2018-08-16-changes-to-the-checks-rest-api/):
* `filename` is being renamed to `path`
* `blob_href` is no longer necessary (no changes required, as responses continue to provide this value)
* `warning_level` is being renamed to `annotation_level`
* `POST /repos/:owner/:repo/check-suite-requests` is being removed
* `POST /repos/:owner/:repo/check-suites/:check_suite_id/rerequest` is being added
Fixes https://github.com/google/go-github/issues/980

Support changes to the Checks REST API

---

github/github.go

Explicitly specify the Rate type so Rate's String() receiver doesn't propagate to Response.
(Otherwise, `fmt.Printf("%+v", resp)` will just output the embedded Rate instead of the whole Response.)

Fix printing for Response instances.

---

github/messages.go

In an AWS Lambda invoked via API Gateway, I do not have direct access to the original `*http.Request`, but instead will typically have a signature of:
`func Handler(ctx context.Context, request events.APIGatewayProxyRequest) (Response, error) {`
The `events.APIGatewayProxyRequest` contains the original body as well as headers, and I would like to be able to invoke `ValidateSignature` directly.

Make ValidateSignature public when the original request is unavailable

---

github/activity_star.go
github/activity_star_test.go

Fixes https://github.com/google/go-github/issues/984
Changes:
- Add [`mediaTypeTopicsPreview` (`application/vnd.github.mercy-preview+json`)](https://github.com/google/go-github/blob/master/github/github.go#L94) HTTP header to [`ActivityService.ListStarred`](https://github.com/google/go-github/blob/master/github/activity_star.go#L70) to allow retrieving topics for starred repositories

Add Topics API preview to starred repos

---

github/github-accessors.go
github/pulls.go
github/pulls_test.go

closes #1001 
Hello and Welcome to my **first** pull request to a big open-source project.
In reference to #1001, I needed to add `"_links"` *object* to [`PullRequest` *structure*](https://godoc.org/github.com/google/go-github/github#PullRequest).
`_links` object preview from [Github API documentation](https://developer.github.com/v3/pulls/#response-1):
```json
"_links": {
"self": {
"href": "https://api.github.com/repos/octocat/Hello-World/pulls/1347"
},
"html": {
"href": "https://github.com/octocat/Hello-World/pull/1347"
},
"issue": {
"href": "https://api.github.com/repos/octocat/Hello-World/issues/1347"
},
"comments": {
"href": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments"
},
"review_comments": {
"href": …
```

Add links to pull request struct

---

github/github-accessors.go
github/orgs.go

related: https://github.com/google/go-github/pull/996
unfortunately i only added the field that matches `default_repository_settings` which is used to GET the org info. according to the docs (https://developer.github.com/v3/orgs/#get-an-organization):
* `default_repository_settings` is used for getting info about the org, using `Get`
* `default_repository_permission` is used to set the value on the org, using `Edit`
ive named the field `GetDefaultRepoPermissionXyz`, using the `Get` and `Edit` suffix to define the field, and using the correct json deserialization in each instance.

add other missing org field

---

github/examples_test.go

Adds a comment explaining what these examples are used for. This is to clarify how they differ from example/ and test/

Add comment explaining use of examples_test.go

---

github/github.go
github/repos_forks.go
github/repos_stats_test.go

Fixes #1022 
`AcceptedError` had a change in behavior in https://github.com/google/go-github/commit/88eb4e9dc91cb2db1bbc56c936f1ee39bbe72ba5
This change adds a `Raw` field to `AcceptedError`s. This allows for per API handling of the accepted error.

fixes AcceptedError unmarshaling

---

github/pulls.go

`requested_teams` was added to the `pull_request` object in the `review_requested` event, see [payload example](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-25) for definition.

add requested_teams to PullRequest

---

github/apps.go
github/apps_test.go

This PR updates the URL used for CreateInstallationToken to the new one. Closes #981.

Update CreateInstallationToken url

---

github/users.go

The `func (s *UsersService) Get` methods supports both calls: Getting a single user with name or getting the authenticated when you pass an empty string. The GitHub API docs for https://developer.github.com/v3/users/#get-the-authenticated-user were missing here.
During developing a tool with this client lib, i often go to the GitHub-API to check the correct API method. After this i get the URL and search in the godoc after the part of the `#`. In this case `get-the-authenticated-user`. With this workflow i reach quite fast the related go client lib method.
I was not able to find the `get-the-authenticated-user` method. Here we go.

Godoc: Add GitHub API doc link for "Get the authenticated user"

---

github/pulls.go

According to [docs](https://developer.github.com/v3/pulls/#parameters):
> Either open, closed, or all to filter by state. Default: open

Add "all" as possible value for PullRequestListOptions.State

---

github/github-accessors.go
github/github.go
github/repos_deployments.go
github/repos_deployments_test.go

Fixes #1035 
Changes:
- Add custom media type(`application/vnd.github.flash-preview+json`)
- Add `environment` parameter to `DeploymentStatusRequest` struct

Support expand Deployment Statuses API

---

github/github-accessors.go
github/github.go
github/repos.go
github/repos_test.go

Added support for the preview required commit signatures for Protected Branches API.
https://developer.github.com/changes/2018-02-22-protected-branches-required-signatures/
This solves: https://github.com/google/go-github/issues/902

Required signatures on protected branches

---

github/projects.go

According to the [API doc](https://developer.github.com/v3/projects/cards/#parameters-1), PullRequest is also an acceptable value for ContentType.

Add 'PullRequest' as possible value for ProjectCardOptions.ContentType

---

github/apps_marketplace.go
github/apps_marketplace_test.go
github/event_types.go
github/github-accessors.go

Adds support for pending changes to Marketplace plans which were added to the API. (discussed here https://developer.github.com/changes/2018-10-31-improved-experience-for-marketplace-pending-changes/) and referenced here #1040.

Support updates to Marketplace APIs and webhook payload

---

github/event.go
github/event_types.go
github/github-accessors.go

Fixes #959 by adding support new webhook event, `github_app_authorization`.

Support GitHub app authorization

---

github/github-accessors.go
github/projects.go

Fixes https://github.com/google/go-github/issues/1071.
Add 4 fields to `ProjectCard` struct.

Add fields to ProjectCard struct

---

github/repos.go
github/repos_test.go

https://developer.github.com/v3/repos/ does not mention any of the List repositories apis supporting  `application/vnd.github.scarlet-witch-preview+json`
And https://developer.github.com/v3/codes_of_conduct/ only mentions it for getting a repo, not listing.
Fixes https://github.com/google/go-github/issues/930

list user repos, list repos by org does not support the code of conduct preview

---

github/github-accessors.go
github/github.go
github/interactions.go
github/interactions_repos.go
github/interactions_repos_test.go

Created files based on the `{service}_{api}.go` format i.e `interactions_repos.go`.
API response for repository interactions and organisation interactions is same so I've abstracted the `Interaction` struct in `interactions.go`.
This PR adds the API's to `GetRestrictions`, `UpdateRestrictions` and `RemoveRestrictions` for a given repository.

Adding the new Interactions API support for repositories

---

github/doc.go

copy import paths from top-level README.md - to have the versioned import path
to show on https://godoc.org/github.com/google/go-github/github

doc.go - include versioned import path

---

github/checks.go
github/git_refs.go
github/repos_commits.go
github/repos_statuses.go

If `Repositories.GetCommitSHA1` was called with the branch name which includes non-alphabet character, it occurs an error. It looks to require escaping with percent encoding.
Below is sample code: 
```go
package main
import (
"context"
"fmt"
"github.com/google/go-github/github"
)
func main() {
client := github.NewClient(nil)
sha1, _, err := client.Repositories.GetCommitSHA1(ctx, "bgpat", "test", "cpu100%", "")
if err != nil {
panic(err)
}
fmt.Println(sha1)
}
```
before: `parse repos/bgpat/test/commits/cpu100%: invalid URL escape "%"`
after: `46736bd30fe65160f7d21e49d8f23e4687abc41b`

Escape commit ref with percent encoding

---

github/github.go
github/repos_releases.go
github/repos_releases_test.go

Update UploadOptions with a MediaType field. If the MediaType is
provided to UploadReleaseAsset it will take precedence over the type
retrieved from looking at the file extension. The complete order of
precedence is:
- MediaType in UploadOptions
- media type from file extension
- default media type, application/octet-stream
Update unit tests to test the order of precedence, default value and
that the Content-Type header is actually set in the upload request.

Allow media type to be specified in release asset upload

---

github/github-accessors.go
github/repos_contents.go

When getting file contents and the file is a symlink that points to anything other than a normal file (for example, a directory), the target field is used to indicate this.
This PR adds the Target field and accessor.
Fixes #1106

Add Target field to RepositoryContent

---

github/repos_hooks.go
github/repos_hooks_test.go

Issue: https://github.com/google/go-github/issues/1109
According to this [post](https://developer.github.com/changes/2019-01-29-life-after-github-services/), there will be 3 endpoints affected which will be deprecated: Edit a Hook, Test a Hook, and Ping a Hook. This PR removes the code regarding those 3 endpoints and also from the test file.
cc: @gmlewis

Removing 3 service hooks endpoints from the code and the test

---

github/github-accessors.go
github/pulls.go

According to the [GitHub docs](https://developer.github.com/v3/pulls/#get-a-single-pull-request), this field is only returned when
retrieving a single pull request by id, not when listing pull requests.
This commit does not include a test as it seems that most
fields and auto-generated accessors are not being tested.

Add missing PullRequest.ReviewComments field

---

github/github-accessors.go
github/users_administration.go
github/users_administration_test.go

GitHub updated the [suspend a user endpoint](https://developer.github.com/enterprise/v3/enterprise-admin/users/#suspend-a-user) to allow you to send a JSON payload containing the reason that the specified user is being suspended. If you input `""` for the reason, GitHub will default the reason to `Suspended via API by SITE_ADMINISTRATOR` in the audit log.

add UserSuspendOptions for user.Suspend

---

github/github-accessors.go
github/github.go
github/pulls.go
github/pulls_test.go

Fixes: #1120 
* Adding new media type (`application/vnd.github.shadow-cat-preview+json`) must be added to `github.go`,
* Adding the type to the header of listPRs and get single PR endpoint call,
* Adding new Draft boolean field to the [`PullRequest`](https://godoc.org/github.com/google/go-github/github#PullRequest) struct.

Support draft pull requests api public beta

---

github/git_commits.go
github/git_commits_test.go

Closes #1123 
This adds the `signature` field for GPG signing of commits.

Add signature field to commit creation

---

github/repos_commits_test.go

Fixes https://github.com/google/go-github/issues/1101
Added test case for `Repositories.GetCommitSHA1`, when it was called with the branch name which includes the non-alphabet character.

Added test case for commit ref with percent encoding

---

github/repos_hooks.go
github/repos_hooks_test.go

Attempting to create webhooks fail unless a name is specified. As per the documentation the only name that is valid is "web", so I haven't opted to allow modification of this but creation seems to fail without it.

Fix Webhook creation.

---

github/search.go
github/search_test.go

Fixes #1122.
- Quit replacing white space with "+"
- Use url.QueryEscape instead of url.PathEscape to escape query string

Use url.QueryEscape instead of url.PathEscape to escape query string

---

github/orgs_hooks.go
github/orgs_hooks_test.go

Hello! This is fixing exactly what #1117 fixed but for org hooks too. The discussion on that PR implies that this only affects GitHub Enterprise but I've been experiencing issues with this in plain ol' GitHub. I suspect this has something to do with this deprecation timeline taking effect at the end of January: https://developer.github.com/v3/guides/replacing-github-services/#deprecation-timeline

Fix org webhook creation

---

github/checks.go
github/event_types.go
github/github-accessors.go

Connects https://github.com/google/go-github/issues/1131
The `check_suite` object from github's check_suite event also includes `head_commit`, which is not present in the `check_suite` object.
The `CheckSuiteEvent` also uses `CheckSuite` as one of its fields in the struct which does not has the head_commit, and therefore is not parsed during json parsing in the current `CheckSuiteEvent`, hence `head_commit` data is unavailable from the `CheckSuiteEvent` struct.
~To also parse the `head_commit`, `CheckSuiteEvent` should use an embeded field for `CheckSuite` with `HeadCommit`, so that all the details are received from the github api.~
To also parse the `head_commit`, 
add the missing field `HeadCommit` in the `CheckSuite` struct with a comment stating that the field is only populated by a …

Use embeded CheckSuite and HeadCommit field for CheckSuiteEvent

---

github/github-accessors.go
github/pulls.go
github/pulls_test.go

Resolves https://github.com/davidji99/go-github/issues/1
Per https://developer.github.com/changes/2019-02-14-draft-pull-requests/, the `draft` parameter is now available for Github APIv3:
> [Updated 03-22-19] You can also create draft pull requests using a new draft field in the Create a pull request endpoint.

Add draft field to NewPullRequest

---

github/apps_marketplace.go
github/github-accessors.go

The id of a MarketplacePlanAccount represents a GitHub Account (user or organization) on a specific plan. After reaching out to GitHub Support, they recently added the "node_id" field to this object. The node_id facilitates transition to the V4 API.

Add NodeID to MarketplacePlanAccount

---

go.mod
go.sum
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

It removed github.com/google/go-github v17.0.0+incompatible dependencies
in go.mod.

Use go module in test directory

---

github/event_types.go

Just fixing minor godoc typos -- the checks API uses "rerequested" (no dash) rather than "re-requested", per GitHub API docs:
* https://developer.github.com/v3/activity/events/types/#checksuiteevent
* https://developer.github.com/v3/activity/events/types/#checkrunevent
Also confirmed via actual interactions with the GitHub API; when a check suite or check run is rerequested, no dash was present in the action string of the events received.
Thanks!

CheckSuiteEvent and CheckRunEvent: fix doc typos

---

github/event_types.go
github/github-accessors.go

Adds `RequestedTeam` to the `PullRequestEvent` event type.
In the event that a Team is requested for a review instead of a User, it will replace the `requested_reviewer` in the JSON payload with `requested_team`.
This allows for reusing similar logic employed when consuming `RequestedReviewer` without having to iterate through `PullRequest.RequestedTeams` which could potentially cause duplication events without additional logic.
Tested with Github Enterprise 2.15.9.

Add RequestedTeam to PullRequestEvent

---

github/teams.go
github/teams_test.go

Add a method to call the following endpoint
https://developer.github.com/v3/teams/#get-team-by-name

Add GetTeamBySlug methods in teamsService

---

github/apps.go
github/github-accessors.go

This is a similar issue to #965 - the `created_at` and `updated_at` fields in the `app` field of webhooks are formatted as Unix epoch integers, rather than RFC3339 for the CRUD APIs.

github.App: Use *Timestamp instead of *time.Time

---

github/github.go
github/repos.go
github/repos_test.go

Adding automated-security-fixes endpoint
fixes: https://github.com/google/go-github/issues/1184

add automated-security-fixes endpoint

---

github/checks_test.go
github/github_test.go

Tests for resource marshalling and unmarshalling

---

github/admin_stats_test.go

`admin_stats.go` had the worst test coverage at 18.75%.

Coverage: admin_stats.go

---

github/issues_timeline.go

Reverts google/go-github#511
The fields had been added in another PR.

Revert "(#510) Adds Type (*string) and Issue (*Issue) fields to timeline Source struct"

---

github/activity_test.go

`activity.go` had the worst test coverage at 55%.

Coverage: activity.go

---

github/repos_traffic_test.go

`repos_traffic.go` had the next worst test coverage.
Note that I found a number of copy/paste typos and inconsistencies in this file compared to the rest of the repo, so I fixed them.
Note that I also found a bug in `addOptions` which is the entire point of doing coverage testing. :joy:
I'll file an issue.

Coverage: repos_traffic.go

---

github/pulls_reviewers_test.go

`pulls_reviewers.go` had the next worst test coverage.

Coverage: pulls_reviewers.go

---

github/repos_test.go

`repos.go` had the next worst test coverage in terms of total lines.
This PR increases the coverage for this file.

Coverage: repos.go

---

github/github-accessors.go
github/users_emails.go

Because `UserEmail.Visibility` field is missed.
https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user

Add Visibility to UserEmail

---

github/github-accessors.go
github/github.go
github/teams.go
github/teams_test.go

Added Support preview Team Sync API for GitHub Enterprise Cloud users

---

github/admin_orgs.go
github/admin_orgs_test.go
github/admin_stats.go
github/admin_users.go
github/admin_users_test.go

Hello,
This PR adds methods for Github Enterprise endpoints.
The following are covered:
- Create organization
- Create User
- Delete User
I will be happy to add a few fix on this PR if necessary.

Add methods for GHE endpoints

---

github/gists.go
github/gists_test.go

Added test cases to increase coverage

addOptions to list gists forks endpoint

---

github/activity_test.go
github/git_commits_test.go
github/pulls_reviewers_test.go
github/repos_test.go
github/repos_traffic_test.go

- Ignore ineffectual assignments
- Check for error when reading keyring

Fix ineffectual assignments and error handling in tests

---

github/github.go

Instead of manually subtracting the timestamps, we can just use time.Until.

Use time.Until

---

github/projects.go

https://developer.github.com/v3/projects/cards/#get-a-project-card
correct argument name because this api  accepts `card_id`, not `column_id`
```
GET /projects/columns/cards/:card_id
```

fix GetProjectCard Argument

---

github/github-accessors.go
github/github-stringify_test.go
github/pulls.go

Fix: https://github.com/google/go-github/issues/1264
Also added another missing field which is the `locked`
/cc @gmlewis

add missing fields to PullRequest: locked and rebaseable

---

.travis.yml
go.mod

Add support for go1.13 and bump Travis CI tests from 1.11 to 1.12 and 1.13.

Support go1.13

---

github/checks.go
github/checks_test.go
github/github-accessors.go

According to https://developer.github.com/v3/checks/runs/#annotations-object `start_column` and `end_column` are part of the Annotation
Additionally I noticed `blob_href` is no longer listed on the docs. Should I remove it in this PR or raise another?  
https://github.com/google/go-github/pull/1241/files#diff-065d35fd95f6db43a7395a47966b9505R54

fix: add start and end column to Annotation

---

github/checks.go
github/checks_test.go
github/github-accessors.go

BREAKING
As defined on https://developer.github.com/v3/checks/runs/#annotations-object `blob_href` is no longer a parameter.
Opening this as discussed in https://github.com/google/go-github/pull/1241#pullrequestreview-266956347

remove blob_href from check annotations

---

github/pulls.go

Fix an error in PullRequestsService.Edit when closing PRs
due to 'base' field being present together with
State = 'closed'.  In this case the GitHub API v2.17.5
responds with an error:
'Cannot change base branch of closed pull request'.
Fixes #1250.

Fix failure in closing PRs

---

github/github-accessors.go
github/repos_commits.go
github/repos_commits_test.go

When using [ListBranchesHeadCommit](https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListBranchesHeadCommit) I'm seeing the error:
```
json: cannot unmarshal bool into Go struct field BranchCommit.protected of type string
```
That's because although the [documentation](https://developer.github.com/v3/repos/commits/#response-3) statements that `protected` field is a string but the response is boolean in fact:
**Request**
```
curl -H "Accept: application/vnd.github.groot-preview+json" \
'https://api.github.com/repos/google/go-github/commits/master/branches-where-head'
```
**Response**
```json
[
{
"name": "master",
"commit": {
"sha": "2e90302801c870f17b6152327d9b9a03c8eca0e2",
"url": "https://api.github.com/repos/google/go-github/commits/2e90302801c870f17b6152327d9b9a0 …
```

Fix BranchCommit.Protected

---

github/github-accessors.go
github/repos.go
github/repos_test.go

Add support for BranchListOptions for `RepositoriesService.ListBranches`.
ref. https://developer.github.com/v3/repos/branches/#list-branches

Add support for BranchListOptions

---

github/search.go

Addressed the document part of https://github.com/google/go-github/issues/1266

Add document for query of search functions

---

github/github-accessors.go
github/orgs.go
github/orgs_test.go

Support the new preview API endpoint to list GitHub
App installations for an organization
This commit fixes #1319

Support List GitHub App installations for organization

---

github/event_types.go

Nothing major, only ran our spell-checker on the vendored go-github package, and this showed up.

Simple spelling error

---

github/reactions_test.go

This PR relates to (#55) and adds a test for the Reaction and Reactions resources.

added test for JSON marshalling for Reaction and Reactions - relates to (#55)

---

github/github-accessors.go
github/repos.go
github/repos_test.go

The API will omit this field when dismissal restrictions are not in place, the response struct has been updated to reflect this.
Also corrected the code and tests for `DisableDismissalRestrictions`.
Fixes #1287

Mark dismissal_restrictions optional in responses

---

github/github-accessors.go
github/users_projects.go
github/users_projects_test.go

GitHub Projects support user-based projects and there are APIs about `List user projects` and `Create a user project`.
Seems go-github does not support them and I want to implement the feature.
* Add `List user projects` and `Create a user project`
Fixes #1294.

Add list and create projects for users

---

github/repos_contents.go
github/repos_contents_test.go

Adds a `followRedirects` parameter, which when `true` will follow the URLs returned with `301 Moved Permanently` statuses (i.e if a repo has been renamed). Once a 302 status is found, that `Location` will be returned to the user.
Adds 2 unit tests for 301 status code return, for when `followRedirects` is `true` and `false`. 
Manually tested, invoking the function against repos both renamed and not renamed.
Fixes https://github.com/google/go-github/issues/1248

Add option to follow 301 redirects for GetArchiveLink

---

github/checks.go
github/checks_test.go
github/github-accessors.go

I couldn't find the changelog of this change but the current document
[1] doesn't mension `head_branch` field anymore.
I also confirmed the Check API works without the field.
[1]: https://developer.github.com/v3/checks/runs/#create-a-check-run

Remove needless HeadBranch from Create/Update CheckRun APIs

---

github/apps.go
github/github-accessors.go
github/repos.go
github/repos_test.go

Added support for allowing apps to push to protected branches

---

github/git_trees.go
github/git_trees_test.go

Improved version of https://github.com/google/go-github/pull/1307
Solves #1268
I think it actually is this simple @gmlewis  😅

Support delete files for CreateTree

---

github/reactions.go
github/reactions_test.go

This PR adds ListCommentReactionOptions struct and substitute it to the ListMigrations method.
Fixes #1281

Add ListCommentReactionOptions to ListCommentReactions

---

github/github.go
github/github_test.go

PR for the enhancement mentioned in Issue #1318. Also added unit tests for both RateLimitError and AbuseRateLimitError.
Why remove the message check for RateLimitError?
The message can be different for enterprise versions of GitHub. Besides, the rate limit header and HTTP status codes are sufficient to identify a rate limit error.
Why not remove the URL check for AbuseRateLimitError?
HTTP response in this situation does not contain any unique header values that would be sufficient to confirm an abuse. Although it is not ideal to do a suffix match on documentation_url, there seems to be no better way.
Reference to GitHub API rate limiting: https://developer.github.com/v3/#rate-limiting

Simplify rate limit error check

---

github/github_test.go
github/orgs_test.go

This pull request contains two items:
1. Modifies the JSON comparison utility for checking marshalling, making it non sensible to key order.This makes it easier to write tests for marshalling, since there is no need to worry about keeping the right order of the JSON keys in the wanted string.  It also removes a non working part of the test. *I made sure old tests using this utility would still break if given the wrong input*.
2. Adds a new test for marshalling organizations (issue #55 )

Test for marshalling Organizations and make JSON comparison non sensitive to key order

---

github/github.go
github/github_test.go

I am adding a nil check for the provided context and return an error instead of panic.
@gmlewis raised a valid point that this is a user error but probably is better to return and error than panic.
Related to #1260

Add context nil check on client Doer

---

github/github-accessors.go
github/repos_deployments.go

Fixes #1116.
I tested this change with the following code:
```go
func createDeployment() {
owner := "gmlewis"
repo := "my-test-repo"
foo := struct {
Foo int    `json:"foo,omitempty"`
Bar string `json:"bar,omitempty"`
}{Foo: 1, Bar: "test create deployment with interface{}"}
req := &github.DeploymentRequest{
Ref:                  github.String("master"),
TransientEnvironment: github.Bool(true),
// Payload:              github.String(`{"foo":1}`),
Payload: &foo,
}
ctx := context.Background()
deployment, _, err := client.Repositories.CreateDeployment(ctx, owner, repo, req)
if err != nil {
log.Fatalf("Repositories.CreateDeployment returned error: %v", err)
}
goon.Dump(deployment)
}
```
and when listing the deployments created on multiple runs, I see:
```
2019/02/12 09:55:03 #0: …
```

Allow any Payload during deployment creation

---

github/github.go
github/github_test.go

Re-populate HTTP response body of ErrorResponse

---

github/github.go
github/github_test.go

> "errors" is list of string for review API.
```
{
"message": "Validation Failed",
"errors": [
"Cannot return null for non-nullable field PullRequestReviewComment.position"
],
"documentation_url": "https://developer.github.com/v3/pulls/reviews/#get-a-single-reviews-comments"
}
```
See #540 for the detail of the problem.
Related: #1136
I assume GitHub won't change the error structure as it's already in production.
I hope they will document the error format, but anyway go-github needs to support it for the sane error handling,
Even if #1136 is implemented, it should be better to represent error as ErrorResponse struct, IMO.
so I implement it by re-using `message` field as a workaround.

Support unexpected error response format

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/simple/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

Reverts google/go-github#1344 due to breaking the build.

Revert "Bump major version to v29"

---

github/apps.go

I got following error.
json: cannot unmarshal string into Go struct field App.app.events of
type github.Event
It's regression from #1283 and event type should be actually string.
https://developer.github.com/v3/apps/#get-a-single-github-app
https://developer.github.com/v3/repos/branches/#list-apps-with-access-to-protected-branch

Fix JSON unmarshal error of App.app.events

---

github/git_trees.go
github/git_trees_test.go

Implement file deletion for CreateTree

---

github/repos_releases.go
github/repos_releases_test.go
test/integration/repos_test.go

Adds an extra parameter to DownloadReleaseAsset `followRedirects`. This will tell the client to follow one level of redirects when downloading the asset.
Solves #1378

Allow DownloadReleaseAsset to follow redirects

---

github/github-accessors.go
github/repos.go

GitHub has been adding some new fields in the branch protections
as documented:
https://developer.github.com/v3/repos/branches/#get-branch-protection
the documentation references the new fields in the branch protection as:
https://developer.github.com/v3/repos/branches/#get-branch-protection:
`GET /repos/:owner/:repo/branches/:branch/protection`
```
"required_linear_history": {
"enabled": true
},
"allow_force_pushes": {
"enabled": true
},
"allow_deletions": {
"enabled": true
}
```
https://developer.github.com/v3/repos/branches/#update-branch-protection:
`PUT /repos/:owner/:repo/branches/:branch/protection`
|field|type|required?|
|-|-|-|
|`required_linear_history`|boolean|optional|
|`allow_force_pushes`|boolean|optional|
|`allow_deletions`|boolean|optional|
This PR achieves a similar goal …

Add new branch protection values

---

github/github.go

There is no need for new() is this case and buf can be initialized in
a single statement as proposed.

Use normal object initialization instead of new()

---

github/github.go
github/repos.go
github/repos_test.go

Fixes #1390.
Now GitHub officially supports **creating a repository dispatch event API**
https://developer.github.com/changes/2020-01-22-everest-preview-graduated/

Remove "everest" custom preview header on official GitHub release 

---

README.md

pkg.go.dev understands modules, whereas godoc.org does not.

use pkg.go.dev for documentation

---

github/event_types.go
github/github-accessors.go

- added archived and disabled fields to PushEventRepository
- updated github accesssors via running `go generate`
Closes https://github.com/google/go-github/issues/1380

Add archived and disabled to PushEventRepository

---

README.md

Reverts google/go-github#1407 as discussed in #1406.

Revert "Add TODOs badge to the README"

---

github/repos_pages.go
github/repos_pages_test.go

Support specification of parameters for enable pages API as per: https://developer.github.com/v3/repos/pages/#parameters
Fixes #1408.

Support specification of parameters for enable pages API

---

github/actions.go
github/actions_secrets.go
github/actions_secrets_test.go
github/github-accessors.go
github/github.go

This adds support for managing [github action secrets](https://developer.github.com/v3/actions/), an API feature that was recently announced.
Relates to: #1399

Implement support for action secrets

---

github/checks.go
github/git_refs.go
github/git_refs_test.go
github/repos_commits.go
github/repos_commits_test.go
github/repos_statuses.go

fixes #1432
Signed-off-by: Hanno Hecker <hanno@zalando.de>

do not encode / in ref names

---

github/teams_discussion_comments.go
github/teams_discussion_comments_test.go

Update endpoints for:
https://developer.github.com/v3/teams/discussion_comments/
All endpoints in "Team Discussion Endpoints" now have two ways to call
them: ByID and BySlug.
Fixes #1423.

Update teams_discussion_comments with ByID and BySlug endpoints

---

github/actions_workflow_jobs.go
github/actions_workflow_jobs_test.go
github/github-accessors.go

This PR adds support for managing the most recent update of Action Workflow Jobs.
Relates to: #1399
By the way, there are several things that I am still not sure of:
- The action in the original GitHub documentation is "List workflow job logs" thus I name the function `ListWorkflowJobLogs` but since it basically retrieve a URL to download a text file that contain the logs I think it would be better to name it `GetLogsFileURL`.
- I am still not sure of perhaps how `go-github` would implement this particular function since the URL of the file is in the header of the response. Do you have any example of other functions that implement this kind of response? 
Thank you very much beforehand :slightly_smiling_face:

Implement support for actions workflow jobs

---

github/teams_discussions.go
github/teams_discussions_test.go

Update teams_discussions with ByID and BySlug endpoints

---

github/pulls.go

This change is specifically motivated by the desire to replicate
the same behavior as observed when merging PR's manually using
the "Squash and Merge" option. In that case, a commit message
including the title and commit message of all the commits in the
PR are included, and the squashed commit includes all of that
context.
I have tested that its possible to merge a Pull Request with
an empty commit message and verified that the api call replicates
the desired behavior:
```
curl -XPUT \
-H "Accept: application/vnd.github.v3+json" \
-H "Authorization: token $GITHUB_API_TOKEN" \
-d '{"merge_method":"squash"}' \
https://api.github.com/repos/pratikmallya/test/pulls/4/merge
{
"sha": "08d173ee449e4ea505d8366b9fa416d6d3923f23",
"merged": true,
"message": "Pull Request successfully merged"
}
``` …

FIX: allow empty commitMessage for merging pulls

---

github/reactions.go
github/reactions_test.go

Delete a commit comment reaction
- `DELETE /repos/:owner/:repo/comments/:comment_id/reactions/:reaction_id`
- Docs: https://developer.github.com/v3/reactions/#delete-a-commit-comment-reaction

Add support to delete commit comment reaction

---

scrape/forms.go
scrape/forms_test.go

improve form parsing to support textarea elements, as well as proper
handling of radio and checkbox inputs (only include the value if the
"checked" attribute is set).
also allow nil setValue func for fetchAndSubmitForm.  While I don't know
of a case (yet) where we want to do this, there's no point in panicking
in this case.

scrape: support textarea, radio, and checkbox

---

github/actions_runners.go
github/actions_runners_test.go
github/github-accessors.go

This PR adds support for the GitHub Actions [Runners API](https://developer.github.com/v3/actions/self_hosted_runners/).
Relates to: #1399
For the [list self hosted runners](https://developer.github.com/v3/actions/self_hosted_runners/#list-self-hosted-runners-for-a-repository) endpoint I sent an email to support regarding the example showing the array nested two levels deep which doesn't match the actual responses I was getting, and inquiring about if they intended to include a `total_count` field like most other endpoints that support pagination.
One of the things I'm not sure about is the return and struct field types, specifically which ones should be references (e.g. `*[]Type` or `*[]*Type` for a list return type, or something else?)

Implement support for actions runners

---

github/github-accessors.go
github/repos_pages.go
github/repos_pages_test.go

Implements support for updating Github Pages sites - allowing CName and
Source to be customized.
Fixes: #1361

Implement support for update pages API

---

github/actions_workflow_jobs.go
github/actions_workflow_jobs_test.go

This adds support for an optional `filter` parameter to the list workflow jobs endpoint that was recently announced. See #1454.

Add support for filter parameter to the list workflow jobs endpoint

---

github/authorizations.go
github/authorizations_test.go
github/github.go
test/integration/authorizations_test.go

Updates based on https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
Fixes #1331.

Update and remove OAuth endpoints

---

github/github.go

In the pull request #1178, the behavior on the client instantiation change to use a new `http.Client` instead of using the `http.DefaultClient`. This change is reflected in the comment block for `NewClient` but not for `NewEnterpriseClient` .

Update the comment for NewEnterpriseClient

---

github/issues.go

Hi,
I found a very small problem when using [go-github](https://github.com/google/go-github). 
`https://developer.github.com/v3/issues/#list-issues-for-a-repository` is exists, but the anchor point (`#list-issues-for-a-repository`) is invalid.
I try to find the correct anchor point (`#list-repository-issues`) and update the corresponding content of the annotation.
This is a sacred moment for me! Please check it.

Update anchor with GitHub API docs in annotation

---

github/admin_orgs.go
github/admin_orgs_test.go
github/github-accessors.go

Adds RenameOrg and RenameOrgByName functions for the Github Enterprise Organization Admin API. Addresses #1479.

Add RenameOrg endpoint for Org Admin API

---

github/teams.go
github/teams_test.go

Addresses Issue #1483 
Changes include:
* Update method signatures of `#ListIDPGroupsForTeam` and `#CreateOrUpdateIDPGroupConnections`  to include the organization name identified as `org` and rename the `teamID` attribute to `slug` as it can be misleading/the api requires the slug for these particular calls
* Update respective tests with corrected arguments

Update IdP team-sync list and create/update endpoints with ByID and BySlug

---

github/gitignore.go
github/reactions.go
github/repos_keys.go
github/repos_keys_test.go
github/users_projects.go
github/users_projects_test.go

#1477 found a number of problems in the repo that would cause breaking API changes to fix them.
Instead of including them there, it [was decided](https://github.com/google/go-github/pull/1477#pullrequestreview-391172913) to pull the breaking API changes into a separate PR, which is this one.

Fix receivers and other breaking changes

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/simple/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

Due to breaking API changes in #1484 and #1487, we need to bump the major version for the next release. This PR prepares for that release.

Prepare for release v31

---

github/event_types.go
github/github-accessors.go

The RepositoryVulnerabilityAlertEvent payload includes the Repository key which is important to add context to the Alert. The alert by itself does not capture what repo the alert is on.
https://developer.github.com/v3/activity/events/types/#repositoryvulnerabilityalertevent
```
{
"action": "create",
"alert": {
"id": 271940701,
"affected_range": "< 2.2.3",
"affected_package_name": "https-proxy-agent",
"external_reference": "https://github.com/TooTallNate/node-https-proxy-agent/commit/36d8cf509f877fa44f4404fce57ebaf9410fe51b",
"external_identifier": "WS-2019-0310",
"ghsa_id": "GHSA-pc5p-h8pf-mvwp",
"created_at": "2020-04-16T22:28:10Z",
"fixed_in": "2.2.3"
},
"repository": {
// repo details here
}
```

Add Repository to the RepositoryVulnerabilityAlertEvent struct

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go

closes #1497 
- update the method to use the more specific ListWorkflowRunsOptions struct
Let me know if I need to update any of the tests as well - I looked through the existing tests and didn't see any that were specifically testing the unique query params of workflow endpoints.

Update ListRepositoryWorkflowRuns to support all query parameters

---

github/actions_runners.go
github/actions_runners_test.go

Closes #1505 
This adds support for the organization-wide self-hosted runners API
The API for self-hosted runners on organization level is almost similar to the ones for repositories, only the the URL path is slightly different, and you need an organization owner token for the new functions to work.
Because of the similarities, this was basically a large copy & paste operation, so for each function there is now an `Organization` counterpart. This is not really DRY, but it makes it more explicit what API is being used.
(An alternative solution would be to have a switch inside each function to decide to use the organization or repository API based on the presence of the repo parameter. I have made that as well on a separate branch. The implementation is much smaller, but the organization …

Support self-hosted organization runners

---

github/actions_workflow_jobs.go
github/actions_workflow_runs.go

Updates the API doc URLs that changed -- workflow-runs and workflow-jobs (and self-hosted-runners).
Closes #1502.

Update changed API doc URLs

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go

Adds support for the new endpoint added to delete logs.
Doc link: https://developer.github.com/v3/actions/workflow-runs/#delete-workflow-run-logs
Fixes #1500.

Add DeleteWorkflowRunLogs function

---

github/apps.go
github/apps_test.go

Add support for [Suspend](https://developer.github.com/v3/apps/#suspend-an-installation) and [Unsuspend](https://developer.github.com/v3/apps/#unsuspend-an-installation) GitHub App installation.
Fixes #1517

SuspendInstallation and UnsuspendInstallation for GitHub Apps

---

github/apps.go
github/apps_test.go

Adds support for deleting a GitHub app installation (https://developer.github.com/v3/apps/#delete-an-installation).
Closes #1436.

Add DeleteInstallation for GitHub Apps

---

github/actions_workflow_runs_test.go

Fixes #1528 
Small PR to change the error message of the test of `GetWorfklowRunByID` that uses `ListWorkFlowRunsByFileName` instead.

Fix error message for the test of GetWorkflowRunByID

---

github/repos.go

I've encountered an issue trying to update BranchRestriction on a personal repository. Github doesn't allow `teams` and `users` fields in the request payload.
```go
p := github.ProtectionRequest{
Restrictions: &github.BranchRestrictionsRequest{
Apps: []string{"myapp"},
},
}
client.Repositories.UpdateBranchProtection(ctx, org, repo, branch, p)
```
will return
```
No subschema in "anyOf" matched.
For 'properties/users', nil is not an array.
For 'properties/teams', nil is not an array.
Not all subschemas of "allOf" matched.
For 'anyOf/1', {"users"=>nil, "teams"=>nil, "apps"=>["myapp"]} is not a null.
```
but if I set `Teams` and `Users` fields as `[]string{}` Github returns `422 Validation Failed [{Resource: Field: Code: Message:Only organization repositories can have users and team …

Enable BranchRestriction fields to be empty

---

github/actions_secrets.go
github/actions_secrets_test.go
github/github-accessors.go

Related to #1525 and #1532.
Adds organization secrets https://developer.github.com/v3/actions/secrets/#get-an-organization-public-key and updates the repository secret actions API (probably would match how they would be named if org support had been in from the beginning, though it would be considered a breaking change).
Some possible issues:
- Checking with GitHub support if parameter selected repository ids should be an array of integers instead of array of strings. I think its been ~1 week?
-  Naming of the functions using the API endpoint header results in very long names.
- Handling of extra values in `Secret` and `EncryptedSecret` for organization secrets that repository secrets don't have: does omitempty make sense or should they be separate structs?
- Should there be an underlying …

Add organization secret API support

---

github/repos_contents.go

Export ArchiveFormat

---

github/messages.go
github/messages_test.go

Fixes #1543 by adding `github_app_authorization` to the event map used to parse webhooks.

Handle github_app_authorization webhook

---

github/actions_workflow_runs.go
github/github-accessors.go

Adds the missing `workflow_id` field from workflow runs endpoint.
See docs: https://developer.github.com/v3/actions/workflow-runs

Add missing workflow_id field from workflow run

---

github/pulls.go

The documentation comments for `commitMessage` and `commitTitle` is not consistent with those of [GitHub API Reference](https://developer.github.com/v3/pulls/#merge-a-pull-request) (they are swapped).

Fix documentation for commitMessage and commitTitle of func (*PullRequestsService) Merge

---

github/repos_deployments.go
github/repos_deployments_test.go

Add DeleteDeployment for Repositories

---

github/authorizations.go
github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github.go

Adds a Code Scanning service with functions for getting code scanning alerts.
Docs: https://developer.github.com/v3/code-scanning/

Add support for Code Scanning API

---

github/github-accessors.go
github/github-stringify_test.go
github/pulls_reviews.go
github/pulls_reviews_test.go

This adds support for the "comfort-fade" preview, which enables multi-line comments (incl. suggested edits).
I have been carrying a subset of this as a patch downstream for a while, which just hard wired things on, but I tried to make this "smart" for back-compat as part of upstreaming.

Add support for multi-line comments.

---

github/event.go
github/event_types.go
github/github-accessors.go
github/github-stringify_test.go
github/messages.go
github/messages_test.go
github/packages.go

Addresses https://github.com/google/go-github/issues/1550

Handle package webhook

---

github/repos.go

Closes #1546 
Notes:
* this reverts a previous change to the `BranchRestrictionsRequest` as it does not behave as expected such that restrictions configured for individual repositories still result in an error if users/teams fields are not set e.g.
```
No subschema in "anyOf" matched.
"teams", "users" weren't supplied.
Not all subschemas of "allOf" matched.
For 'anyOf/1', {"apps"=>["myApp"]} is not a null.
```
or if set to `nil` or `[]string{}` e.g.
```
422 Validation Failed [{Resource: Field: Code: Message:Only organization repositories can have users and team restrictions}]
```
* in addition, the change introduced a break in behavior for organization-level repositories as discussed in #1546
* a workaround didn't seem feasible as the validation issue seems to be upstream but any further …

github/repos: remove omitempty option in BranchRestrictionsRequest

---

github/github-accessors.go
github/pulls_comments_test.go
github/reactions.go
github/reactions_test.go

The [documentation](https://developer.github.com/v3/reactions/) lists two emojis which are not currently mapped over from the GitHub API response. This PR adds those emojis to the Reactions struct and aligns comments to reflect the new additions.

Add rocket and eyes as available emojis on the Reactions struct

---

github/github-accessors.go
github/issues_comments.go
github/issues_comments_test.go

For: #1583 
- The `Sort` & `Direction` fields in` IssueListCommentsOptions` were removed from the github api so they no longer work.
- Fields have been removed from the struct and any corresponding tests. 
> These are tagged as breaking changes so not sure if anything else needs to be updated to reflect that

Fix: Remove Sort & Direction Fields From IssueListCommentsOptions

---

github/github.go

According to the official Go docs:
https://golang.org/pkg/net/http/#Body
```
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body. The default HTTP client's Transport may not
// reuse HTTP/1.x "keep-alive" TCP connections if the Body is
// not read to completion and closed.
```
To ensure http.Client connection reuse, I did the following things:
- Read until Response is complete (i.e. ioutil.ReadAll(resp.Body) or similar)
- Call Body.Close()
Closes #1575

Read response body for TCP connection reuse

---

.github/workflows/tests.yml

Since Go 1.15 has been released, and we want to test the two most recent major releases of Go on this repo, this PR bumps workflows/tests.yml to test the most recent (1.x) version of Go, and the next-most-recent (1.14.x) version.

Support Go 1.15 and 1.14 in workflows/tests.yml

---

github/apps.go
github/apps_test.go
github/github.go

While implementing the content attachment flow I found that the header needed to use this API has been changed. Included the link to the changes blog post referencing this.

Update content type header for AppsService.CreateAttachment

---

github/apps.go
github/github-accessors.go
github/github-stringify_test.go

Since Github exposes the node_id fields on the installation object, this PR enables reading the field.

Add NodeID field to Installation

---

github/actions_workflows.go
github/actions_workflows_test.go

I noticed that the github client hadn't added support for this functionality yet.
According to https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event, this endpoint is utilized for manually triggering a Github Actions workflow run.
I purposely left out support for the `inputs` key, since due to its dynamic nature, might be a larger  and more complicated change than we want.

Add support within Actions for creating a workflow dispatch event

---

github/repos_contents.go
github/repos_contents_test.go

Fix #1629 
To avoid producing an invalid request URL like `.github/?ref`.

Remove trailing slash when passing directory path to GetContent

---

github/apps.go
github/apps_installation.go
github/apps_installation_test.go
github/apps_test.go
github/github.go
github/issues.go
github/issues_events.go
github/issues_events_test.go
github/issues_test.go
github/orgs.go
github/orgs_test.go
github/pulls.go
github/pulls_test.go

This PR addresses below issue
#1616

Remove graduated GitHub v3 API preview headers

---

github/event_types.go
github/event_types_test.go

Add support for webhook which is triggered when you change the base branch in a pull request after opening it. 
Fixes: #1617

Add Base, Ref, and SHA to EditChange struct

---

github/checks.go
github/checks_test.go
github/github.go

removed Accept header (with value mediaTypeCheckRunsPreview). Since checks run is out of preview, didn't see any value in keeping it.
Followed as per,
Graduation of preview: https://developer.github.com/changes/2020-10-01-graduate-antiope-preview/
Docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/checks

Remove graduated GitHub v3 API preview header

---

github/github-accessors.go
github/issues_events.go

Hey, this PR adds support for the [review_requested](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/issue-event-types#review_requested) and [review_request_removed](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/issue-event-types#review_request_removed) issue events.

Add support for review events

---

github/actions_runners.go
github/github-accessors.go

Related to [this](https://github.com/google/go-github/issues/1647) issue.
When calling ListOrganizationRunners there is additional information in a label array (see [here](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#list-self-hosted-runners-for-an-organization) )

Add Label data to Runner calls

---

github/github.go

The changes in the PR #1576 are not needed now as the latest official Go Http package does it internally. So Now, it is possible to remove the code from the PR.
https://github.com/golang/go/blob/master/src/net/http/client.go#L698
closes #1646

Clean up connection reuse code inside Do func as now Go HTTP packge does it internally

---

github/repos_commits.go
github/repos_commits_test.go

This change will fix #1642 by replacig `#` with `%23` in the base and head refs which are required for comparing commits.
Fixes #1642.

Escape # in CompareCommits base and head refs

---

github/actions_runners.go
github/actions_runners_test.go

This PR implements the `List selected repositories enabled for GitHub Actions in an organization` method. The endpoint for this feature is `/orgs/{org}/actions/permissions/repositories`. More details around this can be found here: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#list-selected-repositories-enabled-for-github-actions-in-an-organization

[New Method] Actions/Runner: List enabled repos in organization for Actions

---

github/checks.go
github/checks_test.go
github/github-accessors.go

This PR is regarding [issue 1652.](https://github.com/google/go-github/issues/1652) head_sha is no longer supported as a parameter in case of [updating a check run](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#update-a-check-run). Therefore it is being removed from **type UpdateCheckRunOptions** in this PR. 
Fixes #1652.

Remove HeadSHA parameter from UpdateCheckRunOptions

---

github/actions_workflows.go
github/actions_workflows_test.go

Add Workflow Dispatch Event by ID and FileName

---

example/newreposecret/go.mod
example/newreposecret/go.sum

This PR updates a yaml dependency that was flagged as having vulnerabilities according to Snyk:
https://snyk.io/vuln/golang:github.com%2Fgo-yaml%2Fyaml
Closes #1631.

Update yaml dependency

---

github/actions_workflows.go

The `disableWorkflow` method was not being called, so this PR renames `enableWorkflow` and removes the unused method.

Remove unused disableWorkflow method

---

github/github-accessors_test.go

Due to the sequence of commits, the tests need updating for all workflows to pass.  This PR fixes the problem.

Update tests due to recent PR merges

---

github/checks_test.go

This PR increases the code coverage for `checks.go` to 100%.

Increase checks.go code coverage

---

github/checks_test.go
github/github_test.go

This PR cleans up code coverage tests starting in checks_test.go to reduce duplicated code and reduce the likelihood of method name typos that were previously too easy to make.

Clean up coverage tests in checks_test.go

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

According to the [documentation](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-contributors) for ListContributors:
> To improve performance, only the first 500 author email addresses in the repository link to GitHub users. The rest will appear as anonymous contributors without associated GitHub user information.
Anonymous user results are returned from the API like this:
```
{
"email": "email@email.com",
"name": "First Last",
"type": "Anonymous",
"contributions": 109
}
```
Both name and email are only returned for anonymous users and are not currently mapped in the [contributor](https://github.com/google/go-github/blob/master/github/repos.go#L517) struct. This PR adds those two fields to the struct and accessors.

Adding name and email fields to Repository.Contributor

---

github/repos_commits.go
github/repos_commits_test.go

Fixes: #1642 as reported in #1654 
I added code to escape `base` and `head` part of the URL in `CompareCommits` and `CompareCommitsRaw` methods.
Also did changes in relevant test methods, which are now testing for the following 3 cases:
```java
{base: "b", head: "h"},
{base: "123base", head: "head123"},
{base: "`~!@#$%^&*()_+-=[]\\{}|;':\",./<>?/*-+123base", head: "head123`~!@#$%^&*()_+-=[]\\{}|;':\",./<>?/*-+"},
```
P.S. - Here's the original [pull request](https://github.com/google/go-github/pull/1649) that had to be reverted.

Escape base and head in repos_commits.go

---

github/github.go
github/github_test.go

This allows the user to also treat bodies as plain go streams.
For more flexibility.
~Before this, passing a nil body would do the request but close the~
~body. Now it is up to the caller to close resp.Body.~
~I mainly wanted to be able to do this to stream bodies and to re-use the same HTTP client in order to download release files.~
Edit:
This PR enables using the client as an http client with Github Specific error handling and throttling management.

Add client.BareDo to allow user to handle the body

---

github/misc.go
github/misc_test.go

GitHub have added two extra IP address types in the `/meta` API. That is `actions` and `dependabot`.
I have extended the `APIMeta` method and struct with that new data, so we can consume it.
Closes https://github.com/google/go-github/issues/1777

Extend IP ranges in meta API

---

github/repos.go
github/repos_test.go

Add RemoveRequiredStatusChecks API and tests

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/users_keys.go

feature
When calling `Users.ListKeys` (API Method: [List public SSH keys for the authenticated user](https://docs.github.com/en/rest/reference/users#list-public-ssh-keys-for-the-authenticated-user)), the field `verified` is not populated.
This PR enabled adds `visibility` files to the USers.Key structure.
None
None
- [List public SSH keys for the authenticated user @ GitHub REST API docs](https://docs.github.com/en/rest/reference/users#list-public-ssh-keys-for-the-authenticated-user)

User.Keys: Add verified field

---

github/repos.go
github/repos_test.go

feature
When calling `Repositories.List` (API Method: [List repositories for the authenticated user](https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user)), the field `visibility` is always `nil`.
The `visibility` was introduced in a developer / API preview controlled by the media accept header. 
This PR enabled the API preview `nebula-preview` for `Repositories.List`, to retrieve the `visibility` of a repository.
None
None
- [List repositories for the authenticated user @ GitHub REST API …

Repository.List: Add nebula-preview to receive visibility field

---

github/repos.go
github/repos_test.go

Removes unnecessary **mediaTypeRequiredApprovingReviewsPreview** headers as described in #1779

Clean up unnecessary preview headers

---

github/messages.go
github/messages_test.go

This relates to #592 and adds support for the `X-Hub-Signature-256` header. I've chosen to set the SHA256 header as the default and falling back to the SHA1 header when the SHA256 header is empty. The GitHub documentation [recommends](https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks#validating-payloads-from-github) using the SHA256 header so I don't expect the fallback to be needed in a live environment. Still, this fallback prevents introducing breaking changes when used in tests.

Add support for the X-Hub-Signature-256 header

---

github/enterprise_actions_runners.go
github/enterprise_actions_runners_test.go

adds support for
https://docs.github.com/en/rest/reference/enterprise-admin#delete-a-self-hosted-runner-from-an-enterprise

Add support for removing enterprise Actions runners

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_hooks.go
github/strings_test.go

feature
Adds support for missing fields in the Repository.Hook structure.
Here is an example of a full response of a public repo, where I am the owner + when I call ListHooks
```
{
"type": "Repository",
"id": <ID> (int),
"name": "web",
"active": true,
"events": [
"create",
"delete",
"issue_comment",
"member",
"public",
"pull_request",
"push",
"repository"
],
"config": {
"url": "https://notify.travis-ci.org",
"insecure_ssl": "0",
"content_type": "form"
},
"updated_at": "2019-01-15T15:40:01Z",
"created_at": "2019-01-15T15:40:01Z",
"url": "https://api.github.com/repos/andygrunwald/go-jira/hooks/<ID>",
"test_url": "https://api.github.com/repos/andygrunwald/go-jira/hooks/<ID>/test",
"ping_url": …
```

Repository.Hook: Add missing fields Type, Name, TestURL, PingURL and LastResponse

---

github/apps_installation.go
github/apps_installation_test.go
github/github-accessors.go
github/github-accessors_test.go

- Fixes #1791
- Modified Tests in `apps_installations_test.go`

Change ListRepos and ListUserRepos to return new ListRepositories struct with count

---

github/repos.go
github/repos_test.go

feature
**What this PR does / why we need it:**
In addition to the changes added in https://github.com/google/go-github/pull/1780, this change also ensures the `Visibility` field is included when calling `Repositories.ListByOrg`.
**Special notes for your reviewer:**
None

Repository.ListByOrg: Add nebula-preview to receive visibility field

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs.go
github/orgs_test.go

Update Organization
Bring Organization inline with the latest API changes  (see https://docs.github.com/en/rest/reference/orgs#get-an-organization)

Add MembersCanCreate* to Organization

---

.github/workflows/tests.yml

improvement
go v1.16 is released.
go-github still tests against v1.14.
This PR raises the go version to v1.16 to test against.
None
None
- [Go 1.16 is released)](https://blog.golang.org/go1.16)

Support Go 1.16 and 1.15 in workflows/tests.yml 

---

github/event_types.go

documentation
The inline documentation for the `InstallationEvent` went out of date.
This PR fixes the link + possible values.
Furthermore, does the REST API send a `requester` key as well.
In my current use-case, this was `null`, hence I am not aware of the type (is not documented).
As a trade-off for now, I added a TODO. Once the type is known, this can be extended
This applies the same fix as in https://github.com/google/go-github/pull/1780
None
- [Webhook events and payloads: installation](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#instal …

Fix inline docs for InstallationEvent type

---

github/actions_workflow_runs.go
github/github-accessors.go
github/github-accessors_test.go

Adds the missing name field from workflow runs endpoint.
See docs: https://docs.github.com/en/rest/reference/actions#get-a-workflow-run

Add missing name field from workflow run

---

github/apps_installation.go
github/apps_installation_test.go

feature
* mercy-preview: For receiving repository topics
* nebula-preview: For visibility information
When calling `Apps.ListRepos` or `Apps.ListUserRepos`, the field `visibility` and `topic` are always `nil`.
The reason: Missing headers for developers preview API.
This applies the same fix as in https://github.com/google/go-github/pull/1780
None
- [API changes to support internal repository visibility (2019-12-03)](https://developer.github.com/changes/2019-12-03-internal-visibility-changes/#repository-visibility-fields)

Apps.ListRepos/Apps.ListUserRepos: Add mercy-preview + nebula-preview headers

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/github.go
github/orgs_actions_allowed.go
github/orgs_actions_allowed_test.go
github/orgs_actions_permissions.go
github/orgs_actions_permissions_test.go

Implements methods to interact with `/orgs/MY-ORG/actions` API:
- https://docs.github.com/en/rest/reference/actions
This is important to allow setting up github-actions policies at organization level using this library (e.g. enable/disable github-actions, set/edit filters for allowed actions).
I'm fairly new to using this library and I hope I covered all that's needed here, but please let me know if there is something missing or incomplete.

Add ActionsAllowed and ActionsPermissions to Organization

---

github/pulls.go
github/pulls_test.go

Fixes https://github.com/google/go-github/issues/1815
- changes the CommitMessage field in the request to merge a PR to a pointer
- adds a new boolean flag to the PullRequestOptions struct, which will make the commit message null if set and the given message is ""

Support empty string as a commit message when merging a pull request

---

github/search.go

Currently the search service does not include the reactions preview media type header so issue searches do not include the reaction counts this preview provides. The issue struct already includes this [attribute](https://github.com/google/go-github/blob/b06cfbb1abc090e2ff47cac2f0d2d1750f847293/github/issues.go#L52) so adding this preview header is enough to populate it.
This PR adds that preview so this structure is populated.

Add reactions preview to search service

---

.github/workflows/tests.yml

👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, this changes actions to only run against the …

Improve Actions hygiene

---

.github/workflows/tests.yml

- only run with a single Go version on Windows, since we're just testing
basic things like path separators
- only upload code coverage stats once, not for every build
configuration
- use latest version of actions/cache

tidy up GitHub actions config

---

github/pulls_reviews.go

#540  was close but this, rather confusing, comment was left behind in the last release

Remove outdated todo

---

README.md

The roadmap spreadsheet has not been used lately and I believe it would improve the README.md to simply remove it to reduce confusion.

Remove obsolete roadmap spreadsheet from README.md

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/newreposecret/go.mod
example/newreposecret/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go
update-urls/go.mod

This PR is in preparation for release `v34.0.0`.

Bump version of go-github library

---

github/apps_marketplace.go
github/apps_marketplace_test.go
github/github-accessors.go
github/github-accessors_test.go

To simplify review and address specific requests from https://github.com/google/go-github/issues/1270#issuecomment-791389308 I've made separate commits.
Also wording doesn't seem to match GitHub docs anymore.
If that's ok @gmlewis, I'd like to rename:
- GetPlanAccountForAccount to GetSubscriptionPlanForAccount https://octokit.github.io/rest.js/v18#apps-get-subscription-plan-for-account
- MarketplacePlanAccount to MarketplaceSubscriptionPlan
What do you think?

Fix invalid response and rename ListPlanAccountsForAccount (fixes #1270)

---

github/actions_secrets.go
github/actions_secrets_test.go

Support numeric public key ids for actions

---

github/actions_secrets.go
github/actions_secrets_test.go
github/github-accessors.go
github/github-accessors_test.go
github/repos_environments.go
github/repos_environments_test.go

Add support for environments and environment secrets

---

github/enterprise_audit_log_test.go
github/orgs_audit_log_test.go
github/timestamp.go
github/timestamp_test.go

The GitHub Audit Log API introduced timestamps with millisecond granularity. We add support for these timestamps by first parsing the timestamp into a Unix timestamp and then checking to see if the generated timestamp is in the future. If the timestamp is in the future we re-parse it as a Unix timestamp in Milliseconds.
Tests were added to ensure that when the timestamp is 1 millisecond off that the granularity of the timestamp is preserved by milliseconds correctly being parsed.
Closes #1849
Signed-off-by: Brett Logan <lindluni@github.com>

Add Support For Millisecond Timestamps

---

example/tokenauth/main.go

When assisting someone with GitHub auth token issues, I realized that this example could be more useful if it printed out the rate limit information.

Improve tokenauth example as debugging tool

---

README.md
github/github.go
github/github_test.go

Fixes [1846](https://github.com/google/go-github/issues/1846)
1. Updated `README.md` to reflect that it is no longer Go 1.9 that we require, but instead we need a minimum of Go 1.13.
2. Replaced `reflect.DeepEqual` with `errors.Is` in all the affected tests.
3. Implemented `Is(error) bool` interface for all the required errors (`ErrorResponse`, `RateLimitError`, `AcceptedError` and `AbuseRateLimitError`). All the individual fields are directly compared. However, for the `*http Response` field, only `StatusCode` is being compared. If the other fields of the `http.Response` struct need to be compared, please let me know.

Update error handling as per Go 1.13 guidelines

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_releases.go
github/repos_releases_test.go

support the new `discussion_category_name` field when creating/updating a release.
refs https://github.blog/changelog/2021-04-06-releases-support-comments-and-reactions-with-discussion-linking/
refs https://docs.github.com/en/rest/reference/repos#create-a-release
refs https://github.com/goreleaser/goreleaser/issues/2161

feat: support new release discussions feature

---

github/github-accessors.go
github/github-accessors_test.go
github/issues_comments.go
github/issues_comments_test.go

Revert "Fix: Remove Sort & Direction Fields From IssueListCommentsOptions"

---

github/apps_installation.go
github/apps_installation_test.go

The preview `application/vnd.github.baptiste-preview+json` ensures that the field `"is_template": false` is part of the repository response of the Apps Service.

Apps-Service: Add baptiste-preview to ListRepos and ListUserRepos

---

github/apps_manifest.go
github/apps_manifest_test.go

Apps manifest are now out of preview and uses mediaTypeV3:
https://docs.github.com/en/rest/reference/apps#create-a-github-app-from-a-manifest

Remove obsolete apps manifest preview custom header

---

github/actions_runners.go
github/github-accessors.go
github/github-accessors_test.go

See https://github.com/google/go-github/issues/1861
When using Git Hub Enterprise APIs a temp_download_token is included when querying runner downloads via the API.
This PR updates the response structure to include the necessary token and SHA checksum.
```
>:~$ curl -k -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" https://HOST/api/v3/orgs/actions-sauron/actions/runners/downloads
[
{
"os": "osx",
"architecture": "x64",
"download_url": "https://HOST/_services/pipelines/_apis/distributedtask/packagedownload/agent/osx-x64/2.277.1",
"filename": "actions-runner-osx-x64-2.277.1.tar.gz",
"temp_download_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJ...",
"sha256_checksum": "f1fa173889dc9036cd5294..."
},
{
"os": "linux",
"architecture": "x64",
"download_url": …
```

Add download token and sha to ListRunnerApplicationDownloads

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/teams.go

This PR addresses https://github.com/google/go-github/issues/1863 by adding a Permissions field to the Team type.

Add permissions to teams

---

github/repos.go

Fix typo in repos.go

---

github/apps_test.go

The use of `cmp.AllowUnexported` stuck out to me as code smell when reviewing #1875, but since the weird comparison was already there, I decided to leave it alone in that PR.
This was a very weird test method, since it doesn't follow the pattern of the rest of go-github for comparing POST request bodies, and as a result makes things way more complicated than they need to be.
This eliminates the `GetReadWriter` and `GetReadCloser` funcs.  There was [discussion in #1238](https://github.com/google/go-github/pull/1238/files#r313185975) about these potentially being general purpose funcs, but they never ended up being used beyond this one method, nor should they ever be necessary I don't think.  Even though these were exported funcs, because they were only defined in the test package, this …

compare decoded go struct for request body

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

This option, when set to true, the created repository will get files
from all the branches, not just the default branch.
See [create-a-repository-using-a-template][1] for more information.
[1]: https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template

repos: add option include_all_branches to template repo request

---

github/actions_secrets.go
github/actions_secrets_test.go

Add ListOptions to ListSelectedReposForOrgSecret

---

github/gen-accessors.go
github/gen-stringify-test.go
github/with_appengine.go
github/without_appengine.go
test/integration/activity_test.go
test/integration/audit_log_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/issues_test.go
test/integration/misc_test.go
test/integration/pulls_test.go
test/integration/repos_test.go
test/integration/users_test.go

https://tip.golang.org/doc/go1.17
Fixes #1890

support go1.17 build constraint syntax

---

github/actions_secrets_test.go

* PublicKey
* Secret
* Secrets
* EncryptedSecret
* SelectedReposList
Helps with issue : #55

Add test cases for JSON resource marshalling

---

github/github-accessors.go
github/github-accessors_test.go
github/issues_timeline.go

The Timeline Events API can return a `reviewed` event object when listing events for a pull request. One of the properties of [this object](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#reviewed) is `state`, which tells you the state of a submitted review.
The values `state` can have are:
- `commented`
- `changes_requested`
- `approved`
This PR adds this field to the `Timeline` struct defined in `issues_timeline.go` to make it possible to tell the state of a review when listing pull request events.

Parse 'reviewed' event object 'state' property

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/pulls.go

@gmlewis
I have added the changes required for issue #1881
I had run go test ./... before and after the changes. I could see all test cases passing in /github folder.
Thanks,

Add auto_merge field in PullRequest struct

---

github/activity.go
github/activity_test.go
github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/github_test.go
update-urls/main.go

Some fields were defined inline as anonymous structs.
This made it tedious to use these structs in testcases, because
the anonymous type needed to be redefined (incl the exact same JSON
tags) whenever it was assigned. 
Using anonymous struct also does not scale well when the struct changes.
For example when a field is added to an anonymous struct, every place
where the anonymous struct is assigned must also be changed.
Another advantage of using regular types is that accessors  will be
generated automatically and can be used instead of having to manually
check for nil values when accessing the struct fields.
Define the types as regular structs instead.
-----------
**PR Status:** PR is finished but I noticed that my company hasn't signed the CA yet. As soon as it is done, I'll transition …

define struct types instead of using anonymous structs

---

github/actions_artifacts_test.go
github/actions_workflow_jobs_test.go
github/github_test.go
github/repos.go
github/repos_contents_test.go
github/repos_test.go
test/integration/repos_test.go

Adds a new followRedirects param for handling redirects on the **GetBranch** API. If redirected, the `response.Request.URL` will contain the redirected URL.
As per: #1895.

Modify GetBranch to handle redirects

---

github/event_types_test.go

Added test cases for following change events :
* ProjectChange
* ProjectCardChange
* ProjectColumnChange
Relates to : #55

Add test cases for JSON resource marshaling

---

github/github.go
github/github_test.go

Fixes https://github.com/google/go-github/issues/1899.

Enable `Client.RateLimits` to bypass the rate limit check

---

github/messages.go
github/messages_test.go

* Handled MIME parameters in Content-Type Header
* Added test-cases to support the changes
Fixes: #1874

Handle MIME parameters in Content-Type Header

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go

Fixes #1945 - added a new field for `Protection` struct
to parse `required_conversation_resolution` JSON field
from API response for branch protection rules.
Updated test.

Add RequiredConversationResolution protection field

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

For #1945 - added a new field for ProtectionRequest struct
to marshall as required_conversation_resolution JSON field
to API request for branch protection rules.

Add RequiredConversationResolution ProtectionRequest field

---

github/checks.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go

This adds the `created_at` and `updated_at` fields to `CheckSuite`. See [REST API docs](https://docs.github.com/en/rest/reference/checks#create-a-check-suite--code-samples).

Add missing CreatedAt and UpdatedAt fields to CheckSuite

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/github.go
github/github_test.go
github/orgs_hooks_deliveries.go
github/orgs_hooks_deliveries_test.go
github/repos_hooks_deliveries.go
github/repos_hooks_deliveries_test.go

Resolves #1933
To make this PR minimal as possible for ease of reviewing, I intentionally included only four APIs related to the webhook deliveries API:
- Listing repository hook deliveries
- Getting a specific repository hook delivery
- Listing organization hook deliveries
- GEtting a specific organization hook delivery
That being said, the following methods aren't covered in this PR. If you like, I'd gladly submit subsequent PRs to add all of them.
- Trigger redelivery of a hook delivery
- ~~List/get/redelivery for organizational webhooks~~
Note that changes on the following files are completely generated by running `go generate` as documented in your guide, so you won't need to read them that carefully.
- `github/github-accessors_test.go`
- `github/github-accessors.go`
FWIW, you can …

Add support for listing and getting repository/organization webhook deliveries

---

github/messages.go
github/messages_test.go

This pull request introduces the changes described in #1944.
- Expose the constants `sha1SignatureHeader`, `sha256SignatureHeader`, `eventTypeHeader` and `deliveryIDHeader`
- Introduce a new public function called `ValidatePayloadFromBody` to read the body directly from an `io.Reader` rather than a `http.Request`.
The changes described enables the possibility to use `go-github` even with http libraries like `fiber` or `fasthttp`.
Example A:
```go
app.Get(func(ctx *fiber.Ctx) error {
signature := ctx.Get(github.SHA256SignatureHeader)
if signature == "" {
signature = ctx.Get(github.SHA1SignatureHeader)
}
payload := ctx.Body()
err := github.ValidateSignature(signature, payload, mySecretToken)
// ...
event, err := github.ParseWebHook(ctx.Get(github.EventTypeHeader), payload)
// ...
})
``` …

Expose event message headers, introduce a new way to read the body from an `io.Reader`

---

github/actions_runner_groups.go
github/actions_runner_groups_test.go
github/github-accessors.go
github/github-accessors_test.go

Adds allows_public_repositories to request bodies of the
CreateRunnerGroup as well as UpdateRunnerGroup methods for github
actions.
This allows us to set the allows_public_repositories flag even if it is
not yet properly documented see https://github.com/github/docs/issues/8209
That flag controls if public repos can use runners of this group.
If it is disabled(default) even public repos that are added to the
selected_repositories list cannot use runners of this group.
With this change we can now set this properly and thus use runner groups
created by go-github also for public repos.
Fixes #1996

Add allows_public_repositories to actions_runner_group
