github/actions_runners.go
github/actions_runners_test.go

This commit adds the abillity to add one or more repositories to the
list of enabled repositories for github actions on org level.
It also adds the abillity to remove them from this list.
With this change we can now enable and disable repos to use github actions on org level.
The used endpoints for this are:
https://docs.github.com/en/rest/reference/actions#set-selected-repositories-enabled-for-github-actions-in-an-organization
https://docs.github.com/en/rest/reference/actions#disable-a-selected-repository-for-github-actions-in-an-organization
fixes #1995

Add methods to add and remove repos for actions on org level

---

github/pulls_reviews_test.go

- PullRequestReview
- PullRequestReviewRequest
- DraftReviewComment
- PullRequestReviewDismissalRequest
Helps with issue: #55

 Add test cases for JSON resource marshaling

---

github/github.go
github/github_test.go

Add Client method

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_statuses.go

I've added the `AvatarURL` field to `RepoStatus` to bind the `avatar_url` field from the response. Thanks.
[> Github document (combined status)](https://docs.github.com/en/rest/reference/repos#get-the-combined-status-for-a-specific-reference)

Add avatar_url field to RepoStatus

---

README.md

Small mention to the `go-github-mock` repo in README. I didn't really know how to word it so kept it brief.

Add mention to go-github-mock in README

---

github/apps_manifest.go
github/apps_manifest_test.go
github/github-accessors.go
github/github-accessors_test.go

Add the `slug` field from the [GitHub manifest response](https://docs.github.com/en/rest/reference/apps#create-a-github-app-from-a-manifest) to `AppConfig`

Add Slug field to AppConfig in manifest workflow

---

github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github-accessors_test.go

The deprecated field `open` got changed to `state` to hold 3 different values (`open, dismissed, and fixed`)

Fix deprecated field

---

github/actions_secrets.go

Fix #2035 - Allow empty selected_repository_ids for SetSelectedReposForOrgSecret

Allow empty selected_repository_ids for SetSelectedReposForOrgSecret

---

github/doc.go

It looks like the links to GitHub rate limiting and conditional requests docs are now redirected to the docs home page.
It seems like these sections have moved to `Overview > Resources in the REST API`, this PR updates the links accordingly

Fix GitHub docs links

---

github/github.go

This comment probably became out of date over time, as things were moved and renamed. Update it to the current naming.

Update Cursor comment to reference an existing method

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/users_gpg_keys.go

This pull request adds the `raw_key` field to `GPGKey`. This field is exposed by github.com, for example: https://api.github.com/users/brekelj1/gpg_keys

Add raw_key field to GPGKey struct

---

.github/workflows/linter.yml
.golangci.yml
github/activity_notifications.go

This PR doesn't fix the identified problem raised by the analysis

Set up workflow for golangci

---

.github/workflows/tests.yml

Signed-off-by: Matthieu MOREL <mmorel-35@users.noreply.github.com>

chore(ci) : cache go-build folders

---

.github/workflows/tests.yml
update-urls/go.mod
update-urls/go.sum
update-urls/main.go
update-urls/main_test.go

Fix update-urls unit tests broken by #1875

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_autolinks.go
github/repos_autolinks_test.go

Add support for autolinks

---

.gitignore
github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/scim.go
github/scim_test.go

- Implement SCIM Service
API Docs: https://docs.github.com/en/rest/reference/scim#list-scim-provisioned-identities--parameters
Fixes: #2030.

Implement SCIM

---

github/actions_workflow_runs.go

Adds the `created` filter field to ListWorkflowRunsOptions.
Changelog post: https://github.blog/changelog/2021-09-02-github-actions-filter-workflow-runs-by-created-date/

Add created field to ListWorkflowRunsOptions

---

github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/repos_community_health.go
github/repos_community_health_test.go

Changes to more closely align with the latest version of the docs for the community profile API at: https://docs.github.com/en/rest/reference/repos#community
- Adds CodeOfConductFile to the list of community health files
- Adds SPDXID and NodeID fields to metrics (used by license health file)
- Adds Description and Documentation fields
- Adds ContentReportsEnabled field (returned by organization owned repositories)
- Updates tests to include new fields and more closely match the response shown in the docs example
- Removes the graduated black-panther preview header for the community health api

Update repo community profile API

---

github/actions_runner_groups.go
github/actions_runner_groups_test.go

Fix #2085 . Add List Options for ListRepositoryAccessRunnerGroup to support fetching full list of access repositories. Also update unit tests accordingly.

Add List Options for ListRepositoryAccessRunnerGroup

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/go.sum
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/go.mod
example/newreposecretwithxcrypto/go.sum
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

This PR is in preparation for release v39.0.0.
* #2086 
* https://github.com/google/go-github/pull/2042
* https://github.com/google/go-github/pull/2043
* https://github.com/google/go-github/pull/2045
* https://github.com/google/go-github/pull/2020
* https://github.com/google/go-github/pull/2054
* https://github.com/google/go-github/pull/2049
* https://github.com/google/go-github/pull/2058
* https://github.com/google/go-github/pull/2065
* https://github.com/google/go-github/pull/2074
* https://github.com/google/go-github/pull/2046
* https://github.com/google/go-github/pull/2062
* https://github.com/google/go-github/pull/2061
* https://github.com/google/go-github/pull/2038
* …

Bump version of go-github library to v39

---

github/actions_workflow_runs.go
github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Add common Installation field to webhook events

---

github/event.go
github/event_types.go
github/github-accessors.go
github/github-accessors_test.go
github/messages.go
github/messages_test.go
github/repos.go

Add BranchProtectionRuleEvent

---

github/actions_workflow_jobs.go
github/event_types.go

This adds support for new `workflow_job` webhook events' `labels` field announced at https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/.
I've already using go-github with this patch for weeks while [participating in the alpha test](https://github.com/actions-runner-controller/actions-runner-controller/issues/697) of the new webhook event. So I'm pretty confident this works. But I'd do anything I can do if necessary!

Add support for workflow_job event's `labels` field

---

AUTHORS
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs_packages.go
github/orgs_packages_test.go
github/packages.go
github/packages_test.go
github/users_packages.go
github/users_packages_test.go

Adds support for [Packages API](https://docs.github.com/en/rest/reference/packages) through expansion of Users and Organization Services.
Would resolve #2075

Add support for Packages API

---

github/orgs_packages_test.go
github/users_packages_test.go
scrape/apps_test.go
update-urls/main.go
update-urls/main_test.go

#2104 added some linter flags that caused in-flight PRs to fail testing after being merged.
This PR fixes those errors.

Fix new golangci-lint errors

---

.github/workflows/tests.yml

Bump CI version of Go to test versions 1.17.x and 1.16.x

---

github/apps_hooks.go
github/apps_hooks_test.go
github/doc.go
github/github-accessors.go
github/github-accessors_test.go
github/orgs_audit_log.go

This adds support for two Apps API endpoints (see #2095)
- [Get a webhook configuration for an app](https://docs.github.com/en/rest/reference/apps#get-a-webhook-configuration-for-an-app)
- [Update a webhook configuration for an app](https://docs.github.com/en/rest/reference/apps#update-a-webhook-configuration-for-an-app)
Both endpoints require authentication as an app (with a JWT), which can be dealt with by the underlying transport.
A few notes:
- I reused / extended the `HookConfig` struct which was defined in `orgs_audit_logs.go`, since it represents the same object.
- The `InsecureSSL` field of the struct is a `*string`. However, GitHub only returns `"0"` or `"1"` (insecure SSL disabled / enabled), so I think it'd be more user-friendly to use a `*bool`, and write some logic so that …

Add support for apps webhook config endpoints

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go

Fixes https://github.com/google/go-github/issues/2115
This is an optional field present in most of the events payload. See:
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

event_types.go: add Organization to PushEvent and IssueCommentEvent

---

github/github.go

documentation
API preview headers (media types) are used to enable new features in GitHub API.
These media types will be added to the API request as headers and used to enable particular features on GitHub API that are still in preview.
After some time, specific media types will be promoted (to a "stable" state).
From then on, the preview headers are not required anymore to activate the additional feature on GitHub.com's API. However, this API header might still be needed for users to run a GitHub Enterprise Server on-premise.
It's not uncommon for GitHub Enterprise Server customers to run older versions which would probably rely on the preview headers for some time.
While the header promotion is going out for GitHub.com, it may be some time before it even arrives in GitHub Enterprise …

Comment to keep API preview headers around

---

github/issues.go
github/issues_test.go

Add new RemoveMilestone method on IssuesService

---

github/repos.go
github/repos_test.go

Add support for rename a branch: https://docs.github.com/en/rest/reference/repos#rename-a-branch
Fixes: https://github.com/google/go-github/issues/2118

Add RenameBranch support

---

github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github-accessors_test.go

Add a method to upload Code Scanning Sarif results to GitHub

Upload Code Scanning Sarif results to GitHub

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

* #2127
* #2126
* #2128
* #2129
* #2131
* #2133
* #2141
* #2193
* #2195
* #2119
* #2197
* #2165
plus several test- or documentation-only changes.

Bump version of go-github library to v40

---

github/reactions.go
github/reactions_test.go

Support for creating reaction for a release

---

github/billing.go
github/billing_test.go

fixes #2203
**Changes:**
Changed the type from int to float64 for EstimatedPaidStorageForMonth in billing.go and updated the testcases for it.
New to this repo. Please do let me know if any updates needed.

Change StorageBilling.EstimatedPaidStorageForMonth from int to float64

---

github/github.go
github/github_test.go

* Some Github APIs use `before`/`after` for pagination, rather than `page` or `cursor` pagination. Parse these response values into the github `Response`
* For example, the Organizations GetAuditLog (Enterprise Cloud) https://docs.github.com/en/rest/reference/orgs#get-the-audit-log-for-an-organization
With this change, pagination can be performed
```go
auditParams := &github.GetAuditLogOptions{}
for {
entries, resp, err := client.Organizations.GetAuditLog(ctx, "myorg", auditParams)
if err != nil {
return err
}
if resp.After == "" {
break
}
auditParams.After = resp.After
}
```
Rel: https://github.com/google/go-github/issues/1848

Parse Before/After Links into Response

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go

This Pull request Adds a new function to delete workflows run from workflow history. The same functionality as this button:
I cannot reference the documentation in the function comment because is missing the endpoint in the docs

Add function to delete a workflow run by ID

---

github/billing.go
github/billing_test.go
github/github-accessors.go
github/github-accessors_test.go

New Method for fetching active committers for an Organization
https://docs.github.com/en/rest/reference/billing#get-github-advanced-security-active-committers-for-an-organization

Add active committers API implementation

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/go.sum
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/go.mod
example/newreposecretwithxcrypto/go.sum
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

* #2205
* #2196
* #2154
* #2206
* #2207
* #2135
* #2208

Bump version of go-github library to v41

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/projects.go
github/projects_test.go

This fixes https://github.com/google/go-github/issues/2110
- fixed ProjectOptions: Public -> Private (according to API doc: https://docs.github.com/en/rest/reference/projects#update-a-project)
- added **OrganizationPermission** and **Private** fields to Project struct, which presents during response on Organization Project.
I've done UATs as well, and all API calls looked good:
- Update Org Project with new private field
- Get Org Project (OrganizationPermission and Private presents as expected)
- Get Repo Project (OrganizationPermission and Private not presents as expected)
- Get User Project (OrganizationPermission and Private not presents as expected)

ProjectOptions (public to private) & Project struct (org related fields) fixes 

---

github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github-accessors_test.go

Add ListAnalysesForRepo and GetAnalysis to CodeScanningService, including unit tests.

Add CodeScanningService.ListAnalysesForRepo and CodeScanningService.GetAnalysis

---

github/repos.go
github/repos_test.go

Handle protection status errors for unprotected branches

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go
scrape/testdata/access-restrictions-disabled.html
scrape/testdata/access-restrictions-enabled.html

Although it isn't yet documented at github, the BranchProtectionRuleEvent
includes an `installation` field which is crucial for letting Apps reacting to it
to authenticate their requests.
This PR adds that field the event type, along with an accessor for it.
Fixes: #2214.

Add BranchProtectionRuleEvent Installation field

---

github/pulls.go

1. Correct the statement that results include open and closed PRs by default, when it is only `open` by default, per https://github.com/google/go-github/blob/ff33a554ef2c24c1710238b69942fe51e70d89da/github/pulls.go#L120-L123 
2. Correct the URL for the Github API doc, per https://github.com/google/go-github/issues/2227

Update comment on ListPullRequestsWithCommit API

---

github/doc.go
github/github.go

It looks like GitHub is now designating "abuse rate limits" as "secondary rate limits": https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits
The URL returned in the error response also changed, so this PR updates it so that these errors can properly be caught again.
This PR also includes a suggestion to update the main documentation page to mention this error type, to make it more discoverable.

Fix secondary rate limits URL and improve related documentation

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

Add Changes field to RepositoryEvent

---

.gitignore
github/apps_hooks.go
github/apps_hooks_deliveries.go
github/apps_hooks_deliveries_test.go

Add app hook deliveries API

---

github/github-accessors.go
github/github-accessors_test.go
github/teams.go
github/teams_test.go

Fixes: #2213 .
https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#external-groups

Add support for External Groups

---

.gitignore

Hi reviewers:
I updated the `.gitignore` to ignore the `.go-version` file in this PR.
If merged, it's easy to manage different go version locally for the **goenv** user.
Please help to review it. Thanks!
Reference
https://github.com/syndbg/goenv/blob/master/COMMANDS.md#goenv-local

Update .gitignore for ignoring goenv .go-version file

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/teams.go

When performing an edit of a team, the html_url is required `invalid: [status.html_url: Required value]`
However, that field is missing from the struct, so the previous GET does not marshal this data (even though it is included in the response)
```
gh api orgs/testing-org/teams/test-secret-team
{
"name": "test-secret-team",
"id": 152,
"node_id": "hmmm==",
"slug": "test-secret-team",
"description": "",
"privacy": "secret",
"url": "https://github.myorg.com/api/v3/organizations/63/team/152",
"html_url": "https://github.myorg.com/orgs/testing-org/teams/test-secret-team",
"members_url": "https://github.myorg.com/api/v3/organizations/63/team/152/members{/member}",
"repositories_url": "https://github.myorg.com/api/v3/organizations/63/team/152/repos",
}
```
Signed-off-by: Jake Plimack …

add team.html_url

---

github/checks.go
github/checks_test.go
github/github-accessors.go
github/github-accessors_test.go

Update ListCheckRunsOptions with new field AppID

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_hooks_deliveries.go
github/repos_hooks_deliveries_test.go

Change type of HookDelivery.InstallationID to Int64.

---

github/users_packages.go
github/users_packages_test.go

Here is the detail of the problem: #2251.

Add pagination options to list all package versions

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/go.mod
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

* #2111 
* #2235
* #2250 
* #2212
* #2176
* #2210
* #2092 
* #2109 
* #2216 
* #2218
* #2219
* #2224
* #2228
* #2229
* #2233 
* #2226 
* #2217 
* #2238
* #2237
* #2242
* #2244
* #2236 
* #2240
* #2221
* #2230 
* #2248

Bump version of go-github library to v42

---

github/actions_workflows.go

go-github documentation on GitHub Actions Workflow parameters indicated
support for branch, tag or SHA, while the official docs indicated only
branch and tag are supported (which was verified by attempting to pass a
SHA to the workflow and seeing it ignored). This small changeset simply
aligns the documentation.

Update docs for CreateWorkflowDispatchEventRequest.Ref

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_pages.go

Closes #2261 
This change introduces 2 additional parameters provided by the GitHub API to the PagesUpdate type, `Public` and `HTTPSEnforced`. 
Note: I had to open a new PR because the author email for one of the commits in the first PR did not match the email associated with my CLA.

Add support for additional PagesUpdate parameters

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go

Attempt to solve #2274.
From my own experimentation, I discovered that there's two ways that this `Checks` field can be used to update the required status checks for a protected branch:
- [update branch protection](https://docs.github.com/en/rest/reference/branches#update-branch-protection) -> via the `ProtectionRequest` -> `RequiredStatusChecks` -> `RequiredStatusCheck` struct, in this API call we must provide either one of `Checks` or `Contexts` (the other must be `nil`) in `RequiredStatusChecks` to successfully update a branch protection. If you provide both or neither, you will get an `Invalid Request` error.
- [update status check protection](https://docs.github.com/en/rest/reference/branches#update-status-check-protection) -> via the `RequiredStatusChecksRequest` -> …

Add checks field to RequiredStatusChecks

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

Add Repo and Org fields to DeployKeyEvent

---

example/listenvironments/main.go
github/repos_environments.go
github/repos_environments_test.go

Closes #2257 
This PR introduces an EnvironmentListOptions parameter for the ListEnvironments method.
Tests have also been updated to reflect the changes and an example has been added to the example directory.

Add list options support for environments

---

github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/secret_scanning.go
github/secret_scanning_test.go

This PR adds support for the [Secret Scanning API](https://docs.github.com/en/rest/reference/secret-scanning). Includes all endpoints and structures listed on the API documentation.
Closes #2278

Add support for the secret scanning API

---

github/billing.go
github/billing_test.go

Fixes #2283 
GitHub Actions returns total_paid_minutes_used as floating point value.
The Implementation should accept this floating point value as float64.
```bash
curl -H "Authorization: Bearer <TOKEN>" \
-H "Accept: application/vnd.github.v3+json"  \
https://api.github.com/orgs/{org}/settings/billing/actions
```
```json
{
"total_minutes_used": 1234,
"total_paid_minutes_used": 3959.0,
"included_minutes": 3000,
"minutes_used_breakdown": {
"UBUNTU": 1234,
"MACOS": 1234,
"WINDOWS": 1234
}
}
```

GitHub Actions Billing returns total_paid_minutes_used as float64

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/github-accessors.go
github/github-accessors_test.go

Add GetWorkflowRunAttempt

---

github/github-accessors.go
github/github-accessors_test.go
github/misc.go
github/misc_test.go

As described in https://docs.github.com/en/rest/reference/meta.

Add APIMeta fields related to SSH keys

---

github/github.go
github/github_test.go

The recommended cache, https://github.com/gregjones/httpcache, returns
an X-From-Cache: 1 header whenever it serves a response from the cache.
Cached responses might include (possibly stale) ratelimit headers, which
we would've already processed in the past.

Don't update the ratelimits if we got a response from a cache

---

github/checks.go
github/checks_test.go
github/github.go

Reverts google/go-github#1636
Fixes #2300

Revert "Remove graduated GitHub v3 API preview header"

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/go.mod
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

* #2258 
* #2284 
* #2289 
* #2254
* #2256
* #2259
* #2263
* #2266
* #2269
* #2270 
* #2271
* #2272
* #2276
* #2280
* #2281
* #2282
* #2290
* #2293
* #2273
* #2301
* #2303

Bump version of go-github library to v43

---

example/actionpermissions/main.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs_actions_allowed.go
github/repos_actions_allowed.go
github/repos_actions_allowed_test.go
github/repos_actions_permissions.go
github/repos_actions_permissions_test.go

👋  Hello there!
Couldn't find a PR for it yet so added functionality requested in https://github.com/google/go-github/issues/2297
Sorry if I pushed myself before @cfarrend in doing it but I will need the changes.
Went through the [contributing guide](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) and also added an example to test the change end2end.
Thanks everyone!
Fixes: #2297.

Add support for setting actions permissions on a repository

---

github/actions_artifacts.go
github/actions_workflow_jobs.go
github/actions_workflow_runs.go
github/github.go
github/repos.go
github/repos_contents.go
github/repos_contents_test.go

This PR removes code duplication as detected by  `golangci-lint`.

Remove code duplication

---

github/gen-stringify-test.go
github/github-stringify_test.go

This PR adds missing structs and slices to the stringify tests for better test coverage.

Improve stringify test coverage

---

github/event.go
github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/messages.go
github/messages_test.go
github/pulls_threads.go
github/pulls_threads_test.go
github/repos_hooks_deliveries_test.go

Add support for the pull request review thread event

---

.github/workflows/linter.yml
.github/workflows/tests.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Restrict permissions for GitHub actions

---

github/github-accessors.go
github/github-accessors_test.go
github/org_custom_roles.go
github/org_custom_roles_test.go

Fixes: #2327 .
Thanks for this opportunity.

Add support to list custom roles for organizations

---

README.md
example/actionpermissions/main.go
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/go.mod
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/go.sum
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

* #2032
* #2308
* #2305
* #2311
* #2314
* #2310
* #2313
* #2316
* #2315
* #2321
* #2320
* #2318
* #2323
* #2322
* #2326
* #2332
* #2331
* #2333
* #2334
* #2336
* #2343
* [example: update go modules for some examples](https://github.com/google/go-github/commit/bbfb1057a87ca1418ba540fad198db1b25ff0174) https://github.com/google/go-github/commit/bbfb1057a87ca1418ba540fad198db1b25ff0174
* [fix gofmt issue in newreposecretwithxcrypto](https://github.com/google/go-github/commit/97b5d957fa50c8b2e1a4372930f0954815fbb19a) https://github.com/google/go-github/commit/97b5d957fa50c8b2e1a4372930f0954815fbb19a
* [run golangci-lint on all modules](https://github.com/google/go-github/commit/c071ded072a4f6aa9b696 …

Bump version of go-github library to v44

---

README.md

Related: https://github.com/google/go-github/issues/2347
This PR adds a "Webhooks" section to the `README.md` and provides an example snippet.

Add a "Webhooks" section to the README.md

---

github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github-accessors_test.go

Provide functionality for querying Code Scan Alerts by Github Org. As well as support a Repository field within each Alert object.

Add support for list Code Scan Alerts by Org

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go

Fixes https://github.com/google/go-github/issues/2344
Add support to rerun all failed jobs or a single job from a workflow run
https://docs.github.com/en/rest/actions/workflow-runs#re-run-failed-jobs-from-a-workflow-run
https://docs.github.com/en/rest/actions/workflow-runs#re-run-a-job-from-a-workflow-run

Add RerunFailedJobsByID and RerunJobByID

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Reference: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_vulnerability_alert

Add missing Sender field in RepositoryVulnerabilityAlertEvent

---

github/actions_runner_groups.go
github/actions_runner_groups_test.go

Fixing https://github.com/google/go-github/issues/2328 
Support `visible_to_repository` query parameter in `ListOrganizationRunnerGroups`.

Support query parameter `visible_to_repository` in ListOrganizationRunnerGroups

---

github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/github_test.go

Fixes: https://github.com/google/go-github/issues/2339
I added fields to `RateLimits` struct to get rate limits other than `core` and `search`
Since there is no documentation for `source_import`, `code_scanning_upload`, `actions_runner_registration`, and `scim`, I did not know which endpoints had the rate limit set, so I did not fix `category` function. 
https://github.com/google/go-github/blob/942d33d1d76e64a53d4d50ac0c95d54c907ba0e1/github/github.go#L1126-L1134

Add fields to RateLimits struct

---

github/checks.go
github/checks_test.go

Closes out https://github.com/google/go-github/issues/2357
Adds support for https://docs.github.com/en/rest/checks/runs#rerequest-a-check-run

Add ReRequestCheckRun

---

github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

This function was created based on the docs here: 
https://docs.github.com/en/rest/orgs/custom-roles#list-custom-repository-roles-in-an-organization
The docs incorrectly give the endpoint `https://api.github.com/organizations/ORGANIZATION_ID/custom_roles`.
When using this function, I get a 404. 
The correct endpoint for the custom_roles endpoint is `https://api.github.com/orgs/ORGANIZATION_ID/custom_roles` - and this is consistent with other github endpoints under orgs. I have raised a support ticket with github, but I would expect them to change the documentation, not the api endpoint.
Also changed the file names for consistency.

fix: correct endpoints for custom roles

---

README.md
example/actionpermissions/main.go
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/go.mod
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/go.sum
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

* #2329
* #2365
* #2337 
* #2340 
* #2358 
* #2364
* #2366
* #2367
* #2369
* #2370
* #2373

Bump version of go-github library to v45

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

See
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-common-properties
for the list of common fields.
I may have missed some - but gives better coverage for fields we were
missing before.
Signed-off-by: Billy Lynch <billy@chainguard.dev>

Add missing common event fields.

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/users.go

As a follow on from [this PR](https://github.com/google/go-github/pull/2379) - I also need to be able to access the `role_name` returned from the `Repositories.ListCollaborators` endpoint, and therefore have raised this PR to include the field in the user struct.

add rolename field to user struct

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs.go

This PR adds `MembersCanForkPrivateRepositories` field to `Organization` struct.

Add MembersCanForkPrivateRepositories field to Organization struct

---

github/github-accessors.go
github/github-accessors_test.go
github/issues.go

`state_reason` can be 'completed' or 'not_planned'.
I believe we let GitHub document these values, but let me know if you need me to modify this change. Thank you!
Fixes #2393.
/cc @gmlewis

Add state_reason to IssuesService.Edit 

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_pages.go
github/repos_pages_test.go

Support PagesSource as struct for update pages API

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_codeowners.go
github/repos_codeowners_test.go

This PR adds a new function `GetCodeownersErrors` to the `RepositoriesService` struct.
It adds support for the endpoint https://docs.github.com/en/rest/repos/repos#list-codeowners-errors as described in #2405

feat: add GetCodeownersErrors to RepositoriesService (#2405)

---

github/repos_contents.go

fixes #2427
This removes `omitempty` from `RepositoryContentFileOptions.Content` so that an empty `content` field can be passed in to generate empty files. Before, the `content` field was omitted, which caused the GitHub API to not accept the request as the field is required, even if it is empty.

Remove omitempty from Content field of RepositoryContentFileOptions

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go

Closes https://github.com/google/go-github/issues/2431

Add BypassPullRequestAllowances field

---

github/repos_lfs.go
github/repos_lfs_test.go
go.mod

Add ability to turn LFS on / off for repo

Add LFS control

---

github/search.go
github/search_test.go

Fix TextMatch Option doesn't work when search type is commits topics repositories or issues (#2385)
Fixes: #2385.

Add TextMatch custom header to other search type custom headers

---

github/event.go
github/messages.go
github/messages_test.go
github/repos_hooks_deliveries_test.go

Following up on the issue I created https://github.com/google/go-github/issues/2391. 
Let me know if there is anything missing or needs fixing. I just tried to follow the patterns from the other types.
Cheers,
emil
Fixes: #2391.

Add support for parsing code_scanning_alerts in webhooks

---

github/actions_secrets.go
github/actions_secrets_test.go
github/dependabot_secrets.go
github/dependabot_secrets_test.go

Change DependabotSecretsSelectedRepoIDs to []string

---

CONTRIBUTING.md
github/github.go
github/github_test.go

👋🏻 Hi there! I'm Tim, and I'm a Product Manager at GitHub. To allow us to better understand how people are using our API, it's super helpful to know what versions of SDKs like `go-github` they are using. 
At the moment, this package sends the `User-Agent` "go-github" in requests, but it doesn't say what version is being used.
This updates the `User-Agent` header to include that information, whilst still maintaining the ability for people to choose their own user agent by setting the `UserAgent` field on `Client`.
It also exports a `Version` constant, so people can use that information - for example to construct custom `User-Agent` headers.
This will mean that someone has to update the `Version` constant with the new version when it is incremented.
This is the first ever Go I've written, …

Include the version of `go-github` in `User-Agent` headers sent to the GitHub API

---

README.md

This adds a use case for endpoints that require JWT authentication

chore: Update README with additional auth use case

---

github/misc.go
github/misc_test.go

The Api and Web lists are returned from the `meta` API but still aren't supported in the Go library. This change exposes them in the same way as the other blocks which are returned. I'm working on a change in the GitHub Terraform provider to also support exposing these API/Web CIDRs so if this is all ok I can continue on with that change as well.

feature: adding api and web to meta api endpoint.

---

github/github.go
github/github_test.go
github/repos_hooks.go
github/repos_hooks_test.go

resolves #1265
_Note: PubSubHubbub seems to have been renamed WebSub when it was adopted by the W3C. So we use the name WebSub in our code.
ref https://github.com/pubsubhubbub/PubSubHubbub_
Added support for API to subscribe and unsubscribe to repository events via WebSub protocol.
GitHub API Docs: https://docs.github.com/en/rest/webhooks#pubsubhubbub
WebSub Docs: https://www.w3.org/TR/websub/
WebSub requires Content-Type to be application/x-www-form-urlencoded, so a new factory function has been added.
> This request MUST have a Content-Type header of application/x-www-form-urlencoded (described in Section 4.10.22.6 [[HTML5](https://www.w3.org/TR/websub/#bib-HTML5)])
> https://www.w3.org/TR/websub/#subscriber-sends-subscription-request

Add hooks support for WebSub (formerly PubSubHubbub) protocol

---

example/migrations/main.go
github/migrations_user.go
github/migrations_user_test.go

Fix for https://github.com/google/go-github/issues/2416

Add ListOptions for listing user migrations

---

README.md
example/actionpermissions/main.go
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/go.mod
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tagprotection/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
github/github.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go
update-urls/go.mod

* #2417
* #2438
* #2439
* #2397
* #2440

Bump version of go-github library to v47

---

github/repos_forks.go
github/repos_forks_test.go

Additional options name, default_branch_only for create a fork

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_autolinks.go
github/repos_autolinks_test.go
test/README.md
test/integration/github_test.go
test/integration/repos_test.go

Resolves #2449
* Adds `IsAlphanumeric` param to `AutolinkOptions` and `Autolink` structs of `github/repos_autolinks.go`
* Adds unit and integration tests for creating and getting autolinks for a repo
* Updates the `createRandomTestRepository` function in `test/integration/github_test.go` to look up the owner to create the repo under if a name isn't specified explicitly. Checks `GITHUB_OWNER` env var else falls back to user the oauth token belongs to.
* Removes redundant env var check from `init` function of `test/integration/github_test.go` because those checks already occur in the `test/integration/authorizations_test.go` file as needed. This made it easier for me to run integrations tests without setting env vars that weren't needed.
* `github/repos_autolinks_test.go`
* …

Add alphanumeric param to AutolinkOptions

---

github/repos_releases.go
github/repos_releases_test.go

This PR closes #2444 
According to the [GitHub v3 API reference](https://docs.github.com/en/rest/releases/releases#update-a-release),
`generate_release_notes` is not a recognised body parameter of the endpoint to update a release. If provided to
the API, it will have no effect.
This commit removes the setting of this parameter when updating a release, to avoid confusion in the effect of
setting this parameter.

Remove GenerateReleaseNotes from RepositoriesService.EditRelease

---

github/git_refs.go
github/git_refs_test.go

Closes #2453 
Most of the functions that deal with refs make sure to escape the special characters within the ref's name. The `UpdateRef` function doesn't seem to call the function that does this substitution of special characters with their encodings. This PR solves this problem and should now successfully patch remote refs if the `GetRef` function says the corresponding ref exists.

Escape special characters in ref name for update ref

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs.go

The [update an organization](https://docs.github.com/en/rest/orgs/orgs#update-an-organization) API has additional configurable fields that the Organization struct does not support:
WebCommitSignoffRequired
AdvancedSecurityEnabledForNewRepos
DependabotAlertsEnabledForNewRepos
DependabotSecurityUpdatesEnabledForNewRepos
DependencyGraphEnabledForNewRepos
SecretScanningEnabledForNewRepos
SecretScanningPushProtectionEnabledForNewRepos
Proposing adding these fields to enable them to be configurable with Organization.Edit

Add org struct fields

---

github/repos.go
github/repos_test.go

Always send 'checks' field when creating branch protection

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos.go
github/repos_test.go

The [Update a repository](https://docs.github.com/en/rest/repos/repos#update-a-repository) endpoint in the GitHub API has added an additional field to the security and analysis object to configure secret scanning push protection for a repository. Proposing adding additional fields in SecurityAndAnalysis struct to support configuration with Repositories.Edit
Closes:
#2475

Add SecretScanningPushProtection field to SecurityAndAnalysis struct

---

github/github-accessors.go
github/github-accessors_test.go
github/scim.go
github/scim_test.go

This PR adds return responses to `ListSCIMProvisionedIdentities` and `GetSCIMProvisioningInfoForUser`, as before it was not possible to get the output of those calls.
Fixes https://github.com/google/go-github/issues/2338

Return proper responses for SCIM provisioned identities

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go

Fixes issue https://github.com/google/go-github/issues/2485. The `From` values only seem to come in the variants of `string`, `bool` or `[]string`, so it's possible these objects could be consolidated into something more generic maybe.
e.g.
```go
type FromString struct {
From *string `json:"from,omitempty"`
}
type FromBool struct {
From *bool `json:"from,omitempty"`
}
type FromStringSlice struct {
From []string `json:"from,omitempty"`
}
```
This went against the current pattern so I made everything a `<Value>Changes` struct instead :D

Update ProtectionChanges to contain the remaining possible return values

---

scrape/apps.go
scrape/testdata/access-restrictions-disabled.html
scrape/testdata/access-restrictions-enabled.html

This PR changes the scrape app checks for oauth_application_policy  to reflect the latest class selectors in github.com/organizations/<org>/settings/oauth_application_policy

Rename 'whitelist' to 'allowlist' in oauth class selectors

---

AUTHORS
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/users_ssh_signing_keys.go
github/users_ssh_signing_keys_test.go

Introduce support for the new [SSH signing key endpoints](https://docs.github.com/en/rest/users/ssh-signing-keys) introduced into the REST API with the [introduction of SSH commit verification](https://github.blog/changelog/2022-08-23-ssh-commit-verification-now-supported/).

Add support for User SSH signing keys

---

.github/workflows/tests.yml

Fix use GITHUB_OUTPUT from deprecated set-output

---

github/enterprise_actions_runners.go
github/enterprise_actions_runners_test.go

This change adds ListRunnerApplicationDownloads() to the Enterprise service.
Fixes: #2495
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>

Add enterprise list runner applications download

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

Create custom role APIs

---

README.md
example/actionpermissions/main.go
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/go.mod
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tagprotection/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
github/github.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go
update-urls/go.mod

* #2474
* #2473
* #2472
* #2476
* #2484
* #2486
* #2488
* #2482
* #2492
* #2496
* #2494
* #2498

Bump version of go-github to v48

---

github/teams_test.go

Hi @gmlewis, I have added test case for ExternalGroupMember. So, pls accept my PR for Hackoctober fest contribution.
Helps: #55.

Add test case for JSON resource marshaling

---

github/repos_traffic_test.go
github/search_test.go

Hi creator,
Added test cases for JSON Resources :
CommitResult
Helps: https://github.com/google/go-github/issues/55
I have followed all the guidelines to contribute to this repository.
Please revert in case of any changes are needed.
I am a first-time contributor to Hackoctober, It will be a great help if u can encourage me & accept my contribution.

Add test case for JSON resource marshaling 

---

github/code-scanning.go
github/code-scanning_test.go

Fixes https://github.com/google/go-github/issues/2511

Add support for cursor pagination in AlertListOptions

---

github/code-scanning.go
github/github-accessors.go
github/github-accessors_test.go

Adds new field `dismissed_comment` for Code Scanning.

Code Scanning: add new field for dismissed comment

---

github/dependabot_alerts.go
github/dependabot_alerts_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github.go

This add support for reading dependabot alerts: https://docs.github.com/en/rest/dependabot/alerts
I added the `First` and `Last` parameters to the `ListCursorOptions`. It seems to replace the `PerPage` parameter.

Add support for Dependabot alert endpoints

---

github/actions_runner_groups.go
github/actions_runner_groups_test.go
github/github-accessors.go
github/github-accessors_test.go

Support workflow restrictions in actions_runner_groups

---

github/issues_timeline.go

The `committed` events from the timeline API can have a `parents` field containing the parent commits:
```json
"parents": [
{
"sha": "29480ba555d614487fddba278d32d19102e86527",
"url": "https://api.github.com/repos/google/go-github/git/commits/29480ba555d614487fddba278d32d19102e86527",
"html_url": "https://github.com/google/go-github/commit/29480ba555d614487fddba278d32d19102e86527"
}
],
```
This is also documented on the `issue` event payload: https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#event-object-properties-7

Add parents field to timeline events

---

github/orgs_packages.go

Update the GitHub docs url for PackageGetAllVersions to include the correct anchor.

Update doc URL for PackageGetAllVersions

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

Fixes https://github.com/google/go-github/issues/2574 , and it is mostly a direct, if barebones, implementation of the plan ideated there. Adding references to `LockBranch` and `AllowForkSyncing`. References to `RequireLastPushApproval` were added in cb24cabfacd4bff06727d5b3acea48ba56e5f690 . There might be some changes left to do.

Add LockBranch and AllowForkSyncing to repos.go

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/issues.go

Adds new field `state_reason` for GitHub Issue struct.
reference on the field: https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue

Add new field for issue state reason

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_actions_access.go
github/repos_actions_access_test.go

This PR adds support for the following endpoints and closes #2575:  
[`GET` `/repos/{owner}/{repo}/actions/permissions/access`](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/permissions#get-the-level-of-access-for-workflows-outside-of-the-repository)  
[`PUT` `/repos/{owner}/{repo}/actions/permissions/access`](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/permissions#set-the-level-of-access-for-workflows-outside-of-the-repository)

Add support for repository actions access level / permission

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_releases.go
github/repos_releases_test.go

Fixes: #2593
This adds support for the `make_latest` parameter added to the GitHub repositories API for setting explicit releases.
https://github.blog/changelog/2022-10-21-explicitly-set-the-latest-release/
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release

Add MakeLatest parameter to support explicitly setting latest release

---

AUTHORS
github/repos_forks.go
github/repos_forks_test.go

Change create fork options from url param to body param

---

README.md
github/github.go
github/github_test.go

Fixes: #2580.
@willnorris - please see if you agree with this approach for supporting the new GitHub v3 API versioning mechanism.
My thought is that when they add breaking API changes, that we will continue to support them, but will now add the `WithVersion` option to each request that needs it.

Support new GitHub v3 API calendar-based versioning

---

github/repos.go

This pull request simply fixes the link of the Get method in the RepositoriesService.

Fix GitHub docs URL for get repository API

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

Currently when trying to load in protection an error is thrown due to a data structure mismatch resulting in errors:
```bash
json: cannot unmarshal object into Go struct field Protection.lock_branch of type bool 
json: cannot unmarshal object into Go struct field Protection.allow_fork_syncing of type bool
```
This is due to them using an enabled field which the current structure does not understand. This change introduces the relevant structure and has been tested locally.
```json
{
"url": "https://api.github.com/repos/sous-chefs/sc_vscode/branches/main/protection",
...
"required_conversation_resolution": {
"enabled": false
},
"lock_branch": {
"enabled": false
},
"allow_fork_syncing": {
"enabled": false
}
}
```
As can be seen on the payload above they are under the `enabled` key and are …

Fix JSON protection unmarshal error

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/actions_workflows.go
github/actions_workflows_test.go
github/billing.go
github/billing_test.go
github/github-accessors.go
github/github-accessors_test.go

Fixes #2595.
The structs hardcode the three machine types that Github Actions supported until recently. However, we now have a lot more different types of machines, with the potential for more to be added at any time. Using maps instead of structs will allow us to transparently support more machine classes in the future.
I've done this pretty naively instead of creating safe access methods or anything like that, and kept the map values as pointers for consistency with other maps in the codebase. Can't think of any tests that would be necessary (beyond the generated ones) but open to suggestions.

Change actions billing structs to maps

---

github/enterprise_code_security_and_analysis.go
github/enterprise_code_security_and_analysis_test.go
github/github-accessors.go
github/github-accessors_test.go

This branch adds support for 
> GitHub Changelog: Enable secret scanning with the enterprise-level REST API
Resolves #2599
[Blog](https://github.blog/changelog/2022-12-13-enable-secret-scanning-with-the-enterprise-level-rest-api/)
[Documentation](https://docs.github.com/en/rest/enterprise-admin/code-security-and-analysis?apiVersion=2022-11-28)

Enable secret scanning with the enterprise-level REST API

---

README.md
example/actionpermissions/main.go
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/go.mod
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tagprotection/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
github/github.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go
update-urls/go.mod

* #2606
* #2597
* #2596
* #2600
* #2607
* #2609
* #2611

Bump version of go-github to v49

---

github/actions_cache.go
github/actions_cache_test.go
github/github-accessors.go
github/github-accessors_test.go

@gmlewis   Ready for review. Please mention if something needs a change.
Thanks 
Fixes: #2584.

Add support for GitHub Actions cache API

---

github/actions_oidc.go
github/actions_oidc_test.go
github/github-accessors.go
github/github-accessors_test.go

Support OIDC subject claim customization templates for actions

---

github/actions_oidc.go
github/actions_oidc_test.go

There's a bug in the OpenID Connect customization template in #2615  where `included_claim_keys` is set to `nil` and sent to the GitHub API if it is not set. This results in the API returning a `422 Unprocessable Entity` error.
This PR resolves this by setting the JSON annotation of `IncludeClaimKeys` in `OIDCSubjectClaimCustomTemplate` to `omitempty` and adds a test to verify this.

Omit OpenID Connect customization template claims when none are set

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go

Fixes https://github.com/google/go-github/issues/2628
Signed-off-by: Daniel Liao <10663736+liaodaniel@users.noreply.github.com>

Add RequireLastPushApproval field to UpdateBranchProtection

---

README.md

Add httpcache code example to README.md

---

github/billing.go
github/billing_test.go

Fixes https://github.com/google/go-github/issues/2642
GitHub Actions returns total_minutes_used and included_minutes as floating point value.
The Implementation should accept this floating point value as float64.
Example
```
curl -H "Authorization: Bearer <TOKEN>" \
-H "Accept: application/vnd.github.v3+json"  \
https://api.github.com/orgs/{org}/settings/billing/actions
```
```json
{
"total_minutes_used": 1234.0,
"total_paid_minutes_used": 3959.0,
"included_minutes": 3000.0,
"minutes_used_breakdown": {
"UBUNTU": 1234,
"MACOS": 1234,
"WINDOWS": 0
}
}
```

Change total_minutes_used and included_minutes from int to float64

---

github/github.go
github/github_test.go

Add NewTokenClient

---

github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github-accessors_test.go

Adds method to update codescanning alert.
https://docs.github.com/en/rest/code-scanning?apiVersion=2022-11-28#update-a-code-scanning-alert

Add method to update codescanning alert

---

github/github.go

Add JSON tag for ErrorResponse

---

README.md
example/actionpermissions/main.go
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/go.mod
example/listenvironments/main.go
example/migrations/main.go
example/newfilewithappauth/main.go
example/newrepo/main.go
example/newreposecretwithlibsodium/go.mod
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/simple/main.go
example/tagprotection/main.go
example/tokenauth/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
github/github.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go
update-urls/go.mod

* #2643
* #2646
* #2621
* #2627
* #2629
* #2630
* #2561
* #2632
* #2638
* #2637
* #2639
* #2641
* #2644

Bump version of go-github to v50

---

README.md
example/go.mod
example/go.sum
example/ratelimit/main.go
github/code-scanning_test.go
github/github.go
github/github_test.go

* Add check-before-do for secondary rate limit
* Add optional hook for secondary limits
* Add missing categories for primary rate limits
Notes:
- As far as I could see, there is no documented API for runner registration - so I didn't handle this case.
fixes #2633 
Edit:
Following the conversation in this PR, the actual changes are:
* Add check-before-do for secondary rate limit
* Add missing categories for primary rate limits
* Add examples for using [go-github-ratelimit](https://github.com/gofri/go-github-ratelimit)

Add secondary rate limit handling (prevent remote requests) and fix primary rate limit categories

---

github/actions_variables.go
github/actions_variables_test.go
github/github-accessors.go
github/github-accessors_test.go

https://docs.github.com/en/rest/actions/variables
Fixes #2624 
* Added `actions_variables.go` 
* Added `actions_variables_test.go`

Add support for actions variables

---

github/actions_artifacts_test.go
github/repos_contents_test.go

Remove failing unit tests for Go 1.20

---

github/repos_collaborators.go
github/repos_collaborators_test.go

Fixes https://github.com/google/go-github/issues/2651

Add permission filter for list collaborators

---

github/apps_marketplace.go
github/github-accessors.go
github/github-accessors_test.go

Add Account field to MarketplacePurchase struct

---

github/github-accessors.go
github/github-accessors_test.go
github/issues_timeline.go

fixes #2664 
This PR adds the `requested_team` field into the `Timeline` type.

Add RequestedTeam to issues Timeline type

---

github/teams.go
github/teams_test.go

#2217 added support for the majority of the External Groups API but omitted listing groups for a specific Team within an Organization.
This PR adds the missing method, and corrects the comment on the original `ListExternalGroups` method as that actually returns all external groups within the Organization. I added the `ForTeamBySlug` suffix based on other methods in the source to distinguish it from the original method.
I've added tests based on the original `ListExternalGroups` method and everything passes.

Add ListExternalGroupsForTeamBySlug to Teams API

---

github/actions_workflow_runs.go

Add head_sha for ListWorkflowRunsOptions (fixes: #2687)
GitHub added this option to the following API:
/repos/{owner}/{repo}/actions/runs
Only returns workflow runs that are associated with the specified head_sha.
See also:
https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository

Add head_sha for ListWorkflowRunsOptions

---

github/github.go
github/github_test.go

Add the support of http prxoy to `NewClientWithEnvProxy`.
Relates to: #2363.

Support HTTP Proxy from environment

---

github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

Update the API routes, from `/orgs/{org}/custom_roles` to `/orgs/{org}/custom-repository-roles`, and some documentation references.
Fixes: #2700

Update custom repo roles URL

---

github/github_test.go
github/scim.go
github/scim_test.go

Fix SCIM query params

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/users_keys.go

Fixes #2717 by adding fields and accessors

Add added_by and last_used fields to keys

---

github/billing.go
github/billing_test.go

Adding Pagination support for fetching active committers in an organization.

Add ListOptions to GetAdvancedSecurityActiveCommittersOrg

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go

Add download capability for workflow run attempt logs

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_environments.go
github/repos_environments_test.go

Addresses https://github.com/google/go-github/issues/2725

Add `CanAdminsBypass` to `CreateUpdateEnvironment`

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_pages.go
github/repos_pages_test.go

Add BuildType to Github Repo Pages

---

github/messages.go
github/messages_test.go

Verify the payload signature if the request has a signature present in HTTP headers, or if a non-empty secretToken is passed to the ValidatePayload method, indicating that a signature is expected.
This modifies the behavior added in #1127, but not the spirit of what was requested in #1126, which is to support webhooks that don't have configured secrets.
Specifically, this no longer allows signature checking to be skipped entirely, even for webhooks with a configured secret, simply by passing an empty secretToken to ValidatePayload.
This also cleans up some documentation and unused fields in the accompanying test.
Fixes #2731 
/cc @myitcv

verify payload signature if present

---

github/actions_required_workflows.go
github/actions_required_workflows_test.go
github/github-accessors.go
github/github-accessors_test.go

Have implemented the API's that would enable managing Required Workflows.
Merging this Fixes google/go-github#2729

Implement the actions required workflows APIs

---

github/actions_workflow_runs.go

I add some options for `ListRepositoryWorkflowRuns`.
In particular, `exclude_pull_requests` is very useful, as mentioned in the gh command implementation. (https://github.com/cli/cli/blob/trunk/pkg/cmd/run/shared/shared.go#L338)
Document: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository

Add options for listing workflow runs

---

github/event_types.go
github/event_types_test.go

Closes https://github.com/google/go-github/issues/2741
Adding the `Topics` field, which is included in push event payloads under `repository`

Add Topics to PushEventRepository

---

github/timestamp.go
github/timestamp_test.go

Add GetTime method to Timestamp

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_pages.go
github/repos_pages_test.go

Fixes #2745
Allows requesting a DNS health check for the CNAME configured for a repository's GitHub Pages.

Add DNS health checks support for GitHub Pages

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

Closes https://github.com/google/go-github/issues/2749
Let me know if you have a better idea for struct names.

Add `Owner` to `EditChange` struct

---

github/actions_required_workflows.go
github/actions_required_workflows_test.go

Updated create and update org required workflow methods to return the required workflow object returned by the github api.
Merging this Fixes https://github.com/google/go-github/issues/2756

Update Create/Update methods to return the workflow

---

github/apps.go
github/github-accessors.go
github/github-accessors_test.go

It's not in the official github documentation yet but exposed to the API.
```
% curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $T" https://api.github.com/app|grep installations_count
"installations_count": 3
```

Add InstallationsCount to App

---

github/actions_required_workflows.go
github/actions_required_workflows_test.go

Fixes: #2770
Changed the method from PUT to POST, by following the github REST API docs: https://docs.github.com/en/rest/actions/required-workflows?apiVersion=2022-11-28#create-a-required-workflow

Change the CreateRequiredWorkflow method from PUT to POST

---

github/orgs_members.go

Fixes: https://github.com/google/go-github/issues/2777

Add omitempty to CreateOrgInvitationOptions fields

---

example/go.mod
example/go.sum
github/github.go
github/github_test.go

GitHub API states that x-ratelimit-reset might be returned instead of the Retry-After header for secondary rate limits.
Seems like GitHub recently started using it. Some evidence:
- https://github.com/gofri/go-github-ratelimit/issues/9 
- https://github.com/orgs/community/discussions/50326
This PR handles this case as a fallback for Retry-After, and cleans the code a bit while at it

Support x-ratelimit-reset handling for secondary rate limits

---

github/gen-accessors.go
github/github-accessors.go
github/github-accessors_test.go

Fixes: https://github.com/google/go-github/issues/2425
This PR is similar to the following PR:
- https://github.com/google/go-github/pull/1867

Support array type in go generate with whitelist

---

github/repos_test.go

Is #55 still actively pursued?
Adds test for JSON marshalling specifically the `RepositoryTag` resource.

Add test for resource JSON marshaling

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go

Resolves: https://github.com/google/go-github/issues/2787

Add "new_name" parameter to repo transfer request (#2787)

---

github/dependabot_secrets.go
github/dependabot_secrets_test.go

According to the docs, the API for setting a repos access to dependabot secrets is expecting an array of integers.
[https://docs.github.com/en/rest/dependabot/secrets?apiVersion=2022-11-28#set-selected-repositories-for-an-organization-secret](https://docs.github.com/en/rest/dependabot/secrets?apiVersion=2022-11-28#set-selected-repositories-for-an-organization-secret)

Update DependabotSecretsSelectedRepoIDs type to []int64

---

example/codespaces/newreposecretwithxcrypto/main.go
example/codespaces/newusersecretwithxcrypto/main.go
example/newreposecretwithxcrypto/main.go
github/codespaces.go
github/codespaces_secrets.go
github/codespaces_secrets_test.go
github/codespaces_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github.go

https://github.com/google/go-github/issues/2362

Initial implementation of codespaces API

---

github/actions_runners.go
github/github-accessors.go
github/github-accessors_test.go

Provide full response for generate-jitconfig method instead of `encoded_jit_config` only. According to the [doc](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-a-repository) there is a `runner` object in the API response.
why do we need it? since the generate-jitconfig API is just not generating jitconfig but also creating new self-hosted runner to the github so there is no way we can get the newly created runner id other than from this response.
cc @mkulke @gmlewis

Add Runner to generate-jitconfig method

---

github/admin_stats.go
github/codespaces.go

unnecessary use of fmt.Sprint
unnecessary use of fmt.Sprintf

Remove unnecessary use of fmt.Sprintf

---

github/github.go

should use bytes.Equal(ae.Raw, v.Raw) instead (S1004)

Use bytes.Equal instead of bytes.Compare

---

github/dependabot_secrets.go
github/dependabot_secrets_test.go

`CreateOrUpdateOrgSecret`'s API uses `string` for selected repository IDS while other APIs use `int`. This fixes the issue locally by implementing its own type.
fixes https://github.com/google/go-github/issues/2816

Fix `CreateOrUpdateOrgSecret` regression introduced in v53

---

github/github-accessors.go
github/github-accessors_test.go
github/secret_scanning.go
github/secret_scanning_test.go

Add support for getting Repository when [listing secret scanning alerts for enterprise](https://docs.github.com/en/rest/secret-scanning/secret-scanning?apiVersion=2022-11-28#list-secret-scanning-alerts-for-an-enterprise)
There is no easy way of getting the org/repo when listing secret scanning alerts for enterprise in the current struct. The API returns the Repository field, and with this change it will be included in the SecretScanningAlert struct

Add Repository struct to SecretScanningAlert

---

github/pulls.go
github/pulls_test.go

`ListPullRequestsWithCommit` uses `PullRequestListOptions` as one of it's parameters. This is incorrect because in GitHub's documentation, the endpoint for this function, `repos/%v/%v/commits/%v/pulls`, does not share the same parameters as the ones defined in `ListPullRequestsWithCommit`
https://github.com/google/go-github/blob/96726d8192f34c0d46e7b64b3c400962e8e64898/github/pulls.go#L119-L141
This PR simply sets the correct options, ListOptions, for the ListPullRequestWithCommit.
see #2815  for more details

Fix ListPullRequestsWithCommit option type

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_personal_access_tokens.go
github/orgs_personal_access_tokens_test.go

Following up with my previous PR #2826, I am also proposing the following changes, which add support for [programmatically approving or denying](https://docs.github.com/en/rest/orgs/personal-access-tokens?apiVersion=2022-11-28#review-a-request-to-access-organization-resources-with-a-fine-grained-personal-access-token) fine-grained personal access token requests.
I thought about including the rest of this API, but I don't have an immediate need for it and the PR might get a little too big. I was also a bit unsure on the function signature, so let me know your thoughts.

Add support for personal access tokens request review API

---

github/event.go
github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/messages.go
github/messages_test.go

This PR adds support for the [`personal_access_token_request`](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#personal_access_token_request) webhook event.
> This event occurs when there is activity relating to a request for a fine-grained personal access token to access resources that belong to a resource owner that requires approval for token access.

Add support for `personal_access_token_request` webhook event type

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_rules_test.go
github/repos_rules.go

This PR adds support for referencing repositories by ID in Ruleset conditions.
See https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset
API is changed a bit, probably a low impact since v53.2.0 (with ruleset support added) was released just recently and hopefully not many have code using it in production.
The change `RulesetRepositoryConditionParameters` -> `RulesetRepositoryNamesConditionParameters`
I'm open for suggestions for a change that would not shake the API.

Support repository_id in org ruleset conditions

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_rules_test.go
github/repos_rules.go
github/repos_rules_test.go

This PR reconciles library with GitHub API for the following regarding [repo rulesets](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset):
- `BypassMode` should be part of `BypassActor`.
- `ActorType` possible values documentation updated to match API docs.
- `BypassMode possible values documentation updated to match API docs.
- `Ruleset` ID field changed to `Int64` pointer and added `omitempty` to allow for nil, ruleset ID is unknown prior to creation and is not required when sending a POST request to create ruleset.

Fix repo rules bypass settings

---

github/github-accessors.go
github/github-accessors_test.go
github/secret_scanning.go

added support for getting secret type display name when listing secret scanning alerts

Add secret type display to secret scanning alert

---

github/repos_contents.go

Related to https://github.com/google/go-github/pull/2805#issuecomment-1638119252 .
This allows users to catch this specific error using `errors.Is`.

Use a sentinel error when blocking paths for `RepositoriesServices.GetContents`

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos.go
github/repos_test.go

Fixes https://github.com/google/go-github/issues/2845

Add Dependabot field in security_and_analysis

---

github/code-scanning.go
github/code-scanning_test.go

Fixes https://github.com/google/go-github/issues/2847

Add new query params for AlertListOptions

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_audit_log.go
github/orgs_audit_log_test.go

Much to my chagrin, the audit log view in the site manager does not follow the shape of the API response.
I previously raised a PR #2843 which was merged yesterday. Unfortunately, it does not work with the payload returned from the API.
My sincere apologies about this.

Fix `old_name` field in `AuditEntry`

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_audit_log.go
github/orgs_audit_log_test.go

When renaming a Github organisation, the audit log entry (with action `org.rename`) will contain `data.old_login` which provides the prior name of the organisation.
This PR builds upon prior work which added support for the `data` field within an Audit Log entry.

Add `OldLogin` field to `AuditEntryData`

---

github/repos_rules.go
github/repos_rules_test.go

Since discussing this with the GitHub folks, I’ve been told that the `update_allows_fetch_and_merge` parameter for the update rule only applies to forked repos. **Note: I was told this is still bugged for forked repos when sending a request through the API, but will be fixed in the near future.**
Since it only applies to forked repos, the API returns a ruleset which contains:
```
{
"type": “update"
}
```
This doesn't have a parameters field, so when we try to unmarshal the JSON we run into a nil pointer dereference error. No functionality is changed here except to check for a nil pointer before we try to unmarshal the JSON, and if it isn’t included then we just set the parameters to nil.
I didn’t think this needed a change in testing because it doesn’t change any functionality, but I’ll …

Check for nil pointer in update rule parameters

---

github/repos_releases_test.go

This picks up a dropped `err` variable in tests and clarifies the error message.

Fix dropped test error

---

github/event.go
github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/messages.go
github/messages_test.go
github/repos_hooks_deliveries_test.go

Fixes https://github.com/google/go-github/issues/2861
Adds support for the [Security and Analysis webhook event](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#security_and_analysis) which fires whenever security and analysis features are enabled or disabled for a repository.

Add support for the security and analysis webhook event

---

github/event.go
github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/messages.go
github/messages_test.go
github/repos_hooks_deliveries_test.go

Closes https://github.com/google/go-github/issues/2867
Added support for [projects_v2](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2) and [projects_v2_item](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2_item) webhook events.

Add support for projects_v2 and projects_v2_item webhook events

---

scrape/scrape.go

This is a quote from the [documentation](https://pkg.go.dev/net/http#example-Get) of the `net/http package`:
> When err is nil, resp always contains a non-nil resp.Body. Caller should close resp.Body when done reading from it.
In the current implementation, if the error code is 404, the response body will not close.

Defer closing body before checking HTTP status code

---

github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/repos.go
github/repos_test.go

This is an attempt to fix #2080. It is also required by upstream projects such as [terraform-provider-github](https://github.com/integrations/terraform-provider-github), see [issue 1301](https://github.com/integrations/terraform-provider-github/issues/1301)
```
go test github.com/google/go-github/...
ok      github.com/google/go-github/v53/github  1.165s
?       github.com/google/go-github/v53/test/fields     [no test files]
?       github.com/google/go-github/v53/test/integration        [no test files]
```

Add GetAutomatedSecurityFixes to report status

---

example/basicauth/main.go
example/tagprotection/main.go
example/tokenauth/main.go

Closes #2875 
Replaces deprecated module `crypto/ssh/terminal` in examples

Replace deprectated crypto/ssh/terminal module in examples

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_contents.go
github/repos_contents_test.go

Add SubmoduleGitURL to RepositoryContent

---

github/repos.go
github/repos_test.go

Closes https://github.com/google/go-github/issues/2883
Please let me know if the method names are not descriptive enough or just need to be changed. 
Also, something that's been bugging me. In my previous [PR](https://github.com/google/go-github/pull/2869), I did some actual testing aside from the unit tests. While not present in [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) , is it advisable/necessary/optional to perform actual testing (importing the library, calling the new method and examine response).

Add support for enable/disable private vulnerability reporting on repositories

---

github/orgs_hooks_configuration.go
github/orgs_hooks_configuration_test.go
github/repos_hooks_configuration.go
github/repos_hooks_configuration_test.go

Closes https://github.com/google/go-github/issues/2884
This PR adds support for fetching and updating organization, repository webhook configuration

Add support for organization, repository webhook configuration

---

github/issue_import.go
github/issue_import_test.go

The error was not returned when the 202 status was received during the issues import.

Return json.Unmarshal error when importing issues deferred

---

github/dependabot_alerts.go
github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go
github/messages.go
github/messages_test.go
github/repos_hooks_deliveries_test.go

Closes #2790 
Added support for [dependabot_alert](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#dependabot_alert) webhook event.

Add support for dependabot_alert webhook event

---

github/code-scanning.go
github/code-scanning_test.go
github/github-accessors.go
github/github-accessors_test.go

Fixes https://github.com/google/go-github/issues/2899

Add missing CodeScanning endpoints

---

github/repos_rules.go

`RulesetRepositoryNamesConditionParameters`, Include and Exclude fields shall not be omitted when empty.
Fixes: #2909

Fix serialization of repository_names conditions object

---

.github/workflows/linter.yml

Ever since #2903 , the golangci-lint GitHub Actions workflow has frequently timed out.
According to this: https://github.com/golangci/golangci-lint-action/issues/308
this PR should fix that problem.

Fix golangci-lint timeout failures

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/misc.go
github/misc_test.go
test/integration/misc_test.go

Remove ListServiceHooks

---

github/github-accessors.go
github/github-accessors_test.go
github/secret_scanning.go
github/secret_scanning_test.go

Closes: #2871.
This PR fixes the endpoint:
https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning/secret-scanning#update-a-secret-scanning-alert
by sending its parameters in the body instead of as URL query parameters.
I was unable to edit #2871 directly, so this is a replacement.
Thank you, @jentfoo for the bug report and initial PR!

Fix SecretScanning API by switching arguments from url to json

---

github/actions_artifacts.go
github/actions_artifacts_test.go
github/actions_workflow_jobs.go
github/actions_workflow_jobs_test.go
github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/github.go
github/repos.go
github/repos_contents.go
github/repos_contents_test.go
github/repos_test.go
test/integration/repos_test.go

The [`roundTripWithOptionalFollowRedirect()` method](https://github.com/google/go-github/blob/b45ef89f2dd0ec803ab8f27725bdb4941c0cbc99/github/github.go#L1561) currently takes a boolean parameter `followRedirects`, used to support HTTP 301 redirections. However, at most 1 redirection is handled at the moment (the parameter is set to `false` after the first iteration.)
I've stumbled upon multiple repositories where `https://api.github.com/repos/<OWNER>/<PROJECT>/branches/<BRANCH>` redirects twice ; as a result, the [`GetBranch()` method](https://github.com/google/go-github/blob/b45ef89f2dd0ec803ab8f27725bdb4941c0cbc99/github/repos.go#L1277) only follows the first redirection, then returns the 2nd HTTP 301 response.
This MR proposes to generalize the `followRedirects` boolean into a …

Allow up to maxRedirects upon receiving HTTP 301 status

---

github/actions_variables_test.go

Hello,
this is just another trivial test adding to the 10 year old issue. I hope there is still demand for this.
Helps #55

Add test for resource JSON marshaling - ActionVariable

---

github/actions_cache_test.go
github/actions_oidc_test.go

This PR covers JSON marshalling testing for following types (partial fix for #55)
1. actions_oidc
1. type OIDCSubjectClaimCustomTemplate
2. actions_cache
1. type ActionsCache
2. type ActionsCacheList
3. type ActionsCacheUsage
4. type ActionsCacheUsageList
5. type TotalCacheUsage
6. _(type ActionsCacheListOptions  does not have any json encoding so we have skipped test case for it.)_
NOTE for reviewers: This contribution is for hactoberfest credit please label it so. Thanks!

Add json marshaling tests for action usage and OIDC types

---

github/apps.go
github/apps_test.go
github/github-accessors.go
github/github-accessors_test.go

The PR adds support for [listing installation requests for the authenticated app](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installation-requests-for-the-authenticated-app).

Add List Installation Requests API

---

github/repos.go
github/repos_test.go

When a branch name with special characters like `%` is passed to the [`RepositoryService.GetBranch()` method](https://github.com/google/go-github/blob/8cd452b85e821c32eefcc5964e91e57f9731891f/github/repos.go#L1277) as is, an error is currently returned:
```
invalid URL escape "%"
```
Passing an escaped branch name to `RepositoriesService.GetBranch()` works fine.
Here's a minimal reproducer
```golang
import (
"context"
"net/http"
"testing"
"github.com/google/go-github/v53/github"
"github.com/stretchr/testify/require"
)
func TestGetBranch(t *testing.T) {
t.Parallel()
ctx := context.Background()
githubClient := github.NewClient(&http.Client{
Transport: http.DefaultTransport,
})
owner := "samstickkz"
project := "curr"
branchName := "Feature/authentication_90%"
branch, response, err := …
```

Escape branch string before inserting it in URL

---

github/repos_codeowners.go
github/repos_codeowners_test.go

Support options for GetCodeownersErrors

---

github/github.go
github/github_test.go

Add nil check in ErrorResponse.Error method

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/github-accessors.go
github/github-accessors_test.go

Add referenced workflows to WorkflowRun

---

github/repos.go
github/repos_test.go

Fixes #2976 
The property `Checks` on `RequiredStatusChecks` type is not required according to GitHub api, so using the `omitempty` tag

Fix branch protection request fields

---

github/examples_test.go
github/repos.go
github/repos_test.go
test/integration/repos_test.go

Closes #2987
This deprecates `RepositoriesService.List` and replaces it with two new methods: `RepositoriesService.ListByUser` and `RepositoriesService.ListByAuthenticatedUser`. See #2987 for the justification.

Deprecate RepositoriesService.List

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_properties.go
github/orgs_properties_test.go

Resolves https://github.com/google/go-github/issues/2965

Implement Custom Properties

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Add default branch to repository edit event

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/issues.go

Fixes https://github.com/google/go-github/issues/2996
Adds `Draft` to the `Issue` type, which is documented to be included with issues - https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment

Add `Draft` to `Issue` type

---

github/github.go

GitHub updated its documentation for rate limits and is now sending the following message when a secondary rate limit is triggered:
```json
{
"message": "You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later. If you reach out to GitHub Support for help, please include the request ID XXXX.",
"documentation_url": "https://docs.github.com/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits"
}
```
This PR updates the check on the `documentation_url` to detect a secondary rate limit

Fix secondary rate limits URL

---

github/github-accessors.go
github/github-accessors_test.go
github/security_advisories.go
github/security_advisories_test.go

- implement global security advisories API
Fixes: https://github.com/google/go-github/issues/2851
cc @gmlewis

Implement global security advisories API

---

github/enterprise_code_security_and_analysis.go
github/enterprise_code_security_and_analysis_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs.go
github/repos.go
github/repos_test.go

Add scanning validity checks

---

github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/github_test.go
github/rate_limit.go
github/rate_limit_test.go

resolves https://github.com/google/go-github/issues/3018

Add code_search and dependency_snapshots for RateLimits

---

github/security_advisories.go
github/security_advisories_test.go
openapi_operations.yaml

Support temporary private fork creation via API

---

github/orgs_packages.go
github/orgs_packages_test.go

Package names aren't escaped before being added to the url.
E.g. `orgs/foo/packages/container/foo/bar` instead of `orgs/foo/packages/container/foo%2Fbar`
This causes 404 errors for such packages.

Escape package names to support names which include a slash

---

github/github.go
github/github_test.go

Users can accidentally leak credentials by doing something like this:
```go
pat := os.Getenv("GITHUB_TOKEN")
httpClient := &http.Client{
Timeout: time.Second * 30,
}
ghClient := github.NewClient(httpClient).WithAuthToken(pat)
// ... do something with ghClient
httpClient.Get("https://some-sketchy-site")
```
This PR fixes that by updating `NewClient` to make a copy of httpClient so that when its transport is updated by `WithAuthToken`, the original httpClient won't have its transport updated as well.
It also updates `TestWithAuthToken` to check for leaks

Don't update httpClient passed to NewClient

---

github/repos_properties.go
github/repos_properties_test.go

Closes https://github.com/google/go-github/issues/3014.
Signed-off-by: Daniel Liao <10663736+liaodaniel@users.noreply.github.com>

Add GetAllCustomPropertyValues for repositories

---

github/copilot.go
github/copilot_test.go

small fix to #2973
cc @gmlewis @o-sama

Fix copilot API payload

---

github/github-accessors.go
github/github-accessors_test.go
github/issues_events.go

The IssueEvent was missing the details of `action` and `repository`. 
Issue: #3038 
Related Issue: Similar issue was also reported in #768

Add Repo and Action to IssueEvent

---

github/code-scanning.go
github/code-scanning_test.go

Fixes #3036 
- Update successful test case for UploadSarif to validate the expected return data
- Handle the AcceptedError in UploadSarif and unmarshal a SarifID from the error's Raw attribute

Fix issue in AcceptedError handling for UploadSarif

---

github/actions_secrets.go
github/actions_secrets_test.go
github/actions_variables.go
github/actions_variables_test.go

This wraps two repository API endpoints which are currently not available in the interface:
- [List repository organization actions secrets ](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/secrets?apiVersion=2022-11-28#list-repository-organization-secrets)
- [List repository organization actions variables](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#list-repository-organization-variables)

Add list repo org variables and secrets

---

github/github.go
github/github_test.go

Fix leaked client transport on copy

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_deployment_protection_rules.go
github/repos_deployment_protection_rules_test.go

Fixes https://github.com/google/go-github/issues/3022

Add support for deployment protection rules

---

github/actions_workflow_jobs.go
github/actions_workflow_jobs_test.go

Fixes: #3059.
Add support ListWorkflowJobsAttempt API. 
https://docs.github.com/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run-attempt

Add ListWorkflowJobsAttempt method to ActionsService

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go
github/repos_test.go
test/integration/repos_test.go

By making the both `Contexts` and `Checks` pointers, the JSON will allow sending an empty slice as `[]` to the GitHub API, instead of taking those out and sending `nil` or `null`.
This will actually solve both https://github.com/google/go-github/issues/2976 and https://github.com/google/go-github/issues/2467.
I also clarified in the comments that empty slices are allowed, implying that if the user wants to set no checks or contexts, to allow passing an empty slice.
These changes allow the Go API to properly reflect the behavior of the GitHub API.

Turn `RequiredStatusChecks` `Checks` and `Contexts` into pointers

---

github/repos_rules.go
github/repos_rules_test.go

The purpose of this commit is to allow further querying of rulesets for a specific branch, at the organization or the repository level.
To achieve this, this commit adds the `ruleset_id` and `ruleset_source_type` fields to the RepositoryRule object according to the returned information from the github API.

Allow querying rule set information by ID with information returned from GetRulesFromBranch

---

github/code-scanning_test.go
github/enterprise_audit_log_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github.go
github/github_test.go
github/orgs_audit_log_test.go
github/rate_limit.go
github/rate_limit_test.go

When calling `https://api.github.com/rate_limit`, the endpoint returns a `audit_log` rate limit category as well. This is used for `/audit-log` endpoints:
- https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/orgs?apiVersion=2022-11-28#get-the-audit-log-for-an-organization
- https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/using-the-audit-log-api-for-your-enterprise#using-the-audit-log-api
This PR adds this new rate limit category.
I have a use case where I need to know the rate limit category before making the request so as to not reimplement what's already done in `go-github`, I made this logic public. Other users could also benefit of this change.
If you think it's not reasonable and it …

Add audit log rate limit category and make rate limit category getter public

---

github/apps.go
github/github-accessors.go
github/github-accessors_test.go

This PR allows app installations to request tokens with access to the Org level Custom Properties APIs
1. [GitHub App installation access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)
2. [API Docs](https://docs.github.com/en/rest/orgs/custom-properties?apiVersion=2022-11-28#get-a-custom-property-for-an-organization)

Allow Installation of Custom Properties Permissions

---

github/copilot.go
github/copilot_test.go

The pagination must be passed as query parameters instead of request [body according to the docs](https://docs.github.com/en/rest/copilot/copilot-user-management?apiVersion=2022-11-28#list-all-copilot-seat-assignments-for-an-organization).
Currently this is silently failing but the pagination is broken if you've got lots of Copilot users.

Fix pagination for ListCopilotSeats

---

github/actions_secrets.go
github/actions_variables.go
github/actions_variables_test.go
github/admin.go
github/admin_orgs.go
github/admin_stats.go
github/admin_users.go
github/authorizations.go
github/copilot.go
github/repos_autolinks.go
github/repos_prereceive_hooks.go
github/users_administration.go
openapi_operations.yaml

Fixes:
#3103 
BREAKING-CHANGE: The following endpoints now take `owner` and `repo` names instead of an integer repo ID:
* ActionsService.ListEnvVariables
* ActionsService.GetEnvVariable
* ActionsService.CreateEnvVariable
* ActionsService.UpdateEnvVariable
* ActionsService.DeleteEnvVariable

feat!: Update deprecated endpoints in github/action_variables.go

---

github/repos_properties.go
github/repos_properties_test.go
openapi_operations.yaml

Adds method CreateOrUpdateRepoCustomPropertyValues

Add CreateOrUpdateRepoCustomPropertyValues

---

github/repos_rules.go

When failing to match the type of a repository rule, print the unmatched name.
Previously only the type of the unmatched name was printed, which is always 'string'. This makes it hard to troubleshoot unmarshalling failures.

Print the unrecognized repository rule type

---

github/meta.go
github/meta_test.go

Adds two of the missing fields, `github_enterprise_importer` and `domains`, which are now included with the public meta endpoint. Also fixed some minor capitalization errors.

feat: Add missing github enterprise importer and domains meta fields

---

AUTHORS
github/orgs_rules_test.go
github/repos_rules.go
github/repos_rules_test.go

Fixes: #3098.
Added support for respository ruleset merge_queue in JSON unmarshalling code with accompanying tests

Add support for merge queue ruleset JSON unmarshaling 

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

Fixes: #3154.
The `member` webhook event as described by github documentation contains a `changes` object. https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#member
However, the struct that defines the `Member` webhook event type is missing the `changes` object . This PR adds the missing `changes` object to the `MemberEvent` type.

Add Missing Changes Field to Member Event Type.

---

github/copilot.go
github/copilot_test.go

The pagination options were previously being applied as the Request body, instead of applied to the URL as in other `List` endpoints. This PR ensures that these options are correctly applied to the URL and introduces additional parameters in the test case to ensure this.

Fix application of pagination options on ListCopilotSeats endpoint

---

github/dependency_graph_snapshots.go
github/dependency_graph_snapshots_test.go
github/github-accessors.go
github/github-accessors_test.go

Starts Dependency Graph service support by starting with the [Create Snapshot](https://docs.github.com/en/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28#create-a-snapshot-of-dependencies-for-a-repository) endpoint

Add support for Dependency Graph Snapshots endpoint

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

In [GH docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#deployment_status) we can see that `deployment_status` has a field `action`, that is always set to `created`. This pr adds it to json representation.

Add Action to DeploymentStatusEvent

---

github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

Wrap queries to return the teams and users associated with a specific organization role

Query identities associated with organization roles

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_properties.go
github/orgs_properties_test.go

Adds missing field `values_editable_by` for custom properties, as well as mirrors the field documentation directly from the API documentation for the other fields of custom properties.
Ref: https://docs.github.com/en/rest/orgs/custom-properties?apiVersion=2022-11-28#create-or-update-custom-properties-for-an-organization

feat: Add missing values_editable_by field for organization custom properties

---

github/enterprise_actions_runners.go
github/enterprise_actions_runners_test.go

Fixes: #3166.
BREAKING-CHANGE: This changes `ListOptions` to  `ListRunnersOptions` in `EnterpriseService.ListRunners`.
I fixed a bug related ListRunners API. The `ListRunnersOptions` was not being applied to Enterprise Runner.
follow up: https://github.com/google/go-github/pull/3094

feat!: Change enterprise runner to also use ListRunnersOptions

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/pulls_reviews.go

closes #3168 
Made InReplyTo an int64 following the established type in https://pkg.go.dev/github.com/google/go-github/v62/github#PullRequestComment but happy to change if that or anything else is incorrect.

Add CommitID, InReplyTo, and SubjectType to DraftReviewComment

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

Added support for querying, creating, updating and deleting organization custom roles.
BREAKING CHANGE: `CreateOrUpdateCustomRoleOptions` has been renamed to `CreateOrUpdateCustomRepoRoleOptions` and `roleID` has been changed from type `string` to `int64`.

feat!: Support querying organization custom roles

---

github/repos_contents.go

Support status codes 302 and 200 in GetArchiveLink endpoint

---

README.md

Fixes: #3178.
This PR includes some README changes to include references of a new pkg to authenticate application and installation requests.

Update readme to include go-githubauth for Application auth

---

github/repos_contents.go

Main motivation is tracing as this can be the most time consuming operation.

Fix: Propagate context with DownloadContents

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_collaborators.go

Fixes: #3189.
I am currently using this API to fetch what role does a user have on a repository. AFAICS, RepositoryPermissionLevel struct is missing role_name which is provided by the API (https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user). Due, to this I am unable to use the library. This PR introduces the field within the RepositoryPermissionLevel struct

Add role name to RepositoryPermissionLevel

---

README.md

The URL is missing the schema so GitHub treats it as a relative link.

Fix go-githubauth link in README.md

---

github/enterprise_actions_runners.go
github/enterprise_actions_runners_test.go

Add support for Enterprise GetRunner

---

scrape/apps.go

Add support for App Callback URLs

---

github/pulls.go

I recently mixed up "Head" and "Base" and the error message was not clear. Add some guidance to help people avoid making the same mistake.
This is copied word for word from the existing Github docs.

Add doc for NewPullRequest

---

README.md

Fix: https://github.com/google/go-github/issues/3209
As suggested in the issue, this PR adds in the README some information about how to use iterators with the [enrichman/gh-iter](https://github.com/enrichman/gh-iter) package, with a small code snippet.
The feature is still experimental, because it is not available in the standard library yet (Go 1.23 is planned for [August 2024](https://tip.golang.org/doc/go1.23)).

Added iterators section in README

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

Fixes: #3214.
`CustomRepoRoles` and `CustomOrgRoles` structures have missing fields, due to which the part of the response from the github API is missed.
Updating the structures as per the github API schema defined.

Update CustomOrgRoles and CustomRepoRoles to include all fields returned by the GitHub API

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_properties.go
github/orgs_properties_test.go
github/repos_properties_test.go

Fixes #3198.
BREAKING CHANGE: `CustomPropertyValue.Value` is changed from `*string` to `interface{}` to support `string` and `[]string` values.
So the problem here is that the GitHub custom properties `value` can come in either as a `string` (for all non `multi_select` properties), or as a `[]string` in a `multi_select` property.
The issue is happening because we were trying to unmarshal it but always expecting a `string` for the Value.
My solution was to make value an `interface{}` type that implements a `UnmarshalJSON` to handle both scenarios. While this works, we end up losing the auto generated `GetValue()` accessor. Another thing I was unsure is that I saw on other places and on the tests for this that we use a pointer to the value, but I changed it to the value itself on the …

feat!: Add support for multi-select Custom Properties

---

github/teams.go
github/teams_test.go

Fixes #3196.
BREAKING CHANGE: Replace `ListCursorOptions` with `ListIDPGroupsOptions` in `TeamsService.ListIDPGroupsInOrganization`
I followed the template of this PR, fixing a similar issue: https://github.com/google/go-github/pull/3094. 
Let me know if there is a better way to handle this. And I'm open to better naming suggestions.

feat!: Replace ListCursorOptions with ListIDPGroupsOptions in TeamsService.ListIDPGroupsInOrganization

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_personal_access_tokens.go
github/orgs_personal_access_tokens_test.go

Add List fine-grained personal access tokens with access to organization resources API

---

scrape/apps.go
scrape/apps_test.go
scrape/scrape.go

Fixes: #3210.
**BREAKING CHANGE:** The `CreateApp` function now requires two arguments: `AppManifest` and `orgName`, to support creating apps with organizations.
The issue occurred because the create app URL path was only set up for creating personal GitHub apps.
My solution was to add an additional argument to the function to provide the necessary information for creating organizational GitHub Apps. The second argument, `AppConfig`, now includes configuration structs with an `OwnerType` that can be either personal or organizational, and you can provide the organization name by passing `OrgName` in the `AppConfig` struct.
For more details, see the issue: [https://github.com/google/go-github/issues/3210](https://github.com/google/go-github/issues/3210).

feat!: Add support for creating GitHub App with organizations

---

github/orgs_custom_roles.go

Changes related to the issue https://github.com/google/go-github/issues/3226

Allow create custom repository/organization roles without permission

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_rules.go
github/repos_rules_test.go

Fixes: #3231.
This is an attempt to add support for file_path_restriction in repository rules. It will implement #3231

Add support for filepath repository rules

---

github/repos_rules.go
github/repos_rules_test.go

Fixes: #3244.
I signed the CLA. The `fmt` `test` and `lint` scripts all passed without warnings.

feat: Add do_not_enforce_on_create to required status checks rule params

---

github/github-accessors.go
github/github-accessors_test.go
github/meta.go
github/meta_test.go

Fixes: #3248.
BREAKING CHANGE: `APIMeta.Domains` changed from `map` to `struct`.
This should at least be a tiny bit less prone to breaking, as it only accounts for existing schema with that API, and future additions should silently be ignored (unless GitHub breaks the contract, which they didn't _really_ do in this scenario).
- closes #3248

feat!: Fix meta service domains schema structure

---

github/scim.go
github/scim_test.go

Fixes: #3238. 
BREAKING CHANGE: `SCIMService.ProvisionAndInviteSCIMUser` now returns a response.

feat!: Fix broken SCIMService.ProvisionAndInviteSCIMUser method

---

github/billing.go
github/billing_test.go

Update active committers struct to include additional attributes.

Update active committers struct

---

github/activity_notifications.go
github/activity_notifications_test.go

Fixes https://github.com/google/go-github/issues/3264.

Add 'mark thread as done' functionality

---

github/orgs_credential_authorizations.go
github/orgs_credential_authorizations_test.go

BREAKING CHANGE: `ListCredentialAuthorizations` now takes `opts *CredentialAuthorizationsListOptions` instead of `ListOptions`.
As per the docs for the [List SAML SSO authorizations for an organization](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/orgs?apiVersion=2022-11-28#list-saml-sso-authorizations-for-an-organization) endpoint — it supports a query param named `login` to filter the authorizations by a github user.
This PR adds support for passing this `login` query param via a new struct (`CredentialAuthorizationsListOptions`) which embeds `ListOptions` as `ListOptions` itself only supports `Page` and `PerPage` query params.

feat!: Add login query param support to ListCredentialAuthorizations

---

github/checks.go
github/checks_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go

fixes https://github.com/google/go-github/issues/3277

Add missing fields to the checksuite event

---

script/lint.sh

As specified in the [GitHub Actions logs for the linter](https://github.com/google/go-github/actions/runs/10973176585/job/30470274170#step:4:9), the ``github-actions`` output format is deprecated, and ``colored-line-number`` should be used instead. Deprecation was done in https://github.com/golangci/golangci-lint/pull/4726

chore: Change golangci-lint output format due to deprecation

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_custom_roles.go

Resolves #3283 
Exactly the same as [the custom repo role](https://github.com/google/go-github/blob/46f1127c50024fd92c7bb10992e1baaf607ee5e7/github/orgs_custom_roles.go#L63). 
[Docs for the endpoint](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/organization-roles?apiVersion=2022-11-28#create-a-custom-organization-role)

feat: Support baseRole option for custom organization roles

---

github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

Resolves #3282 
It was only possible to list organization roles before, this makes it possible to get a specific one. 
I might have went overboard with the test-cases (testing both a custom role and a built-in one). I haven't written mocks before, so I'm not sure what the best practices are here 😅

feat: Support getting an organization role

---

github/orgs_custom_roles.go
github/orgs_custom_roles_test.go

feat: Implement organization role assignments for both users and teams

---

.golangci.yml

This PR enables the G602 gosec rule in golangci-lint's config because golangci-lint 1.60.2 doesn't have any problems with gosec's performance. The issues https://github.com/golangci/golangci-lint/issues/4039 and https://github.com/securego/gosec/issues/1007 have been fixed.

chore: Enable gosec G602 rule

---

github/actions_artifacts_test.go
github/actions_cache.go
github/actions_runners_test.go
github/apps_test.go
github/github.go
github/issue_import_test.go
github/migrations_source_import.go
github/orgs_members.go
github/repos.go
github/teams_discussion_comments.go
github/teams_discussion_comments_test.go
github/teams_discussions.go
github/teams_test.go
github/users_emails.go
github/users_gpg_keys.go

The PR fixes spelling mistakes in comments, test names, parameter names, and variables.

fix: Correct typos in vars, comments, tests

---

github/strings.go

The PR refactors implementation of the `stringifyValue` function.
`w.Write([]byte("<nil>"))` may allocate, better is to use `w.WriteString("<nil>")`

fix: Avoid allocation in the stringifyValue

---

github/orgs_members.go
github/orgs_members_test.go

The https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#cancel-an-organization-invitation endpoint was not available, and I needed it for some tooling. 
I tried my best to stick to the standards, and added a quick test. 
Happy to update / change anything if required.

Add CancelInvite method to cancel an org invitation by ID

---

github/github_test.go
github/repos_releases_test.go

The PR simplifies the `openTestFile` function logic by leveraging [`T.TempDir`](https://pkg.go.dev/testing#T.TempDir).

refactor: Simplify temp file creation in tests

---

example/commitpr/main.go
github/doc.go
github/examples_test.go
scrape/README.md

The PR replaces outdated `godoc.org` with `pkg.go.dev`.
See https://github.com/golang/go/issues/49212 for details about the deprecated `godoc`.
The badge is created at https://pkg.go.dev/badge/.

docs: Replace godoc.org with pkg.go.dev

---

example/basicauth/main.go
example/codespaces/newreposecretwithxcrypto/main.go
example/codespaces/newusersecretwithxcrypto/main.go
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
example/tagprotection/main.go
example/tokenauth/main.go

The PR proposes removing local variables such as `bytePassword` and `secretBytes` because they do not do not significantly enhance readability.

refactor: Remove redundant local vars in examples

---

github/teams.go
github/teams_test.go

The `newTeamNoParent` struct is the same as `NewTeam` as the comment states. The PR #3111 added `NotificationSetting` field to the `NewTeam` but forgot to add it to the `newTeamNoParent`.

fix: Add missing NotificationSetting to newTeamNoParent

---

README.md

The PR improves formatting in README.md:
- replace outdated `godoc.org` with `pkg.go.dev`;
- set text link for raw URLs;
- replace whitespace with TAB in Go example code;
- add missing `###` for some titles;

docs: Improve formatting in README

---

github/orgs_properties.go

This change will allow a user to set `null` when calling [the create/update repository custom property endpoint](https://docs.github.com/en/enterprise-cloud@latest/rest/repos/custom-properties?apiVersion=2022-11-28#create-or-update-custom-property-values-for-a-repository). As written in the docs, doing so will remove/unset the custom property. Currently doing so is not possible
Normally I think this would count as a breaking change, since this will modify the behavior when omitting the `Value`, but I believe this is a straight up bug, as omitting the `Value` should always result in an error. So there shouldn't be any usages that's relying on this behavior. Technically it's possible, but improbable.

fix: Allow removing/unsetting repository custom property

---

github/projects_test.go
github/teams.go
github/teams_test.go

The PR removes unneeded `strings.Join` function calls. The value of `strings.Join([]string{mediaTypeTopicsPreview}, ", ")` is the same as `mediaTypeTopicsPreview`.

refactor: Remove unneeded strings.Join calls

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_rules.go
github/repos_rules_test.go

This PR will expose fields `CreatedAt` and `UpdatedAt` for `Ruleset`
Closes https://github.com/google/go-github/issues/3315

feat: Add CreatedAt and UpdatedAt to Ruleset

---

example/tokenauth/main.go

The PR replaces `println` with normal `fmt.Println` in the `example/tokenauth`.
`println` is not guaranteed to stay in the language according to [the spec](https://go.dev/ref/spec#Bootstrapping).

refactor: Replace 'println' with 'fmt.Println'

---

.golangci.yml
example/topics/main.go
github/authorizations.go
github/checks.go
github/codesofconduct.go
github/copilot_test.go
github/emojis.go
github/github.go
github/github_test.go
github/issues_labels.go
github/messages.go
github/orgs_members_test.go
github/repos.go
github/repos_contents.go
github/repos_deployments.go
github/search.go
github/timestamp.go
github/users_emails.go
scrape/apps.go
test/integration/audit_log_test.go
tools/metadata/metadata.go

This PR enables `godot` linter to ensure comments always end with a full stop. This is for consistency with other comments and to comply with the guidelines at https://go.dev/wiki/CodeReviewComments#comment-sentences:
> Comments should begin with the name of the thing being described and end in a period

docs: Add dots at the end of sentences

---

scrape/apps_test.go
scrape/forms_test.go
scrape/scrape_test.go

The PR replaces `t.Errorf` with `t.Fatalf` in `scrape` tests where there is no need to continue execution if an `err` occurs. Additionally, it uses `filepath.Join` instead of a hard-coded separator `/`.

scrape: refactor tests with t.Fatal

---

README.md
github/gen-accessors.go
github/gen-stringify-test.go
github/with_appengine.go
github/without_appengine.go
test/integration/activity_test.go
test/integration/audit_log_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/issues_test.go
test/integration/misc_test.go
test/integration/pulls_test.go
test/integration/repos_test.go
test/integration/users_test.go

This PR removes outdated `// +build` comments. The ["Build constraints"](https://pkg.go.dev/cmd/go#hdr-Build_constraints) says:
> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.
**NOTE:** This change breaks compatibility with Go 1.16. The library will compile only with Go 1.17+.

chore: Remove deprecated build constraints

---

github/actions_artifacts.go
github/actions_artifacts_test.go
github/github-accessors.go
github/github-accessors_test.go

Fixes: #3328.
BREAKING CHANGE: `opts` argument to `ActionsService.ListArtifacts` changed from `ListOptions` to `ListArtifactsOptions`.

feat!: Add name query parameter to ActionsService.ListArtifacts

---

github/orgs_rules_test.go
github/repos_rules.go
github/repos_rules_test.go

BREAKING CHANGE: Rename `RuleRequiredCodeScanningTools` to `RuleRequiredCodeScanningTool`.
Some improvements for #3256

feat!: Rename code scanning params from plural to singular

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_rules_test.go
github/repos_rules.go

BREAKING CHANGE: Change `RulesetRepositoryPropertyTargetParameters.Source` from `string` to `*string`.
Our application was failing to apply or update Github Rulesets because of the following error:
```
Invalid property /conditions: data matches no possible input. See `documentation_url`. []
```
Following the release of Go Github v65. Digging into this we saw a change in the following PR #3250.
Looking into the Github REST API the `source` attribute is not listed as required. Thus we also did not implement this on our side. The problem that surfaced was the fact that the property was still being sent to the Github API even though it was empty. 
With this PR we make it optional, a pointer, and i adapted test cases to verify that it is indeed missing when empty.
I tested this with our own …

feat!: Fix `source` property on Repo Custom Properties

---

github/pulls_reviewers.go
github/pulls_reviewers_test.go

Fixes a [JSON marshaling problem](https://github.com/google/go-github/issues/3336#issuecomment-2438435830) that causes spurious 422s when calling RemoveReviewrs with `TeamReviewers` but no `Reviewers`.
The github API requires `"reviewers"`. It permits `"reviewers": []` but not `"reviewers": null`. Try it:
```
echo "Show the problem"
curl -L \                                                            
-X DELETE \   
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer ${PAT}" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/${OWNER}/${REPO}/pulls/${NUMBER}/requested_reviewers \
-d '{"team_reviewers":["the_senate"]}' 
{
"message": "Invalid request.\n\n\"reviewers\" wasn't supplied.",
"documentation_url": …
```

Allow RemoveReviewers to remove only teams

---

github/github-accessors.go
github/github-accessors_test.go
github/secret_scanning.go

Modify `SecretScanningAlertLocationDetails` to recognize API responses of type `pull_request_comment_url`.
Per the documentation available here:
https://docs.github.com/en/rest/secret-scanning/secret-scanning?apiVersion=2022-11-28
For requests to this route:
```
curl -L \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer <YOUR-TOKEN>" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/OWNER/REPO/secret-scanning/alerts/ALERT_NUMBER/locations
```
The API may return JSON that matches the following shape:
```javascript
// ...
{
"type": "pull_request_comment",
"details": {
"pull_request_comment_url": "https://api.github.com/repos/octocat/Hello-World/issues/comments/1825855898"
}
},
// ...
```
(I'm sorry I can't provide a more specific link. The docs don't …

feat(secret scanning): Support `pull_request_comment_url`

---

github/apps.go
github/github-accessors.go
github/github-accessors_test.go

Added permissions:
- repository_custom_properties
- repository_advisories
- merge_queues
- discussions
- dependabot_secrets
- codespaces_secrets
- codespaces_metadata
- codespaces_lifecycle_admin
- codespaces

Add missing permissions to struct

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

The `workflow_job` webhook event as described by GitHub documentation contains a `deployment` object. 
https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job
However, the struct that defines the `workflow_job `webhook event type is missing the `deployment` object . This PR adds the missing object to the `WorkflowJobEvent` type.

Add missing Deployment field to workflow_job event type

---

github/apps.go
github/github-accessors.go
github/github-accessors_test.go

Added permissions:
- attestations
- codespaces_user_secrets
- copilot_messages
- gists
- git_signing_ssh_public_keys
- gpg_keys
- interaction_limits
- keys (git ssh keys).
- organization_actions_variables
- organization_announcement_banners
- organization_api_insights
- organization_codespaces
- organization_codespaces_secrets
- organization_codespaces_settings
- organization_copilot_seat_management (GitHub Copilot Business)
- organization_dependabot_secrets
- organization_events
- organization_knowledge_bases
- plan
- profile
- starring
- user_events
- watching

Map more missing installation permissions

---

github/github.go
github/github_test.go

Fix: Preserve HTTP Response in URL Errors
Fixes #3362
This PR improves error handling in the BareDo method to properly preserve HTTP response information when encountering *url.Error. Changes include:
- Move response creation earlier to avoid code duplication
- Add proper nil response handling
- Preserve HTTP response information in URL errors
- Add test case TestDo_preservesResponseInURLError
The changes allow users to access HTTP status codes (like 404) even when encountering URL errors.
This PR was created with help from Devin: https://preview.devin.ai/sessions/1b2f7ce6e3b44942b3ac1f518eac7c22

Fix: Preserve HTTP Response in URL Errors

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/teams.go
github/users.go

Resolves #3364
This PR adds the `Assignment` field to `Team` & `User` and the `InheritedFrom` field to `User` when accessed in the context of an organization role.

feat: Add assignment for org role associations

---

github/teams.go

Resolves #3368
This PR makes all legacy ID based team methods as deprecated based on the [closing down notice](https://docs.github.com/en/enterprise-cloud@latest/rest/teams/teams?apiVersion=2022-11-28#get-a-team-legacy).

chore: Deprecate legacy ID-based team methods

---

github/github-accessors.go
github/github-accessors_test.go
github/secret_scanning.go
github/secret_scanning_test.go

Support to an optional comment when closing an alert
Per the documentation available here:
https://docs.github.com/en/rest/secret-scanning/secret-scanning?apiVersion=2022-11-28#update-a-secret-scanning-alert

feat: Support resolution_comment to update alert API

---

github/orgs_custom_repository_roles.go
github/orgs_custom_repository_roles_test.go

Resolves #3370 
This PR adds the missing `GetCustomRepoRole` function.

feat: Add get for custom org repo role

---

AUTHORS
github/enterprise_properties.go
github/enterprise_properties_test.go

This PR adds enterprise scoped [custom properties](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/custom-properties?apiVersion=2022-11-28).
> [!NOTE]
> This API endpoint is currently still in preview.

feat: Add enterprise custom properties

---

.golangci.yml
github/github.go

The PR enables the `canonicalheader` linter and changes header key strings to be in canonical form.
This is needed because canonical header keys don't need to be converted to a canonical form via [http.CanonicalHeaderKey](https://pkg.go.dev/net/http#CanonicalHeaderKey), leading to fewer allocations when adding, setting or getting a header.
<details>
<summary>Benchmarks</summary>
```go
func BenchmarkCanonical(b *testing.B) {
v := http.Header{
"Canonical-Header": []string{"hello_world"},
}
b.ReportAllocs()
b.ResetTimer()
for i := 0; i < b.N; i++ {
s := v.Get("Canonical-Header")
if s != "hello_world" {
b.Fatal()
}
}
}
func BenchmarkNonCanonical(b *testing.B) {
v := http.Header{
"Canonical-Header": []string{"hello_world"},
}
b.ReportAllocs()
b.ResetTimer()
for i := 0; i < b.N; i++ {
s := …
```

refactor: Change header keys to be canonical

---

.golangci.yml
github/orgs_codesecurity_configurations_test.go

This is found with `gci`, so I enabled this linter in golangci-lint's config.

chore: Sort std imports

---

github/issues_timeline.go
github/issues_timeline_test.go

Updates the Timeline struct documentation to include review request-related events that were missing from the Event field description, matching the GitHub API behavior.
- Added documentation for `review_requested` event
- Occurs when an actor requests a review from a user/team
- Notes that `Requester` or `RequestedTeam` will be populated
- `Reviewer` will be populated
- Added documentation for `review_request_removed` event
- Occurs when an actor removes a review request
- `Reviewer` will be populated
- Notes that `Requester` or `RequestedTeam` will be populated
These events were already supported in the implementation via the corresponding struct fields, but were missing from the Event field's documentation.
- Ran the test suite locally to ensure all changes are functioning as expected. …

feat: Document review request events in `Timeline` struct

---

github/git_commits.go
github/git_commits_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_commits_test.go
github/repos_contents_test.go

BREAKING CHANGE: The unused `Stats` field is removed from the `Commit` struct.
This field appears to never be populated throughout the codebase.
Closes #3394

fix!: Remove unused `Stats` field from  `Commit` struct

---

github/repos_releases.go
github/repos_releases_test.go

This fixes issue #3081, such that `Repositories.DownloadReleaseAsset` correctly handles scenarios where a non-`nil` `followRedirectsClient` argument has been passed, and the specified repository has been renamed to a new name.
Previously, in such scenarios...
1. The initial `GET /repos/<OWNER>/<REPO>/releases/assets/<ASSET ID>` responds 301 w/ a `Location: <GH API HOST>/repositories/<REPO ID>/releases/assets/<ASSET ID>`.
2. The `followRedirectsClient` issues a `GET <GH API HOST>/repositories/<REPO ID>/releases/assets/<ASSET ID>` with a `Accept: */*` header.
3. `GET <GH API HOST>/repositories/<REPO ID>/releases/assets/<ASSET ID>` responds 200 with a JSON response body (rather than 302 w/ a `Location: <MEDIA SERVER ASSET URL>` header) due to the presence of the `Accept: */*` header (and the …

fix: DownloadReleaseAsset handles renamed repository

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_personal_access_tokens.go

According to REST API: https://docs.github.com/en/rest/orgs/personal-access-tokens?apiVersion=2022-11-28#list-fine-grained-personal-access-tokens-with-access-to-organization-resources
There are some fields which are not getting captured by PersonalAccessToken struct. The fields are:
token_id
token_name
For issue: https://github.com/google/go-github/issues/3403

Update PersonalAccessToken struct

---

README.md
example/go.mod
example/newreposecretwithlibsodium/go.mod
go.mod
scrape/go.mod
script/test.sh
tools/go.mod

Bump Go to 1.22.10 or 1.23.4 in go.mod files

---

github/actions_artifacts.go
github/actions_artifacts_test.go
github/actions_workflow_jobs.go
github/actions_workflow_jobs_test.go
github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/github.go
github/github_test.go
github/repos_contents.go
github/repos_contents_test.go

Fixes #3406
Some endpoints of the GitHub HTTP API return a 302 response in successful scenarios, often to redirect to archives or artifacts download links. Because the `net/http` client usually follows 302s when calling `Do`, we instead currently use the `RoundTripper` directly for those endpoint to check after each call if the current redirection is a 302. The problem is that the library supports rate limit headers only in the `Do` type of calls.
This PR adds an opt-in feature flag to enable rate limit headers support on those endpoints which end with a 302 redirection. I refactored `Client` a bit to share the core `BareDo` logic between calls that care about redirection details and calls that don't. I added an unexported `bareDoUntilFound` method that behaves similarly to the old …

Add opt-in rate limit support on endpoints returning 302s

---

.github/dependabot.yml
.github/workflows/linter.yml
.github/workflows/tests.yml

Tell dependabot to group updates to the official actions owned by GitHub under the [actions](/actions/org) into a single PR and update the workflows to pin to explicit digests tracked to individual version numbers rather than just the major tag

build(deps): Pin and group actions/*

---

github/orgs_security_managers.go

The [organization security manager role REST APIs](https://docs.github.com/en/rest/orgs/security-managers) are being sunset (https://gh.io/security-managers-rest-api-sunset) in favor of the [organization roles REST APIs](https://docs.github.com/en/rest/orgs/organization-roles).
This change adds deprecation messages to tell consumers which client operations to use instead going forward.

Add deprecation messages to security managers APIs

---

script/generate.sh

@dnwe - does this seem like a reasonable change for the use of all developers in this repo?

Enforce toolchain requirement in generate.sh

---

CONTRIBUTING.md
REVIEWERS

This PR adds a _REVIEWERS_ file and updates the contributing guide to reference it. 
Fixes #3434

chore: Add reviewers file

---

github/gen-accessors.go

After merging this PR, the checks for #3433 will become green (I checked [here](https://github.com/alexandear/go-github/pull/6)).
The PR addresses the issue described in https://github.com/google/go-github/pull/3433#issuecomment-2596182213: we need to guarantee the order of equal getters.
```go
func (s *SMTP) GetUsername() string {
if s == nil || s.Username == nil {
return ""
}
return *s.Username
}
// GetUserName returns the UserName field if it's non-nil, zero value otherwise.
func (s *SMTP) GetUserName() string {
if s == nil || s.UserName == nil {
return ""
}
return *s.UserName
}
```

gen-accessors: update dumping of getters

---

.github/workflows/tests.yml

This PR updates the Codecov action to use native GH OIDC support to authenticate pushing coverage from the `master` branch.
Fixes: #3439.
Closes: #3221.

chore: Fix codecov upload

---

.golangci.yml
github/code_scanning.go
github/github.go
github/pulls_reviewers_test.go
github/repos_contents.go
github/timestamp.go

The PR updates comments and error messages to use `unmarshal` with one *el*. Also, configures `misspell` linter to detects this in the future.
See https://go.dev//wiki/Spelling

chore: Spell "unmarshal" consistently with one el

---

example/verifyartifact/main.go
github/github.go
github/repos_deployments_test.go
github/teams_discussion_comments.go

The PR corrects grammar mistakes. Changing the parameter name in `CreateCommentBySlug` is backward-compatible.

fix: Typos in func parameter, vars, error, and comments

---

github/checks.go
github/checks_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go

BREAKING CHANGE: `Rerequstable`=>`Rerequestable`, `RunsRerequstable`=>`RunsRerequestable`
Fixes: #3443.

fix!: Typo in field names in the CheckSuite struct

---

github/admin_stats.go
github/admin_stats_test.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go

BREAKING CHANGE: `MergablePulls`=>`MergeablePulls`, `UnmergablePulls`=>`UnmergeablePulls`
This PR corrects field typos in the [`github.PullStats`](https://github.com/google/go-github/blob/v68.0.0/github/admin_stats.go#L126-L127) struct:
- `MergablePulls` -> `MergeablePulls` (because `json:"mergeable_pulls"`)
- `UnmergablePulls` -> `UnmergeablePulls` (because `json:"unmergeable_pulls"`)

fix!: Typo in field names in the PullStats struct

---

.golangci.yml
example/codespaces/newreposecretwithxcrypto/main.go
example/codespaces/newusersecretwithxcrypto/main.go
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
github/github.go
github/github_test.go
github/repos_rules.go

BREAKING CHANGE: Some error strings are slightly modified - please do not rely on error text in general.
This PR is somewhat of a breaking change because it changes error messages for `Client.NewRequest`, `Client.NewFormRequest`, and `Client.NewUploadRequest`. However, I'm not sure if anyone relies on the word case of an error message.
The PR also configures golangci-lint to detect this in the future.
`revive.error-strings` was already enabled in the lint config but didn't work until we set `confidence: 0.6` in this PR.

refactor!: Do not capitalize error strings

---

github/enterprise_manage_ghes.go
github/enterprise_manage_ghes_config.go
github/enterprise_manage_ghes_config_test.go
github/enterprise_manage_ghes_maintenance.go
github/enterprise_manage_ghes_maintenance_test.go
github/enterprise_manage_ghes_ssh.go
github/enterprise_manage_ghes_ssh_test.go
github/enterprise_manage_ghes_test.go
github/github-accessors.go
github/github-accessors_test.go

feat: Add manage_ghes endpoints introduced in 3.15

---

.golangci.yml
github/admin_stats_test.go
github/enterprise_audit_log_test.go
github/gists.go
github/orgs_audit_log_test.go
github/pulls_reviewers.go
scrape/apps_test.go
scrape/example/scrape/main.go
scrape/forms_test.go
scrape/scrape_test.go

Add `goheader` to check the file header license.

chore: Check and fix license headers

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/issues.go

Add new fields for Issues Type. In the Rest API this is not available yet when getting an issue information, but that is available in an issue event (webhook)
This is a new feature for issues: https://github.com/orgs/community/discussions/139933
Will be good to have this available in the lib to people can use when dealing with events :)
Fixes: https://github.com/google/go-github/issues/3450
cc @gmlewis

Add new fields for IssueType

---

github/github-stringify_test.go
github/github.go
github/github_test.go
github/rate_limit.go
github/rate_limit_test.go

GitHub introduced two new headrs when it comes to rate limiting:
* `X-Ratelimit-Used`
* `X-Ratelimit-Resource`
See https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#checking-the-status-of-your-rate-limit
For which resources are available, see https://docs.github.com/en/rest/rate-limit/rate-limit?apiVersion=2022-11-28#get-rate-limit-status-for-the-authenticated-user
This Pull Request extends the Rate Limiting Header parsing and adds the two new information into the `Rate` response.
Additionally, the key `used` is added into the response from the `/rate_limit` API endpoint.
For the `Rate` type, the docs have been updated according to the original GitHub API docs.

Extend `Rate` and Rate Limiting with `X-Ratelimit-Used` and `X-Ratelimit-Resource` headers

---

github/pulls.go

The docs for `ListPullRequestsWithCommit` mention use of `PullRequestListOptions`, but this method no longer accepts `PullRequestListOptions` per #2815 and #2822.
This pull request updates the method doc comment to remove the outdated reference to `PullRequestListOptions`, and adds some clarifications based on the GitHub docs for the relevant API endpoint.

docs: Clarify ListPullRequestsWithCommit usage

---

README.md
github/orgs_packages_test.go
github/repos_commits_test.go
github/repos_contents_test.go
github/repos_test.go
script/test.sh

Use correct url escaping to fix the errors caused by mux changes.
Fixes: #3409

fix: go 1.22 test breakage

---

README.md
github/doc.go

See #3468 for more discussion/details.
Fixes: #3468.

feat: Add link to bored-engineer/github-conditional-http-transport to conditional requests documentation

---

README.md

Before this change the most recent run from any branch was used for the badge, which could have been a failed run on a branch (for example earlier today the most recent run was https://github.com/google/go-github/actions/runs/13250097376/job/36985764795 and the readme showed the test status as failing).

chore: Only use master test runs for status badge

---

github/code_scanning.go
github/code_scanning_test.go

As per the official documentation the endpoints to list alerts for both an organization and a repository accept three additional params which are not included in this SDK. Those are: `tool_guid`, `direction` and `sort`.
See:
- https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#list-code-scanning-alerts-for-an-organization
- https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#list-code-scanning-alerts-for-a-repository
This PR adds those fields and extends the tests to cover them as well.

fix: Add missing query params to AlertListOptions

---

example/go.mod
example/newreposecretwithlibsodium/go.mod
github/github.go
tools/go.mod

This minor release contains the following changes:
* #3464
* #3438
* #3465
* #3459
* #3469
* #3472
* #3470
* #3471
* #3474
* #3475
* #3467
* #3477

Bump version of go-github to v69.1.0

---

github/dependabot_alerts_test.go

This PR adds some more tests for issue #55. Would appreciate a review!
Also noticed that some fields in the Github API response such as `cvss_severities` and `epss` are not supported in the existing struct. Is this expected (deprecated fields) or just new fields in the Github response that haven't been reflected in the current codebase yet? 
Thanks in advance!

feat: Add JSON marshal tests for dependabot alerts

---

github/secret_scanning.go
github/secret_scanning_test.go

Similar to https://github.com/google/go-github/pull/3477 this adds the missing sorting options from the `SecretScanningAlertListOptions` struct.
These options are available in the [list-secret-scanning-alerts-for-a-repository](https://docs.github.com/en/rest/secret-scanning/secret-scanning?apiVersion=2022-11-28#list-secret-scanning-alerts-for-a-repository) endpoint and the respective ones for orgs and enterprises.

feat: Add sorting list options for secret scanning

---

example/go.sum
example/newreposecretwithlibsodium/go.sum
go.mod
go.sum
scrape/go.mod
scrape/go.sum

Bump github.com/google/go-cmp from 0.6.0 to 0.7.0

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_pages.go
github/repos_pages_test.go

This PR fixes an issue with the UpdatePages method, which caused the error: "400 Custom domains are not available for GitHub Pages" on GHES. The issue occurred because the update struct didn't specify the omitempty tag for JSON marshalling, which resulted in explicit null values being sent. As a result, GHES returned the error.
To resolve this, the fix adds a check for the client URL. If the URL differs from the public GitHub API, a new struct is created without the CNAME field to avoid sending null values.
Question: Should we add the omitempty tag directly to the CNAME field of the PagesUpdate struct instead of this workaround?
References:
- Issue: https://github.com/google/go-github/issues/3466
Fixes: #3466.

fix: Resolve '400 Custom domains' error on GitHub Enterprise Server

---

github/github.go
github/github_test.go

the callbackURL from the event previously didn't match with the regex, and was always causing a "no match found error".  This includes the full URL and should match.

Correct the `runIDFromURLRE` regex to properly match the callbackURL

---

github/enterprise_network_configurations.go
github/enterprise_network_configurations_test.go
github/github-accessors.go
github/github-accessors_test.go

This pull request introduces support for the hosted compute network configurations  in the go-github library, addressing https://github.com/google/go-github/issues/3462.
Changes Include:
Implementation of API endpoints for managing network-configuration endpoints.
Support for the following operations:
* Get, Create, Update, Delete and List network-configuration of an enterprise.
* Get network settings resource.
* Corresponding unit tests for each function.
Additional Information:
API Reference: [GitHub REST API: Network Configurations](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/network-configurations?apiVersion=2022-11-28).

feat: Add support for network-configurations endpoints

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/reactions.go

This pull request exposes the `created_at` field for [reactions](https://docs.github.com/en/rest/reactions/reactions?apiVersion=2022-11-28).

Add created_at field to Reaction

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

Fixes: #3507.
I am submitting this as a Block (Square) employee. Block has signed the Google Corporate CLA
q

Add reason parameter to MergeGroupEvent

---

github/reactions.go
github/reactions_test.go

BREAKING CHANGE: `ListCommentReactionOptions` => `ListReactionOptions` and all `List*Reactions` methods now use it.
All list reactions endpoint now suppor the `content` query parameters to filter the returned results by content (`+1`, `eyes`, etc.). Including:
- [List reactions for a commit comment](https://docs.github.com/rest/reactions/reactions#list-reactions-for-a-commit-comment)
- [List reactions for an issue](https://docs.github.com/rest/reactions/reactions#list-reactions-for-an-issue)
- [List reactions for an issue comment](https://docs.github.com/rest/reactions/reactions#list-reactions-for-an-issue-comment)
- [List reactions for a pull request review comment](https://docs.github.com/rest/reactions/reactions#list-reactions-for-a-pull-request-review-comment)
- [List reactions for a …

feat!: Add ListReactionOptions to all ListxxReactions functions to enable filter by content

---

github/reactions.go
github/reactions_test.go

Following up on changes in https://github.com/google/go-github/pull/3532
This PR adds `List` and `Delete` functionality to reactions associated with a release

Add ListReleaseReactions and DeleteReleaseReaction 

---

github/meta.go
github/meta_test.go

added ActionsMacOs to APIMeta struct for https://github.com/google/go-github/issues/3534 
Fixes: #3534.

feat: Add actions_macos field to APIMeta struct

---

github/github_test.go

This PR addresses an issue where parallel tests share the default HTTP transport, leading to intermittent "connection broken" errors due to race conditions in connection reuse.  
Tests create their own clients and servers via `setup(t)`, but they unintentionally share Go's default transport when no explicit transport is specified. As a result:  
- `server.Close()` triggers `CloseIdleConnections()` on the default transport.  
- This closes all idle connections, affecting other tests running in parallel.  
- If another test is in the middle of using a connection from the shared pool, it encounters a "connection broken" error.  
- Ensure each test uses an **isolated HTTP transport** instead of the shared default transport.  
- This prevents unintended connection closures from affecting other …

fix: Isolate HTTP transports in parallel tests to prevent connection issues

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/packages.go
github/packages_test.go

Hi,
As mentioned in the [previous reply](https://github.com/google/go-github/pull/3515#issuecomment-2783162924), the `Repository` field was mistakenly removed in `Package` strcuture.
This PR aims to reintroduce it.
cc @gmlewis

fix: Add back repository field in Package struct

---

.github/workflows/tests.yml

Reverts google/go-github#3551 which is causing problems with our builds.

Revert "build(deps): bump codecov/codecov-action from 5.4.0 to 5.4.2"

---

github/repos_hooks_deliveries.go
github/repos_hooks_deliveries_test.go

Simple implementation for case-insensitive GetHeader. I thought about caching the keys, but it seems too complicated for now with additional not predictable memory consumption. Tests are included.
Fixes #3555

Add case-instensitive GetHeader for HookRequest & HookResponse

---

github/enterprise_rules_test.go
github/event_types_test.go
github/orgs_rules_test.go
github/rules.go
github/rules_test.go

BREAKING CHANGE: `MergeMethod*` consts have been split into: `PullRequestMergeMethod*` and `MergeQueueMergeMethod*`.
Fixes: #3558
This issue will cause GitHub API return error if user use type MergeMethod in  MergeQueueRuleParameters.MergeMethod: 
```
422 Invalid request. Invalid property /rules/0: data matches no possible input. See `documentation_url`. []
```

fix!: Differentiate merge method of pull request and merge queue

---

github/github-accessors.go
github/github-accessors_test.go
github/issues.go
github/issues_test.go

With he new field for Issue Type, we can also update that field in the edit method, adding that to be able to use it.
updating the tests to add that as well
https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue
cc @gmlewis

Add issue `Type` to `IssueRequest`

---

github/repos_contents.go
github/repos_contents_test.go

Fixes: #3566. 
By parsing the content field from the response, we can retrieve the most recent state of the file without making an additional request. Only when the content field is empty—such as [for object format and files exceeding the 1 MB ](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content) limit (see GitHub API docs) — do we fall back to the previous approach, which involves directory parsing and fetching the content via download_url or as raw data.
Additional tests were added to cover various cases.

Improve DownloadContents and DownloadContentsWithMeta methods

---

README.md

Because https://github.com/google/go-github/blob/3c5408e78f96138f004621711cac62db14ea030e/go.mod#L3

docs: Update minimum Go version in README to 1.23

---

github/doc.go
github/github.go
github/messages.go

Tested links locally:
```console
❯ pkgsite .
2025/06/09 15:27:36 Info: go/packages.Load(["all"]) loaded 189 packages from . in 157.503625ms
2025/06/09 15:27:36 Info: go/packages.Load(std) loaded 344 packages from /opt/homebrew/Cellar/go/1.24.3/libexec in 404.353584ms
2025/06/09 15:27:36 Info: FetchDataSource: fetching github.com/google/go-github/v72@v0.0.0
2025/06/09 15:27:36 Info: FetchDataSource: fetching std@latest
2025/06/09 15:27:36 Info: Listening on addr http://localhost:8080
2025/06/09 15:27:37 Info: FetchDataSource: fetched std@latest using *fetch.goPackagesModuleGetter in 215.236334ms with error <nil>
2025/06/09 15:27:37 Info: FetchDataSource: fetched github.com/google/go-github/v72@v0.0.0 using *fetch.goPackagesModuleGetter in 563.621917ms with error <nil>
```
Open in a browser …

docs: Use pkgsite links

---

github/issues.go
github/repos_test.go
scrape/forms_test.go

The PR fixes typos found with the help of [typos](https://github.com/crate-ci/typos) and [codespell](https://github.com/codespell-project/codespell).

chore: Correct typos in comments and tests error messages

---

github/github-accessors.go
github/github-accessors_test.go
github/scim.go
github/scim_test.go

BREAKING CHANGE: `ListSCIMProvisionedGroupsForEnterprise` now takes `ListSCIMProvisionedGroupsForEnterpriseOptions` instead of `*ListSCIMProvisionedIdentitiesOptions`.
This PR fixes two issues:
1) The options in `ListSCIMProvisionedGroupsForEnterprise` were not beeing handled.
2) `ListSCIMProvisionedIdentitiesOptions` was missing the `excludedAttributes` property.
See https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/scim?apiVersion=2022-11-28#list-provisioned-scim-groups-for-an-enterprise--parameters

fix!: Add ListSCIMProvisionedGroupsForEnterpriseOptions

---

github/migrations.go
github/migrations_test.go

Implements https://github.com/google/go-github/issues/3597
Add support for two options of the migrate organization endpoint:
- `ExcludeReleases`
- `Exclude`
```
func Test_ExcludeRepositories(t *testing.T) {
client := github.NewClient(nil).WithAuthToken("GITHUB_AUTH_TOKEN")
m, _, err := client.Migrations.StartMigration(context.Background(), "GITHUB_ORG", []string{"GITHUB_ORG_REPO"}, &github.MigrationOptions{
Exclude: []string{"repositories"},
})
assert.NoError(t, err)
assert.Empty(t, m.Repositories)
}
```
```
func Test_ExcludeReleases(t *testing.T) {
client := github.NewClient(nil).WithAuthToken("GITHUB_AUTH_TOKEN")
m, _, err := client.Migrations.StartMigration(context.Background(), "GITHUB_ORG", []string{"GITHUB_ORG_REPO"}, &github.MigrationOptions{
ExcludeReleases: true,
}) …
```

feat: Add organization migration options

---

github/apps_installation.go
github/apps_installation_test.go

The PR removes no longer needed preview "Accept" headers in `AppsService.ListRepos` and `AppsService.ListUserRepos`.
https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#list-repositories-accessible-to-the-app-installation--parameters
https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#list-app-installations-accessible-to-the-user-access-token--parameters

fix: Remove custom Accept in Apps.ListRepos and Apps.ListUserRepos

---

github/copilot.go
github/copilot_test.go

Resolves #3616  
- **Fixed `UnmarshalJSON` method** in `copilot.go`:
- Added a `case nil:` branch to handle `null` `assignee` values.
- Sets `cp.Assignee = nil` when `assignee` is `null`, instead of returning an error.
- **Updated `copilot_test.go`**:
- Added a unit test case `"Null Assignee"` to ensure the `assignee: null` scenario is handled correctly and no error is thrown.
The current implementation of `UnmarshalJSON` for `CopilotSeatDetails` throws an error when the `assignee` field is `null`, even though the [GitHub API documentation](https://docs.github.com/en/rest/copilot/copilot-user-management?apiVersion=2022-11-28#list-all-copilot-seat-assignments-for-an-organization) explicitly states that `assignee` can be `null`.

fix: Handle null assignee in Copilot Seat Billing API response

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

Adds the `require_last_push_approval` field in order to be returned as part of the webhook payload object for `branch_protection_rule` as documented [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=created#branch_protection_rule).
It's being added to both the `ProtectionChanges` and `BranchProtectionRule` to account for the `created` and `edited` action types of the webhook.
_For context_:
- in https://github.com/google/go-github/pull/2567 the `require_last_push_approval` field was added originally
- request for addition of ☝🏼 field: https://github.com/google/go-github/issues/2574

fix: Add missing `require_last_push_approval` field to branch protection rule event structs

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_releases.go

Close #3627
https://github.blog/changelog/2025-06-03-releases-now-expose-digests-for-release-assets/
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release
The `Get a Release` API returns digests of assets.
To get digests, this commit adds the field `Digest` and the method `GetDigest` to `ReleaseAsset`.

feat: Add the `Digest` field to `ReleaseAsset`

---

github/checks.go
github/checks_test.go
github/github-accessors.go
github/github-accessors_test.go

BREAKING CHANGE: Change `ListCheckSuiteOptions.AppID` from `int` to `int64`
Fixes: #3631

fix!: Change `ListCheckSuiteOptions.AppID` from `int` to `int64`

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs.go

This PR adds a number of new fields to the Organization struct that are available when getting an org via the REST API. They can be seen in the [sample response](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#get-an-organization) in the GitHub documentation.
```
"default_repository_branch": "main",
```
```
"members_can_delete_repositories": true,
"members_can_change_repo_visibility": true,
"members_can_invite_outside_collaborators": true,
"members_can_delete_issues": false,
"display_commenter_full_name_setting_enabled": false,
"readers_can_create_discussions": true,
"members_can_create_teams": true,
"members_can_view_dependency_insights": true,
```

Add additional settings fields to org API

---

README.md
example/commitpr/main.go

To avoid seeing the notice "The highest tagged major version is v74":

docs: Update links to use the latest version of github documentation

---

.golangci.yml
example/codespaces/newreposecretwithxcrypto/main.go
example/codespaces/newusersecretwithxcrypto/main.go
example/newreposecretwithlibsodium/main.go
example/newreposecretwithxcrypto/main.go
github/actions_workflow_runs.go
github/git_blobs.go
github/git_commits.go
github/git_refs.go
github/git_tags.go
github/git_trees.go
github/github_test.go
github/issues.go
github/issues_comments.go
github/issues_labels.go
github/issues_milestones.go
github/orgs_outside_collaborators.go
github/orgs_users_blocking.go
github/pulls.go
github/repos.go
github/repos_commits.go
github/repos_keys.go

This PR combines function parameters by type (with the help of [gocritic.paramTypeCombine](https://go-critic.com/overview.html#paramtypecombine)). See https://github.com/google/go-github/pull/3654#discussion_r2236676684

refactor: Fix gocritic.paramTypeCombine lint issues

---

CONTRIBUTING.md
github/actions_artifacts_test.go
github/actions_workflow_jobs_test.go
github/actions_workflow_runs_test.go
github/dependabot_alerts_test.go
github/meta.go
github/orgs_audit_log.go
github/repos_contents_test.go
github/repos_hooks_test.go

This PR replaces `http://` with `https://` where possible.

docs: Use secure URLs in string literals

---

script/generate.sh

Because the minimum supported version is go 1.23.0

chore: Do not force Go 1.22.0 as toolchain version

---

github/orgs_rules_test.go
github/rules.go

Add exempt as bypass mode to ruleset bypass actors

---

github/repos_rules_test.go

As asked in #3727, here's a test to ensure bypass_actors is never serialized as null when clearing bypass actors.
Test is failing prior to the fix and passes with the current implementation.
Validates #3726

test: Ensure bypass_actors serializes as an empty array when clearing ruleset bypass actors

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

- Add Reason *string field to PullRequestEvent struct
- Update tests to include new field in JSON marshaling
- Generate accessor method GetReason() with corresponding tests
- Field is populated in 'dequeued' event deliveries
- Fixes: https://github.com/google/go-github/issues/3729

Add `reason` field to `PullRequestEvent`

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_codesecurity_configurations.go
github/orgs_codesecurity_configurations_test.go

BREAKING CHANGE: GetRepositoriesForCodeSecurityConfiguration now returns RepositoryAttachment instead of Repository.
Adds type RepositoryAttachment for GetRepositoriesForCodeSecurityConfiguration
Fixes unmarshal error in GetRepositoriesForCodeSecurityConfiguration, as described in #3217.
(I submitted the PR under my corporate GitHub user, but I could not get a proper google/CLA so using my personal user.)

fix!: Return `RepositoryAttachment` from `GetRepositoriesForCodeSecurityConfiguration`

---

example/actionpermissions/main.go
github/actions_permissions_enterprise.go
github/actions_permissions_enterprise_test.go
github/actions_permissions_orgs.go
github/actions_permissions_orgs_test.go
github/orgs_actions_allowed.go
github/orgs_actions_allowed_test.go
github/orgs_actions_permissions.go
github/orgs_actions_permissions_test.go
github/repos_actions_allowed_test.go
github/repos_actions_permissions.go
github/repos_actions_permissions_test.go

BREAKING CHANGE: Permissions-related methods are renamed from `Edit*` to `Update*`.
Rename the methods `EditXXX` to `UpdateXXX` for the permissions related apis
accomplish https://github.com/google/go-github/pull/3679#discussion_r2281878877

refactor!: Replace `Edit` with `Update` in permissions method names

---

.gitignore

ignore settings files like `.claude/settings.local.json` for claude code usage

chore: Ignore hidden `.claude` settings folder

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/repos_releases.go
github/repos_releases_test.go

https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/immutable-releases
Closes https://github.com/google/go-github/issues/3720
Caveat: untested beyond test suite.

feat: Immutable releases support

---

.golangci.yml

mentioned https://github.com/google/go-github/pull/3739#issuecomment-3341026988

ci: Add `errorlint` configuration to golangci-lint settings

---

test/integration/activity_test.go
test/integration/audit_log_test.go
test/integration/github_test.go
test/integration/misc_test.go
test/integration/repos_test.go
test/integration/users_test.go

This PR refactors integration tests:
- Refactor `checkAuth` function in by passing `*testing.T` parameter and renaming for clarity.
- Simplifying `client` and `auth` initialization by using [`sync.OnceValues`](https://pkg.go.dev/sync#OnceValues).
- Fix `TestAPIMeta` which fails if run without OAuth token.
<details><summary>Running integration tests locally</summary>
<p>
`TestAPIMeta` without token:
```console
❯ go test -tags=integration -count=1 -v -run=TestAPIMeta ./test/integration/...
=== RUN   TestAPIMeta
--- PASS: TestAPIMeta (0.28s)
PASS
ok      github.com/google/go-github/v75/test/integration        0.860s
```
`TestAPIMeta` with token:
```console
❯ GITHUB_AUTH_TOKEN=ghp_... go test -tags=integration -count=1 -v -run=TestAPIMeta ./test/integration/...
=== RUN   TestAPIMeta
--- PASS: …
```

test: Simplify the function that skips integration tests

---

github/secret_scanning_pattern_configs_test.go

**Issue**:  Existing test cases for TestSecretScanningService_ListPatternConfigsForOrg, TestSecretScanningService_UpdatePatternConfigsForEnterprise, TestSecretScanningService_UpdatePatternConfigsForOrg method in secret_scanning_pattern_configs_test.go file were not executing the actual test cases, because the test cases were written inside the handler logic .  This issue lead to only 25% of code coverage.
**Resolution** : As a fix, moved the test cases out of handler logic , which called all the test cases of the functions(TestSecretScanningService_ListPatternConfigsForOrg, TestSecretScanningService_UpdatePatternConfigsForEnterprise,TestSecretScanningService_UpdatePatternConfigsForOrg) leading to 100% of code coverage.
Code coverage percentage before this fix:
Code coverage percentage …

test: Fix issues in `TestSecretScanningService` tests

---

.github/dependabot.yml

I think, @dependabot should handle packages in the `example`: https://github.com/google/go-github/blob/68b82b5bb174a85d6ed23108ee0cde4cf6ead589/example/go.mod#L5-L15.

chore(ci): Add example dir to dependabot config
