github/event_types.go
github/git_commits.go
github/repos_deployments.go

Change-Id: Ia4888efa18c557a31af7093cfa449a67650afa20

go-github: add useful fields to Webhooks

---

tests/README.md
tests/integration/activity_test.go
tests/integration/issues_test.go
tests/integration/misc_test.go
tests/integration/pulls_test.go
tests/integration/repos_test.go
tests/integration/users_test.go

Fixes #311.
Change-Id: I334b9e22e748d96a62b0c7f59690c1a998a3c802

Block running integration tests by default

---

github/github.go
github/github_test.go

Fixes #306.
Change-Id: I3b42c946f8255e165c3bbd83b1566675d21fb0e8

Add support for 451 status code

---

github/activity.go
github/activity_test.go

Fixes #191.
Change-Id: I2fbcca9913cd20df75e9b5a5272a50879025d526

Add support for Feeds API

---

github/orgs.go
github/orgs_test.go

Fixes #215.
Change-Id: Ic17192cc0b1dbe02745e4c7f76bd81457f73141a

add support for new list all orgs method

---

github/github.go
github/repos_deployments.go
github/repos_deployments_test.go

Fixes #328.
Change-Id: I2f93fb89eb46e9d341e9a9aada8de1b3339d1ffd

add support for Deployment and DeploymentStatus API enhancements

---

github/event_types.go

See blog post for more information:
https://developer.github.com/changes/2016-04-18-new-webhook-actions-are-live/
Fixes #339.
Change-Id: Iec93b108e86e5aa8662d160567ee136eedea9700

add support for new webhook changes

---

github/github.go
github/migrations_source_import.go
github/migrations_source_import_test.go

Add support for the Source Import API

---

github/github.go
github/issues.go
github/issues_comments.go
github/issues_comments_test.go
github/issues_test.go
github/pulls_comments.go
github/pulls_comments_test.go
github/reactions.go
github/reactions_test.go
github/repos_comments.go
github/repos_comments_test.go

Fixes #356.
Change-Id: Iecc8d7d7c11a8ce9ed38c6d024683815495cb8b4

add support for Reactions API

---

github/reactions.go
github/reactions_test.go

Reactions API now includes user information.
See https://developer.github.com/changes/2016-06-07-reactions-api-update/.
Fixes #364.
Updates #356.

Update Reactions API (preview) for breaking change.

---

github/github.go
github/orgs_members.go
github/orgs_members_test.go
github/orgs_teams.go
github/orgs_teams_test.go
github/repos_collaborators.go
github/repos_collaborators_test.go

Fixes #262.
Change-Id: Ie9acf859346fce6b797b039d35b17e46f404e2a3

remove org permission content type

---

github/authorizations.go
github/git_commits.go
github/git_commits_test.go
github/git_tags.go
github/git_tags_test.go
github/github.go
github/repos_commits.go
github/repos_commits_test.go
github/users_gpg_keys.go
github/users_gpg_keys_test.go

Successfully tested using new "gpg_key" scopes.
Fixes #334.
Change-Id: I9b10ae5e7679f5196778d9eb3ded6168d7facfc3

add support for git signing API methods

---

github/examples_test.go
github/misc_test.go
github/repos_contents_test.go
github/repos_test.go
github/users.go

See #367 for discussion.
Change-Id: I10e26bddebeea2a1485fc4389caab1ff12421382

move examples to github_test package in examples_test.go

---

github/github.go
github/issues_timeline.go
github/issues_timeline_test.go

Fixes #360.
Change-Id: I69846ddeb5fd289ec81712cccaefde3f3931fd09

add support for Issue Timeline API

---

github/activity_watching_test.go
github/gists_comments_test.go
github/gists_test.go
github/git_tags_test.go
github/github_test.go
github/issues_events_test.go
github/issues_test.go
github/pulls.go
github/pulls_comments_test.go
github/pulls_test.go
github/repos_test.go

See #369 for motivation.
Change-Id: I7bf843b42a0d8869e72b6d0606bdc99893b10bdb

remove unnecessary newlines

---

github/event_types.go

Fixes #370.
Change-Id: I0a8567ae352bd2e9e973ac73383894d2b4cdfb9d

better support both Events API and Webhook events in PushEventCommit

---

github/authorizations_test.go

Change-Id: Ib5fd4e99b88ff01e3363e049177326b7ee97be93

add unit tests for #342 - CreateImpersonation and DeleteImpersonation

---

github/authorizations.go
github/event_types.go
github/github.go
github/migrations_source_import.go

Fixing some lint issues

---

github/github.go
github/timestamp_test.go
tests/integration/users_test.go

Fixed typo and removed unused vars

---

github/search.go
github/search_test.go

Added the field incomplete_results. It is docummented on https://developer.github.com/v3/search/#timeouts-and-incomplete-results

Adding missing field to search results

---

.travis.yml

Also update Go 1.6.2 to 1.6.3.

Travis: Add Go 1.7.

---

github/github.go
github/repos_forks.go
github/repos_projects.go
github/repos_projects_test.go

Fixes #432.
This also fixes a small typo in repos_forks.go for a GitHub API URL.
Change-Id: I4792114482f412f0eff54a6899a759fc9393ff88

Add support for new Projects Preview API

---

github/licenses.go
github/licenses_test.go
github/repos.go
github/repos_test.go

Update structs to reflect the new reponses returned from GitHub.
Fixes #471

Update License struct and add new RepositoryLicense struct

---

github/admin.go

@shurcooL: Thanks for catching this. Easy enough to fix.

Adjusts comment style based on feedback

---

github/repos_deployments.go
github/repos_deployments_test.go

Add methods for getting a single Deployment and single
DeploymentStatus.
Fixes #482.

Add Repositories.Deployments get methods

---

github/repos_commits.go
github/repos_commits_test.go

Add blob_url, raw_url, contents_url in CommitFile struct
Related issue #419
Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>

Add URLs in CommitFile

---

github/pulls.go

Adds support for SHA
https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

Support SHA in merges

---

github/activity_events.go
github/event_types.go
github/messages.go
github/messages_test.go

GitHub docs: https://developer.github.com/webhooks/#ping-event

Add the "PingEvent" structure.

---

github/gists.go

Just added the language property to the GistFile struct.

Add 'language' property to GistFile struct

---

github/issues.go
github/issues_comments.go
github/issues_labels.go
github/issues_milestones.go
github/pulls.go
github/pulls_comments.go
github/repos.go

Helps #536.
/cc @gmlewis @shurcooL

[improvement] Return nil when no error for better code readability

---

github/issues.go

Add issue.Locked field

---

github/issues.go
tests/fields/fields.go

Fixes #574 and also add issue into tests/field

add issue.ClosedBy field and add issue test into tests/field

---

github/event_types.go
github/github-accessors.go
github/integration_installation.go

added HTMLURL to IntegrationInstallationEvent and IntegrationInstallationRepositoriesEvent #591

added HTMLURL field  to IntegrationInstallation

---

github/github.go
github/orgs_projects.go
github/orgs_projects_test.go
github/repos_projects.go
github/repos_projects_test.go

ListProjects returns list of organization projects
CreateProject creates organization project

OrganizationsService: Add projects methods

---

github/event_types.go
github/github-accessors.go

Added support for PushEventRepository.ArchiveURL per https://developer.github.com/v3/activity/events/types/#pushevent

Support PushEventRepository.ArchiveURL

---

github/repos.go
github/repos_test.go

This PR adds required status checks methods as detailed in https://developer.github.com/v3/repos/branches/#get-required-status-checks-of-protected-branch
and https://developer.github.com/v3/repos/branches/#list-required-status-checks-contexts-of-protected-branch

RepositoriesService: Add required status checks methods

---

github/github.go
github/orgs_members.go
github/orgs_members_test.go
github/orgs_outside_collaborators.go
github/orgs_outside_collaborators_test.go
github/orgs_teams.go
github/orgs_teams_test.go
github/repos_collaborators.go
github/repos_collaborators_test.go

#607: Remove custom media type for Organization Memberships API

---

github/messages.go
github/messages_test.go

Addresses https://github.com/google/go-github/issues/618

Add DeliveryID function for webhook events

---

github/activity_events.go
github/event_types.go
github/github-accessors.go
github/messages.go
github/messages_test.go

@shurcooL I have now been able to isolate only the changes for this file based on your inputs. Thank you for your inputs. I was struggling for long on how to remove this. Please review these changes.
Resolves #569.

#569:3 Webhooks for OrgBlockEvent

---

github/repos_invitations.go

Add error check before return to make it consistent

---

github/git_trees.go
github/git_trees_test.go
github/github-accessors.go

Add URL field to TreeEntry

---

github/github-accessors.go
github/github.go
github/misc.go
github/misc_test.go
github/repos.go
github/repos_test.go

Fixes #648 support review Codes of Conduct API

Add Preview Suport To Conduct Api

---

github/github.go
github/github_test.go

#622 
Old message: ... rate reset in 26m8.032328588s
New messages:
... [rate reset in 12h26m00s]
... [rate reset in 26m08s]
... [rate reset in 8s]

Changed rate limit error message string

---

.travis.yml
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/issues_test.go
test/integration/misc_test.go
test/integration/pulls_test.go
test/integration/repos_test.go
test/integration/users_test.go

Update code with the latest breaking API changes so that it builds without errors.
All tests other than `TestRepositories_EditBranches` are passing. To fix that test, it requires someone with expertise in protection requests, and is out of scope of this change.

test/integration: Update for API changes to fix build.

---

github/github-accessors.go
github/github.go
github/repos.go
github/repos_test.go
github/search.go

Hi, 
This is my first PR to go-github and please feel free to let me know, if there is anything that needs to be changed or can be improved. Thank you!
Fixes https://github.com/google/go-github/issues/670

Add preview support to Topics API

---

github/repos.go
github/repos_test.go

This PR adds the experimental COC accept header to list calls

Allow COC to be returned in lists

---

github/github-accessors.go
github/pulls_reviews.go
github/pulls_reviews_test.go

https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review

Support commit_id for "Create a pull request review"

---

github/pulls.go
github/pulls_test.go

Add cryptographer-preview header to include GPG signed response

---

github/issues.go
github/issues_test.go

Re-submit of #679.
Changes in a761d22 is in reference to https://github.com/google/go-github/pull/679#discussion_r130531558.

github: add IsPullRequest helper (resubmit)

---

github/github-accessors.go
github/repos.go

Add has_projects field to Repository struct

---

github/github-accessors.go
github/repos.go

Add Archived flag to Repository struct as per changes announced by GitHub
- https://developer.github.com/changes/2017-11-08-archiving-repositories/
Fixes #776 
/cc @gmlewis @shurcooL

repos: add archived boolean field to Repository struct

---

github/event_types.go

Added 'review_requested' and 'review_request_removed' to PullRequestEvent action

---

github/event_types.go
github/github-accessors.go
github/pulls.go

Fixes https://github.com/google/go-github/issues/863.
Closes #824.

Fix PullRequestEvent struct for review_requested actions for the requested_reviewers struct field

---

github/misc.go
github/misc_test.go

Adding importer ips to `/meta` struct

misc: add importer field to struct

---

github/examples_test.go

This PR is about providing an example on how to create a pull request (it's always nice to have examples in the godoc).

Add an example for PullRequestsService.Create

---

github/examples_test.go

This PR adds an example on how to use ListTeams to get the ID of a team based on its name.

Add example to get a team ID from its name using ListTeams

---

github/event_types.go

Add "repositories" field to InstallationEvent

---

example/commitpr/main.go

This PR has been created with this program

Add example app for creating commit and PR

---

github/apps.go
github/apps_test.go

Fixes #932
Tested API with following script: https://gist.github.com/haya14busa/612373686d75c711baad1fbbcf17d5ed

Add find installation by org, repo and user API

---

github/apps.go
github/apps_test.go
github/github-accessors.go

installation have created_at and updated_at fields.
https://developer.github.com/v3/apps/#find-organization-installation

add created/updated at fields to Installation type

---

github/github-accessors.go
github/projects.go
github/projects_test.go

Project card archiving

---

github/activity_events.go
github/checks.go
github/checks_test.go
github/event_types.go
github/github-accessors.go
github/github.go
github/messages.go
github/messages_test.go

~~This is a work in progress~~
Adding support for the checks api as mentioned in #913 
Plan on supporting:

Add checks api

---

github/github-accessors.go
github/repos_community_health.go

Add IssueTemplate and PullRequestTemplate in ReposCommunityHealth struct

---

github/apps_marketplace.go
github/apps_marketplace_test.go
github/github.go

In reference to issue #917, removed custom 'valkyrie-preview' media type and Accept header

Removed mediaTypeMarketplacePreview

---

README.md

provide more clear contributing details so that contributor would able to read the CONTRIBUTING.md

provide more clear contributing details in README.md

---

github/github-accessors.go
github/repos.go
github/repos_test.go

Add UpdateRequiredStatusChecks function

---

.travis.yml
README.md

Remove support for Go 1.7

---

github/search.go
github/search_test.go

Use PathEscape on search query instead of QueryEscape

---

github/checks.go
github/github-accessors.go

Per: https://developer.github.com/v3/checks/runs/#get-a-single-check-run / https://developer.github.com/v3/checks/suites/#get-a-single-check-suite

Add NodeID to CheckRun, CheckSuite

---

github/event_types.go
github/github-accessors.go

Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>
Closes https://github.com/google/go-github/issues/993

Add assignee in PullRequestEvent

---

github/repos_releases.go
github/repos_releases_test.go

Restrict request params of CreateRelease and EditRelease to known subset

---

github/repos.go
github/repos_test.go
go.sum

Restrict request params of Create to known subset

---

github/orgs_hooks.go
github/orgs_hooks_test.go
github/repos_hooks.go
github/repos_hooks_test.go
github/strings_test.go

Restrict request params of CreateHook for repos and orgs to known subset

---

README.md

Correct import statement and update according to https://godoc.org/github.com/google/go-github/github.

fix import statement

---

github/github-accessors.go
github/repos_commits.go

Add previous_filename to CommitFile

---

github/github-accessors.go
github/users.go

The current User struct does not contain a field to store the `two_factor_authentication` property returned by authenticated user routes.
Issue: https://github.com/google/go-github/issues/1053

Add 2FA field to User struct

---

github/checks.go

Fixes #1060 
Adds a field for the `actions` object array, and a struct definition of that object's fields.

Add actions to check create/update

---

github/event_types.go
github/github-accessors.go

Fixes https://github.com/google/go-github/issues/1062
Closely related to #1061

Add RequestedAction to the CheckRunEvent

---

AUTHORS
github/github.go
github/migrations_user.go
github/repos_collaborators.go
github/repos_collaborators_test.go
github/repos_invitations.go
github/repos_invitations_test.go
github/users.go
github/users_test.go

Fixes #708 
cc @gmlewis would you please review 😄.

GitHub Repository Invitation API: Remove custom media type

---

github/git_commits.go
github/git_commits_test.go
github/git_tags.go
github/git_tags_test.go
github/github.go
github/pulls.go
github/pulls_test.go
github/repos_commits.go
github/repos_commits_test.go
github/users_gpg_keys.go
github/users_gpg_keys_test.go

Git Signing API: Remove custom media type

---

github/repos_collaborators_test.go

repo_collaborators_test.go: Remove whitespace

---

github/github-accessors.go
github/projects.go
github/projects_test.go
github/teams.go
github/teams_test.go

One test is failing, will fix it in a day or two

Add support for Preview organization projects

---

github/projects_test.go

projects_test.go: Add TestProject_marshall function

---

github/issues_test.go
github/projects_test.go
github/pulls_test.go
github/repos_deployments_test.go
github/repos_test.go
github/teams_test.go

tests: Replace all occurences of `acceptHeaders` with `wantAcceptHeaders`

---

github/examples_test.go
github/interactions_orgs.go
github/interactions_orgs_test.go
github/interactions_repos.go
github/interactions_repos_test.go

Added Interactions restrictions API for organizations

---

github/reactions.go

Hi! I've just fixed ineffassign issue. Please review this

Fix ineffassign issues

---

github/apps_installation.go
github/apps_installation_test.go

Fixes https://github.com/google/go-github/issues/1095

Fix API endpoints for add and remove repo for installation

---

github/github-accessors.go
github/issues_timeline.go

Example event:
$ curl -s -H 'Accept: application/vnd.github.mockingbird-preview' https://api.github.com/repos/tink-ab/four-eyes/issues/2/timeline | jq '.[1]'
{
"actor": {
"login": "evchen",
"id": 18511984,
"node_id": "MDQ6VXNlcjE4NTExOTg0",
"avatar_url": "https://avatars1.githubusercontent.com/u/18511984?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/evchen",
"html_url": "https://github.com/evchen",
"followers_url": "https://api.github.com/users/evchen/followers",
"following_url": "https://api.github.com/users/evchen/following{/other_user}",
"gists_url": "https://api.github.com/users/evchen/gists{/gist_id}",
"starred_url": "https://api.github.com/users/evchen/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/evchen/subscriptions", …

fix(timeline): add missing fields for cross-reference

---

github/repos_hooks.go
github/repos_hooks_test.go

Reverts google/go-github#1111.
Fixes #1114.

Revert "Removing 3 service hooks endpoints from the code and the test"

---

github/messages.go
github/messages_test.go

Fixes https://github.com/google/go-github/issues/1126

No webhook secret

---

github/event_types.go

It has been added by Github yesterday. https://developer.github.com/v3/activity/events/types/#pullrequestevent

Add "ready_for_review" to PullRequestEvent

---

github/github-accessors.go
github/issues_events.go

Added support for dismissed_review IssueEvent

---

AUTHORS
github/github-accessors.go
github/github.go
github/repos_pages.go
github/repos_pages_test.go

updated custom media type to Preview enable and disable Pages API

---

github/github-accessors.go
github/teams.go

Remove NodeID from NewTeam struct
fixes https://github.com/google/go-github/issues/1152

remove NodeID from NewTeam

---

github/checks.go
github/checks_test.go
github/github-accessors.go

Fixes https://github.com/google/go-github/issues/1155

Fix set check suite preferences options

---

github/github.go
github/repos.go
github/repos_test.go

Adding vulnerability-alerts endpoint
fixes: https://github.com/google/go-github/issues/1164

add vulnerability-alerts endpoint

---

github/pulls_reviews.go
github/pulls_reviews_test.go
go.sum

Fixes: #1174 
- Add UpdateReview to PullRequestReview.
- Add its test.

Add method for updating a pull request review

---

github/github.go
github/github_test.go

Fixes #1173.
Reviewers: can you think of any negative impacts this change might have on users of this package?

Return new http.Client when nil passed to NewClient

---

github/examples_test.go
github/github-accessors.go
github/github.go
github/pulls.go
github/pulls_test.go

Added update branch API

---

github/checks_test.go

I'm not sure how Travis didn't catch this broken unit test.

Fix unit test

---

github/admin_test.go

`admin.go` had the worst test coverage at 50%.

Coverage: admin.go

---

github/issues_timeline.go

(#510) Adds Type (*string) and Issue (*Issue) fields to timeline Source struct

---

github/event_types.go
github/github-accessors.go
go.sum

https://developer.github.com/v3/activity/events/types/#pushevent defines the statuses_url sent with each PushEvent webhook.

Add PullsURL to PushEventRepository

---

github/github-accessors.go
github/pulls.go
github/pulls_test.go

Fix 'Reqest' -> 'Request' (add back the 'u').

Fix 'Reqest' -> 'Request' (add back the 'u').

---

github/migrations.go
github/migrations_test.go

This PR adds ListOptions to the ListMigrations method.
Fixes #1277

Adding ListOptions to ListMigrations

---

github/pulls_reviews_test.go

This PR relates to (#55) and adds a test for the Reviewers resource.

added test for JSON marshalling for Reviewers - relates to (#55)

---

github/git_commits_test.go

This PR relates to (#55) and adds a test for the Commit resource.

added test for JSON marshalling of Commit - relates to (#55)

---

github/github.go
github/repos_pages.go
github/repos_pages_test.go

Have run search on "mediaTypePagesPreview" and removed it from everywhere, also have removed it from tests, though I am not sure if tests are actual anymore.
Fixes #1298.

Removed mediaTypePagesPreview header

---

github/github-accessors.go
github/issues_comments.go
github/issues_comments_test.go

Make IssueListCommentsOptions consistent with GitHub API

---

github/admin.go
github/event.go
github/event_types.go
github/github-accessors.go
github/github-stringify_test.go
github/messages.go
github/messages_test.go

Closes https://github.com/google/go-github/issues/1301.

Add support for UserEvent webhooks

---

github/admin_users.go
github/admin_users_test.go
github/github-accessors.go
github/github-stringify_test.go

feat(oauth impersonation): add create and delete endpoints

---

github/repos.go
github/repos_test.go

This PR adds the vulnerability-alerts GET endpoint.
Fixes #1341

Add vulnerability-alerts GET endpoint

---

CONTRIBUTING.md

I thought this was already in CONTRIBUTING.md, but couldn't find it, so I added a note.

Add note about force-push

---

github/github-accessors.go
github/github-stringify_test.go
github/github.go
github/github_test.go
github/pulls_comments.go
github/pulls_comments_test.go

Add support for multiline PR comments

---

github/github.go
github/issues.go
github/issues_labels.go
github/issues_labels_test.go
github/issues_test.go
github/orgs_members.go
github/orgs_members_test.go
github/pulls.go
github/pulls_test.go
github/repos.go
github/repos_collaborators.go
github/repos_collaborators_test.go
github/repos_test.go
github/search.go
github/teams.go
github/teams_discussion_comments.go
github/teams_discussion_comments_test.go
github/teams_discussions.go
github/teams_discussions_test.go
github/teams_members.go
github/teams_members_test.go
github/teams_test.go
github/users.go
github/users_test.go

closes https://github.com/google/go-github/issues/1351

Remove custom preview headers from "graduated" API

---

github/event.go
github/event_types.go
github/github-accessors.go
github/github.go
github/messages.go
github/messages_test.go
github/repos.go
github/repos_test.go

Add repository dispatch to trigger workflow on GitHub actions.

Add support for repository dispatches

---

github/teams.go
github/teams_test.go

Fixes #1267.
I wrote this PR to communicate my thoughts about one way to fix #1267 since I'm not sure I clearly communicated this idea when reviewing #1356.

Add removeParent to EditTeam

---

AUTHORS

No issue associated with this PR.

Update AUTHORS with recent contributors

---

github/github.go
github/migrations_source_import.go
github/migrations_source_import_test.go

- fixes: https://github.com/google/go-github/issues/1373

remove deprecated custom preview header

---

github/teams.go
github/teams_test.go

Remove IDPGroupList.Groups omitempty

---

github/apps_installation.go
github/apps_installation_test.go
github/github.go

Added support to revoke apps installation token

---

github/github.go
github/github_test.go
github/teams.go
github/teams_test.go

Support cursor pagination

---

github/event_types.go
github/github-accessors.go

Fixes https://github.com/google/go-github/issues/1243

Support new fields in PullRequestEvent for "synchronize" action

---

.github/workflows/tests.yml

- combine windows and linux configs into a single matrix, now that
actions/cache handles file paths properly
- update to latest actions/checkout and codecov actions

update github actions config

---

README.md

Add TODOs badge to the README

---

github/github-accessors.go
github/github-stringify_test.go
github/pulls_reviews.go

#892 and #802, electric boogaloo.

Add the AuthorAssociation field to PullRequestReview

---

github/actions_workflows.go
github/actions_workflows_test.go
github/github-accessors.go

I approved and merged #1411 which implements `Workflows` without pointers to fields which is inconsistent with the rest of the repo.
In light of #1429, #537, #180, #79, #45, and #19, I'm creating this PR to be more consistent with the repo.

Switch Workflow to use pointers

---

github/teams_members.go
github/teams_members_test.go

Fixes: https://github.com/google/go-github/issues/1422.

Update teams members endpoints+Remove deprecated ones

---

github/actions_workflow_jobs.go
github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/event_types.go
github/github-accessors.go
github/github-stringify_test.go
github/strings_test.go

Implement support for actions workflow runs

---

github/misc_test.go

add test for APIMeta json marshalling

---

github/actions_runners.go
github/actions_runners_test.go

Fixes: #1472.
Note to self: once this is merged, the next release to be built will need a semver major version bump, as this is a breaking change.

Update ListRunners with new response type - breaking change

---

github/github.go
github/github_test.go

Support for deprecating API authentication through query parameters

---

github/github-accessors.go
github/repos_deployments.go
github/repos_deployments_test.go

Add preview keys to the DeploymentStatus type. 
Include preview headers in ListDeploymentStatuses request.
Fixes #1494.

Update DeploymentStatus type

---

github/github.go
github/github_test.go

The upload endpoint is not `/api/v3` it is `/api/upload`
Tested against Github Enterprise

Correct Enterprise upload url

---

github/repos_collaborators.go
github/teams.go

Update permission levels for repositories owned by an organization 

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/actions_workflows.go
github/actions_workflows_test.go
github/github-accessors.go

Fixes: #1526 
Add methods and tests for :

Add support for workflow usage and workflow run usage API endpoints

---

github/actions_artifacts.go
github/actions_artifacts_test.go

I've based the implementation on ListWorkflowRunArtifacts  as the methods have similar behavior.
Issue at #1537

Add ListArtifacts to ActionsService

---

README.md
example/appengine/app.go
example/basicauth/main.go
example/commitpr/main.go
example/migrations/main.go
example/newrepo/main.go
example/simple/main.go
example/topics/main.go
github/doc.go
github/examples_test.go
go.mod
test/fields/fields.go
test/integration/activity_test.go
test/integration/authorizations_test.go
test/integration/github_test.go
test/integration/repos_test.go
test/integration/users_test.go

This PR is in preparation for the release of `v32.0.0`.

Prepare for release v32

---

github/licenses_test.go

Add JSON Marshal test for License

---

github/event.go
github/event_types.go
github/github-accessors.go
github/messages.go
github/messages_test.go

Add support for [workflow_dispatch] & [workflow_run] webhook events.
[workflow_dispatch]: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_dispatch
[workflow_run]: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run
Fixes #1598

Add Workflow run and dispatch events

---

github/repos_commits.go
github/repos_commits_test.go

Revert "Escape # in CompareCommits base and head refs"

---

github/github-accessors.go
github/github-stringify_test.go
github/repos_hooks.go

Add action, organization and installation objects to Webhook payload

---

github/apps_installation_test.go

This PR increases the code coverage of `apps_installation.go` from 76.2% to 95.2%.

Increase apps_installation.go code coverage

---

github/enterprise_actions_runners_test.go

This PR increases code coverage of `enterprise_actions_runners.go` from 52.4% to 100%.

Increase enterprise_actions_runners.go code coverage

---

github/users_emails_test.go

This PR increases code coverage for `users_emails.go`.

Increase users_emails.go code coverage

---

github/event_test.go

This PR increases code coverage of `event.go` to 100%.

Add event_test.go to increase code coverage

---

github/issues_events_test.go

This PR increases code coverage for `issues_events.go` to 100%.

Increase issues_events.go code coverage

---

github/actions_runners_test.go
github/apps_installation_test.go
github/enterprise_actions_runners_test.go
github/issues_events_test.go
github/pulls_reviewers_test.go
github/repos_test.go
github/repos_traffic_test.go
github/teams_discussion_comments_test.go
github/teams_discussions_test.go

This PR switches tests over to use the new test helper methods.

Use new test helpers

---

README.md

- Fixes #1641 
- Added Installation Instructions
- Added version badge sorted by latest semver

readme: add installation instructions

---

github/billing.go
github/billing_test.go
github/github.go

This PR adds the new services to the go-github client: Billing Services
https://docs.github.com/en/rest/reference/billing
Fixes: https://github.com/google/go-github/issues/1788
/cc @gmlewis

billing: implement billing services

---

github/apps_marketplace.go
github/github-accessors.go
github/github-accessors_test.go

Hello,
As described in issue #1775, I've added missing fields to MarketplacePlan and MarketplacePurchase structs.
Thanks,
Alex

Add missing fields to MarketplacePlan and MarketplacePurchase structs

---

README.md

This PR is to address the [review comments](https://github.com/google/go-github/pull/1796#pullrequestreview-590728346) made by @dmitshur in #1796.

Remove -u from go get in README.md

---

github/apps.go
github/apps_test.go
github/github-accessors.go
github/github-accessors_test.go

Addresses https://github.com/google/go-github/issues/1802

Add Actions field to InstallationPermissions model

---

github/actions_runner_groups.go
github/actions_runner_groups_test.go
github/github-accessors.go
github/github-accessors_test.go

Support self-hosted runner groups

---

github/apps.go
github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go

feature
The `Installation` type in AppService is missing a few fields from the JSON response.
This PR adds the fields
- AppSlug
- HasMultipleSingleFiles
- SuspendedAt
- SuspendedBy
- SingleFilePaths
Here is a dump of the JSON response:
```json
[
{
"id": <APP-ID>,
"account": {
"login": "<USER>",
"id": <ID>,
"node_id": "...",
"avatar_url": "https://avatars.githubusercontent.com/...",
"gravatar_id": "",
"url": "https://api.github.com/users/...",
"html_url": "https://github.com/...",
"followers_url": "https://api.github.com/users/.../followers",
"following_url": "https://api.github.com/users/.../following{/other_user}",
"gists_url": "https://api.github.com/users/.../gists{/gist_id}",
"starred_url": …
```

Apps.Installation: Add missing fields AppSlug, HasMultipleSingleFiles, SuspendedAt, SuspendedBy and SingleFilePaths

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_audit_log.go

Update hook_id to int64

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Add Workflow and WorkflowRun to WorkflowRunEvent

---

github/event_types.go
github/pulls.go

Update document links of event types

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Fixes https://github.com/google/go-github/issues/1868
Hopefully the commit message is okay! Such a small change wasn't really sure what to say.
I believe I followed all the other steps correctly in the `CONTRIBUTING.md` but let me know if something needs fixing.

Add missing fields to Star event

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/orgs_members.go
github/orgs_members_test.go
github/teams.go

Add support for the list failed organization invitations feature

---

github/actions_runner_groups.go
github/actions_runner_groups_test.go

Just a minor typo that slightly interfered with my `grep`s while working on https://github.com/integrations/terraform-provider-github/pull/821 :)

Typo fix: Runer -> Runner

---

github/actions_workflow_jobs_test.go

* TaskStep
* WorkflowJob
* Jobs
Helps with issue : #55

Adds test cases for JSON resource marshalling

---

github/actions_artifacts_test.go

* Artifact
* ArtifactList
Helps with issue : #55

Add test cases for JSON resource marshaling

---

github/teams_test.go

Add test for JSON marshaling for Teams

---

github/pulls_test.go

- PullRequestAutoMerge
- PullRequest
- PRLink
- PRLinks
- PullRequestBranch
- NewPullRequest
- PullRequestBranchUpdateOptions
- PullRequestBranchUpdateResponse
- pullRequestUpdate
- PullRequestMergeResult
- pullRequestMergeRequest
Helps With Issue : #55

 Add test cases for JSON resource marshaling

---

.github/dependabot.yml

Signed-off-by: Matthieu MOREL <mmorel-35@users.noreply.github.com>

chore(ci) : setup dependabot configuration

---

github/repos_invitations_test.go

Add test case for JSON resources marshaling 

---

github/repos_hooks_test.go

Add test cases for JSON resources marshaling

---

github/github_test.go
github/repos_hooks_test.go

Add test cases to verify that error responses contain status code

---

github/pulls_reviews.go

Remove outdated comment for #540

---

github/repos_test.go

Adds test-cases for JSON resources marshaling

---

github/github.go
github/github_test.go

Fix since+page pagination bug

---

github/messages.go

fix references to webhook types

---

github/actions_workflow_runs.go
github/actions_workflow_runs_test.go
github/github-accessors.go
github/github-accessors_test.go

Add `Actor` field to `WorkflowRun`.
Fixes: https://github.com/google/go-github/issues/2380

Add Actor field to WorkflowRun

---

github/teams_test.go

Hi creators,
I have added test case for :
IDPGroupList struct
under Helps: #55 issue
I have followed all the guidelines to contribute in this repository.
Please revert in case of any changes needed.
I am first time contributor of Hackoctober , It will be great if you review & accept my contribution.

Add test case for JSON resource marshaling

---

README.md

Relates to: #2513.
Thank you, @steven-terrana for the original PR.

Fix typo in README URL

---

github/repos_traffic_test.go

Added test for `TrafficBreakdownOptions`
Helps: #55

Add test for resource JSON marshaling

---

github/orgs_security_managers.go
github/orgs_security_managers_test.go

Add support for security manager endpoints

---

.github/workflows/linter.yml

This should hopefully resolve the issue found in: https://github.com/google/go-github/pull/2562
See: https://github.com/golangci/golangci-lint/issues/3107 for more information.

Bump golangci-lint version to 1.50.1

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Add installation in CodeScanningAlertEvent type.

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

Add milestone field to IssuesEvent

---

.github/workflows/linter.yml

This should hopefully fix the problems found in https://github.com/google/go-github/pull/2666, https://github.com/google/go-github/pull/2693 and https://github.com/google/go-github/pull/2695 .
See: https://github.com/golangci/golangci-lint/issues/825#issuecomment-629696537

Fix golangci-lint

---

.github/workflows/linter.yml

This should hopefully fix #2698 .

Remove example subdirs in GitHub Actions linter workflow

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_environments.go
github/repos_environments_test.go

Fixes: https://github.com/google/go-github/issues/2722

Add `CanAdminsBypass` to Environment

---

github/orgs.go
github/orgs_test.go

Add support for deleting an org

---

github/github-accessors.go
github/github-accessors_test.go
github/repos.go

Fixes #2719
This adds a few fields that were requested in #2719.

Add fields to `Branch Protection` endpoint

---

github/event_types.go
github/github-accessors.go
github/github-accessors_test.go

This pull request adds the `Requester` property to the `InstallationEvent` struct.

Add requester to InstallationEvent

---

github/actions_workflow_runs.go
github/github-accessors.go
github/github-accessors_test.go

Add workflow run display title

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/pulls_comments.go

https://github.com/google/go-github/issues/2832

Support line comments on PRs

---

github/github-accessors.go
github/github-accessors_test.go
github/repos_environments.go

Add prevent_self_review field on repo/deployment environments. See https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28#create-or-update-an-environment

Add prevent_self_review on repo environments

---

github/meta.go

Closes https://github.com/google/go-github/issues/2963

Add support for packages IP address for APIMeta

---

github/orgs_properties.go
github/orgs_properties_test.go

Fix broken CreateOrUpdateRepoCustomPropertyValues

---

github/github-accessors.go
github/github-accessors_test.go
github/orgs_audit_log.go

Add Referrer field to AuditEntry

---

github/event_types.go
github/event_types_test.go
github/github-accessors.go
github/github-accessors_test.go

Fixes: https://github.com/google/go-github/issues/3056

Add Topics to EditChange struct

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/teams.go
github/teams_test.go

Add NotificationSetting to NewTeam

---

github/copilot_test.go

Hotfix: Fix broken unit test in copilot_test.go

---

github/github-accessors.go
github/github-accessors_test.go
github/github-stringify_test.go
github/pulls_reviews.go

Fixes: #3219.
Reverts google/go-github#3169

Revert "Add CommitID, InReplyTo, and SubjectType to DraftReviewComment"

---

github/orgs_rules_test.go
github/repos_rules.go

Add Source field to RulesetRepositoryPropertyTargetParameters

---

github/repos_rules.go

Update comment for Ruleset

---

github/copilot_test.go

I spotted this typo during the review.

docs: Fix typo in test comment

---

script/lint.sh

ci: update golangci-lint to v1.63.4

---

REVIEWERS

I'm happy to review PRs within the repository.
My PR's can be found here: https://github.com/google/go-github/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aalexandear+is%3Aclosed

chore: Add alexandear to REVIEWERS

---

github/sub_issue.go
github/sub_issue_test.go

fix: Fix broken URL for `SubIssueService.Remove` endpoint

---

REVIEWERS

After working on this repository for about 2 months, I'm now ready to review new PRs.

chore: Add zyfy29 to REVIEWERS
